apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - migrate-job.yaml
  - api.yaml
  - web.yaml
  - worker.yaml
  - services.yaml
  - middleware.yaml
  - ingressroute.yaml
  - certificate.yaml
  - pdb.yaml
