// Code generated by MockGen. DO NOT EDIT.
// Source: team_member.go
//
// Generated by this command:
//
//	mockgen -source=team_member.go -destination=teammember/mock_team_member.go -package=teammember -mock_names=TeamMember=MockTeamMember
//

// Package teammember is a generated GoMock package.
package teammember

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/usenorn/norn/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamMember is a mock of TeamMember interface.
type MockTeamMember struct {
	ctrl     *gomock.Controller
	recorder *MockTeamMemberMockRecorder
	isgomock struct{}
}

// MockTeamMemberMockRecorder is the mock recorder for MockTeamMember.
type MockTeamMemberMockRecorder struct {
	mock *MockTeamMember
}

// NewMockTeamMember creates a new mock instance.
func NewMockTeamMember(ctrl *gomock.Controller) *MockTeamMember {
	mock := &MockTeamMember{ctrl: ctrl}
	mock.recorder = &MockTeamMemberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamMember) EXPECT() *MockTeamMemberMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamMember) Create(ctx context.Context, membership entity.TeamMembership) (entity.TeamMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, membership)
	ret0, _ := ret[0].(entity.TeamMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTeamMemberMockRecorder) Create(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamMember)(nil).Create), ctx, membership)
}

// Delete mocks base method.
func (m *MockTeamMember) Delete(ctx context.Context, teamID, accountID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, teamID, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamMemberMockRecorder) Delete(ctx, teamID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamMember)(nil).Delete), ctx, teamID, accountID)
}

// Get mocks base method.
func (m *MockTeamMember) Get(ctx context.Context, teamID, accountID uuid.UUID) (entity.TeamMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, teamID, accountID)
	ret0, _ := ret[0].(entity.TeamMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTeamMemberMockRecorder) Get(ctx, teamID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTeamMember)(nil).Get), ctx, teamID, accountID)
}

// ListByTeamID mocks base method.
func (m *MockTeamMember) ListByTeamID(ctx context.Context, teamID uuid.UUID) ([]entity.TeamMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTeamID", ctx, teamID)
	ret0, _ := ret[0].([]entity.TeamMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTeamID indicates an expected call of ListByTeamID.
func (mr *MockTeamMemberMockRecorder) ListByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTeamID", reflect.TypeOf((*MockTeamMember)(nil).ListByTeamID), ctx, teamID)
}
