import type { AcceptInvitation } from "$lib/workspace/accept-invitation";

export const acceptInvitationPreviewStates: Record<string, AcceptInvitation> = import.meta.env.DEV
	? {
			no_token: { kind: "no_token" },
			invalid: { kind: "invalid" },
			expired: { kind: "expired" },
			revoked: { kind: "revoked" },
			already_accepted: { kind: "already_accepted" },
			create_account: {
				kind: "create_account",
				workspace: { slug: "northwind", name: "Northwind" },
				email: "rae@northwind.co",
				invitedBy: { name: "Jun Park", email: "jun@northwind.co" },
				invitedAt: "2026-07-28T09:00:00Z",
				expiresAt: "2026-08-04T09:00:00Z",
				teams: ["Mobile"],
				role: "member",
			},
			create_account_admin: {
				kind: "create_account",
				workspace: { slug: "northwind", name: "Northwind" },
				email: "rae@northwind.co",
				invitedBy: { name: "Jun Park", email: "jun@northwind.co" },
				invitedAt: "2026-07-28T09:00:00Z",
				expiresAt: "2026-08-04T09:00:00Z",
				teams: ["Mobile"],
				role: "admin",
			},
			sign_in_required: {
				kind: "sign_in_required",
				workspace: { slug: "northwind", name: "Northwind" },
				email: "rae@northwind.co",
				invitedBy: { name: "Jun Park", email: "jun@northwind.co" },
				invitedAt: "2026-07-28T09:00:00Z",
				expiresAt: "2026-08-04T09:00:00Z",
				teams: ["Mobile"],
			},
			confirm: {
				kind: "confirm",
				workspace: { slug: "northwind", name: "Northwind" },
				email: "rae@northwind.co",
				invitedBy: { name: "Jun Park", email: "jun@northwind.co" },
				invitedAt: "2026-07-28T09:00:00Z",
				expiresAt: "2026-08-04T09:00:00Z",
				teams: ["Mobile"],
				role: "member",
				slot: "b2c3d4e5",
			},
			address_mismatch: {
				kind: "address_mismatch",
				email: "rae@northwind.co",
				signedIn: [
					{
						account: {
							id: "00000000-0000-4000-8000-0000000000a1",
							status: "active",
							email: "jun@northwind.co",
							displayName: "Jun Park",
							timezone: "UTC",
							hasPassword: true,
							createdAt: "2026-07-01T09:00:00Z",
						},
						defaultSlot: "a1b2c3d4",
						workspaces: [],
						current: true,
					},
				],
			},
			sso_required: {
				kind: "sso_required",
				workspace: { slug: "northwind", name: "Northwind" },
				email: "rae@northwind.co",
				invitedBy: { name: "Jun Park", email: "jun@northwind.co" },
				invitedAt: "2026-07-28T09:00:00Z",
				expiresAt: "2026-08-04T09:00:00Z",
				teams: ["Mobile"],
			},
			no_inviter: {
				kind: "create_account",
				workspace: { slug: "northwind", name: "Northwind" },
				email: "rae@northwind.co",
				invitedAt: "2026-07-28T09:00:00Z",
				expiresAt: "2026-08-04T09:00:00Z",
				teams: [],
				role: "member",
			},
			joined: { kind: "joined", workspace: { slug: "northwind", name: "Northwind" } },
			unavailable: { kind: "unavailable" },
		}
	: {};
