// Code generated by MockGen. DO NOT EDIT.
// Source: mcp_connections.go
//
// Generated by this command:
//
//	mockgen -source=mcp_connections.go -destination=mcpconnection/mock_mcp_connections.go -package=mcpconnection -mock_names=MCPConnections=MockMCPConnections
//

// Package mcpconnection is a generated GoMock package.
package mcpconnection

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/usenorn/norn/internal/entity"
	service "github.com/usenorn/norn/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockMCPConnections is a mock of MCPConnections interface.
type MockMCPConnections struct {
	ctrl     *gomock.Controller
	recorder *MockMCPConnectionsMockRecorder
	isgomock struct{}
}

// MockMCPConnectionsMockRecorder is the mock recorder for MockMCPConnections.
type MockMCPConnectionsMockRecorder struct {
	mock *MockMCPConnections
}

// NewMockMCPConnections creates a new mock instance.
func NewMockMCPConnections(ctrl *gomock.Controller) *MockMCPConnections {
	mock := &MockMCPConnections{ctrl: ctrl}
	mock.recorder = &MockMCPConnectionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPConnections) EXPECT() *MockMCPConnectionsMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockMCPConnections) Approve(ctx context.Context, requestID string) (service.MCPAuthorizationDecision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", ctx, requestID)
	ret0, _ := ret[0].(service.MCPAuthorizationDecision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Approve indicates an expected call of Approve.
func (mr *MockMCPConnectionsMockRecorder) Approve(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockMCPConnections)(nil).Approve), ctx, requestID)
}

// Authenticate mocks base method.
func (m *MockMCPConnections) Authenticate(ctx context.Context, token string) (entity.Actor, entity.MCPConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, token)
	ret0, _ := ret[0].(entity.Actor)
	ret1, _ := ret[1].(entity.MCPConnection)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockMCPConnectionsMockRecorder) Authenticate(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockMCPConnections)(nil).Authenticate), ctx, token)
}

// BeginAuthorization mocks base method.
func (m *MockMCPConnections) BeginAuthorization(ctx context.Context, input service.BeginMCPAuthorizationInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginAuthorization", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginAuthorization indicates an expected call of BeginAuthorization.
func (mr *MockMCPConnectionsMockRecorder) BeginAuthorization(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginAuthorization", reflect.TypeOf((*MockMCPConnections)(nil).BeginAuthorization), ctx, input)
}

// Deny mocks base method.
func (m *MockMCPConnections) Deny(ctx context.Context, requestID string) (service.MCPAuthorizationDecision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deny", ctx, requestID)
	ret0, _ := ret[0].(service.MCPAuthorizationDecision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deny indicates an expected call of Deny.
func (mr *MockMCPConnectionsMockRecorder) Deny(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deny", reflect.TypeOf((*MockMCPConnections)(nil).Deny), ctx, requestID)
}

// DescribeAuthorization mocks base method.
func (m *MockMCPConnections) DescribeAuthorization(ctx context.Context, requestID string) (service.MCPAuthorizationView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAuthorization", ctx, requestID)
	ret0, _ := ret[0].(service.MCPAuthorizationView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAuthorization indicates an expected call of DescribeAuthorization.
func (mr *MockMCPConnectionsMockRecorder) DescribeAuthorization(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAuthorization", reflect.TypeOf((*MockMCPConnections)(nil).DescribeAuthorization), ctx, requestID)
}

// Exchange mocks base method.
func (m *MockMCPConnections) Exchange(ctx context.Context, input service.ExchangeMCPCodeInput) (service.MCPTokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exchange", ctx, input)
	ret0, _ := ret[0].(service.MCPTokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exchange indicates an expected call of Exchange.
func (mr *MockMCPConnectionsMockRecorder) Exchange(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockMCPConnections)(nil).Exchange), ctx, input)
}

// List mocks base method.
func (m *MockMCPConnections) List(ctx context.Context) ([]entity.MCPConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.MCPConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMCPConnectionsMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMCPConnections)(nil).List), ctx)
}

// ListForWorkspace mocks base method.
func (m *MockMCPConnections) ListForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]service.OwnedMCPConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForWorkspace", ctx, workspaceID)
	ret0, _ := ret[0].([]service.OwnedMCPConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForWorkspace indicates an expected call of ListForWorkspace.
func (mr *MockMCPConnectionsMockRecorder) ListForWorkspace(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForWorkspace", reflect.TypeOf((*MockMCPConnections)(nil).ListForWorkspace), ctx, workspaceID)
}

// Narrow mocks base method.
func (m *MockMCPConnections) Narrow(ctx context.Context, connectionID uuid.UUID, input service.NarrowMCPConnectionInput) (entity.MCPConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Narrow", ctx, connectionID, input)
	ret0, _ := ret[0].(entity.MCPConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Narrow indicates an expected call of Narrow.
func (mr *MockMCPConnectionsMockRecorder) Narrow(ctx, connectionID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Narrow", reflect.TypeOf((*MockMCPConnections)(nil).Narrow), ctx, connectionID, input)
}

// Refresh mocks base method.
func (m *MockMCPConnections) Refresh(ctx context.Context, input service.RefreshMCPTokenInput) (service.MCPTokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, input)
	ret0, _ := ret[0].(service.MCPTokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockMCPConnectionsMockRecorder) Refresh(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockMCPConnections)(nil).Refresh), ctx, input)
}

// RegisterClient mocks base method.
func (m *MockMCPConnections) RegisterClient(ctx context.Context, input service.RegisterMCPClientInput) (entity.MCPClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterClient", ctx, input)
	ret0, _ := ret[0].(entity.MCPClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterClient indicates an expected call of RegisterClient.
func (mr *MockMCPConnectionsMockRecorder) RegisterClient(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterClient", reflect.TypeOf((*MockMCPConnections)(nil).RegisterClient), ctx, input)
}

// Revoke mocks base method.
func (m *MockMCPConnections) Revoke(ctx context.Context, connectionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, connectionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockMCPConnectionsMockRecorder) Revoke(ctx, connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockMCPConnections)(nil).Revoke), ctx, connectionID)
}

// RevokeByValue mocks base method.
func (m *MockMCPConnections) RevokeByValue(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByValue", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByValue indicates an expected call of RevokeByValue.
func (mr *MockMCPConnectionsMockRecorder) RevokeByValue(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByValue", reflect.TypeOf((*MockMCPConnections)(nil).RevokeByValue), ctx, token)
}

// RevokeInWorkspace mocks base method.
func (m *MockMCPConnections) RevokeInWorkspace(ctx context.Context, workspaceID, connectionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeInWorkspace", ctx, workspaceID, connectionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeInWorkspace indicates an expected call of RevokeInWorkspace.
func (mr *MockMCPConnectionsMockRecorder) RevokeInWorkspace(ctx, workspaceID, connectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeInWorkspace", reflect.TypeOf((*MockMCPConnections)(nil).RevokeInWorkspace), ctx, workspaceID, connectionID)
}
