import type { ReviewQueue } from "$lib/executions/reviews";

export type ReviewsPreview = { queue: ReviewQueue };

export const reviewPreviewStates: Record<string, ReviewsPreview> = import.meta.env.DEV
	? {
			loading: { queue: { kind: "loading" } },
			unavailable: { queue: { kind: "unavailable" } },
			empty: {
				queue: {
					kind: "ready",
					waiting: {
						questions: [],
						plans: [],
						changes: [],
					},
				},
			},
			questions: {
				queue: {
					kind: "ready",
					waiting: {
						questions: [{
							question: {
								id: "00000000-0000-4000-8000-000000001301",
								issueId: "3a2b1c0d-9e8f-4a7b-8c6d-5e4f3a2b1c0d",
								issueReference: "DSG-14",
								issueTitle: "Median helper for the ledger",
								executionId: "exec-01M0RCN1M3CGMBD9ZC12S4S5GF",
								stage: "planning",
								kind: "decision",
								state: "asked",
								blocking: true,
								options: ["Ledger package", "Shared utilities"],
								allowFreeText: true,
								question: "Should the helper live in the ledger package or in shared utilities?",
								default: "Ledger package",
								deadline: "2026-08-27T09:00:00Z",
								answered: false,
								expired: false,
								standing: "Ledger package",
								askedByName: "Rae's agent",
								actorKind: "agent",
								createdAt: "2026-08-24T09:10:00Z",
							},
							decision: { canDecide: true, decider: "Rae Okafor" },
						},
						{
							question: {
								id: "00000000-0000-4000-8000-000000001302",
								issueId: "4b3c2d1e-0f9a-4b8c-9d7e-6f5a4b3c2d1e",
								issueReference: "DSG-21",
								issueTitle: "Stop the export from timing out on large ledgers",
								executionId: "exec-01M0RCN1M3CGMBD9ZC12S4S5GF",
								stage: "implementation",
								kind: "decision",
								state: "asked",
								blocking: false,
								options: [],
								allowFreeText: true,
								question: "Keep the old export endpoint during the migration?",
								default: "Keep it for 30 days",
								deadline: "2026-08-27T09:00:00Z",
								answered: false,
								expired: false,
								standing: "Keep it for 30 days",
								askedByName: "Rae's agent",
								actorKind: "agent",
								createdAt: "2026-08-24T09:10:00Z",
							},
							decision: { canDecide: true, decider: "Sam Iwu" },
						}],
						plans: [],
						changes: [],
					},
				},
			},
			plans: {
				queue: {
					kind: "ready",
					waiting: {
						questions: [],
						plans: [{
							run: {
								execution: {
									id: "exec-01M0RCN1M3CGMBD9ZC12S4S5GH",
									reference: "DSG-30",
									workspaceId: "8f1c2f4a-6f2c-4a3e-9a1c-2b3d4e5f6071",
									issueId: "5c4d3e2f-1a0b-4c9d-8e7f-6a5b4c3d2e1f",
									issueReference: "DSG-30",
									issueTitle: "Split the invoice handler",
									agentName: "Rae's agent",
									runnerName: "rae-mbp",
									codebaseName: "northwind",
									attempt: 1,
									state: "awaiting_plan_approval",
									stage: "planning",
									params: { tool: "claude", model: "opus", permissionProfile: "standard" },
									queuedAt: "2026-08-24T09:02:00Z",
									startedAt: "2026-08-24T09:03:00Z",
									finishedAt: "2026-08-24T09:41:00Z",
								},
								change: {
									repositories: 0,
									commits: 0,
									additions: 0,
									deletions: 0,
									filesChanged: 0,
									pullRequests: 0,
								},
							},
							decision: { canDecide: true, decider: "Rae Okafor" },
						}],
						changes: [],
					},
				},
			},
			final: {
				queue: {
					kind: "ready",
					waiting: {
						questions: [],
						plans: [],
						changes: [{
							run: {
								execution: {
									id: "exec-01M0RCN1M3CGMBD9ZC12S4S5GF",
									reference: "DSG-14",
									workspaceId: "8f1c2f4a-6f2c-4a3e-9a1c-2b3d4e5f6071",
									issueId: "3a2b1c0d-9e8f-4a7b-8c6d-5e4f3a2b1c0d",
									issueReference: "DSG-14",
									issueTitle: "Median helper for the ledger",
									agentName: "Rae's agent",
									runnerName: "rae-mbp",
									codebaseName: "northwind",
									attempt: 1,
									state: "awaiting_review",
									stage: "review",
									params: { tool: "claude", model: "opus", permissionProfile: "standard" },
									queuedAt: "2026-08-24T09:02:00Z",
									startedAt: "2026-08-24T09:03:00Z",
									finishedAt: "2026-08-24T09:41:00Z",
								},
								change: {
									repositories: 2,
									commits: 5,
									additions: 1101,
									deletions: 89,
									filesChanged: 13,
									pullRequests: 0,
								},
							},
							decision: { canDecide: true, decider: "Rae Okafor" },
						}],
					},
				},
			},
			mixed: {
				queue: {
					kind: "ready",
					waiting: {
						questions: [{
							question: {
								id: "00000000-0000-4000-8000-000000001301",
								issueId: "3a2b1c0d-9e8f-4a7b-8c6d-5e4f3a2b1c0d",
								issueReference: "DSG-14",
								issueTitle: "Median helper for the ledger",
								executionId: "exec-01M0RCN1M3CGMBD9ZC12S4S5GF",
								stage: "planning",
								kind: "decision",
								state: "asked",
								blocking: true,
								options: ["Ledger package", "Shared utilities"],
								allowFreeText: true,
								question: "Should the helper live in the ledger package or in shared utilities?",
								default: "Ledger package",
								deadline: "2026-08-27T09:00:00Z",
								answered: false,
								expired: false,
								standing: "Ledger package",
								askedByName: "Rae's agent",
								actorKind: "agent",
								createdAt: "2026-08-24T09:10:00Z",
							},
							decision: { canDecide: true, decider: "Rae Okafor" },
						},
						{
							question: {
								id: "00000000-0000-4000-8000-000000001302",
								issueId: "4b3c2d1e-0f9a-4b8c-9d7e-6f5a4b3c2d1e",
								issueReference: "DSG-21",
								issueTitle: "Stop the export from timing out on large ledgers",
								executionId: "exec-01M0RCN1M3CGMBD9ZC12S4S5GF",
								stage: "implementation",
								kind: "decision",
								state: "asked",
								blocking: false,
								options: [],
								allowFreeText: true,
								question: "Keep the old export endpoint during the migration?",
								default: "Keep it for 30 days",
								deadline: "2026-08-27T09:00:00Z",
								answered: false,
								expired: false,
								standing: "Keep it for 30 days",
								askedByName: "Rae's agent",
								actorKind: "agent",
								createdAt: "2026-08-24T09:10:00Z",
							},
							decision: { canDecide: false, decider: "Sam Iwu" },
						}],
						plans: [{
							run: {
								execution: {
									id: "exec-01M0RCN1M3CGMBD9ZC12S4S5GH",
									reference: "DSG-30",
									workspaceId: "8f1c2f4a-6f2c-4a3e-9a1c-2b3d4e5f6071",
									issueId: "5c4d3e2f-1a0b-4c9d-8e7f-6a5b4c3d2e1f",
									issueReference: "DSG-30",
									issueTitle: "Split the invoice handler",
									agentName: "Rae's agent",
									runnerName: "rae-mbp",
									codebaseName: "northwind",
									attempt: 1,
									state: "awaiting_plan_approval",
									stage: "planning",
									params: { tool: "claude", model: "opus", permissionProfile: "standard" },
									queuedAt: "2026-08-24T09:02:00Z",
									startedAt: "2026-08-24T09:03:00Z",
									finishedAt: "2026-08-24T09:41:00Z",
								},
								change: {
									repositories: 0,
									commits: 0,
									additions: 0,
									deletions: 0,
									filesChanged: 0,
									pullRequests: 0,
								},
							},
							decision: { canDecide: true, decider: "Rae Okafor" },
						}],
						changes: [{
							run: {
								execution: {
									id: "exec-01M0RCN1M3CGMBD9ZC12S4S5GF",
									reference: "DSG-14",
									workspaceId: "8f1c2f4a-6f2c-4a3e-9a1c-2b3d4e5f6071",
									issueId: "3a2b1c0d-9e8f-4a7b-8c6d-5e4f3a2b1c0d",
									issueReference: "DSG-14",
									issueTitle: "Median helper for the ledger",
									agentName: "Rae's agent",
									runnerName: "rae-mbp",
									codebaseName: "northwind",
									attempt: 1,
									state: "awaiting_review",
									stage: "review",
									params: { tool: "claude", model: "opus", permissionProfile: "standard" },
									queuedAt: "2026-08-24T09:02:00Z",
									startedAt: "2026-08-24T09:03:00Z",
									finishedAt: "2026-08-24T09:41:00Z",
								},
								change: {
									repositories: 2,
									commits: 5,
									additions: 1101,
									deletions: 89,
									filesChanged: 13,
									pullRequests: 0,
								},
							},
							decision: { canDecide: false, decider: "Rae Okafor" },
						}],
					},
				},
			},
			not_yours: {
				queue: {
					kind: "ready",
					waiting: {
						questions: [{
							question: {
								id: "00000000-0000-4000-8000-000000001301",
								issueId: "3a2b1c0d-9e8f-4a7b-8c6d-5e4f3a2b1c0d",
								issueReference: "DSG-14",
								issueTitle: "Median helper for the ledger",
								executionId: "exec-01M0RCN1M3CGMBD9ZC12S4S5GF",
								stage: "planning",
								kind: "decision",
								state: "asked",
								blocking: true,
								options: ["Ledger package", "Shared utilities"],
								allowFreeText: true,
								question: "Should the helper live in the ledger package or in shared utilities?",
								default: "Ledger package",
								deadline: "2026-08-27T09:00:00Z",
								answered: false,
								expired: false,
								standing: "Ledger package",
								askedByName: "Rae's agent",
								actorKind: "agent",
								createdAt: "2026-08-24T09:10:00Z",
							},
							decision: { canDecide: false, decider: "Rae Okafor" },
						},
						{
							question: {
								id: "00000000-0000-4000-8000-000000001302",
								issueId: "4b3c2d1e-0f9a-4b8c-9d7e-6f5a4b3c2d1e",
								issueReference: "DSG-21",
								issueTitle: "Stop the export from timing out on large ledgers",
								executionId: "exec-01M0RCN1M3CGMBD9ZC12S4S5GF",
								stage: "implementation",
								kind: "decision",
								state: "asked",
								blocking: false,
								options: [],
								allowFreeText: true,
								question: "Keep the old export endpoint during the migration?",
								default: "Keep it for 30 days",
								deadline: "2026-08-27T09:00:00Z",
								answered: false,
								expired: false,
								standing: "Keep it for 30 days",
								askedByName: "Rae's agent",
								actorKind: "agent",
								createdAt: "2026-08-24T09:10:00Z",
							},
							decision: { canDecide: false, decider: "Sam Iwu" },
						}],
						plans: [{
							run: {
								execution: {
									id: "exec-01M0RCN1M3CGMBD9ZC12S4S5GH",
									reference: "DSG-30",
									workspaceId: "8f1c2f4a-6f2c-4a3e-9a1c-2b3d4e5f6071",
									issueId: "5c4d3e2f-1a0b-4c9d-8e7f-6a5b4c3d2e1f",
									issueReference: "DSG-30",
									issueTitle: "Split the invoice handler",
									agentName: "Rae's agent",
									runnerName: "rae-mbp",
									codebaseName: "northwind",
									attempt: 1,
									state: "awaiting_plan_approval",
									stage: "planning",
									params: { tool: "claude", model: "opus", permissionProfile: "standard" },
									queuedAt: "2026-08-24T09:02:00Z",
									startedAt: "2026-08-24T09:03:00Z",
									finishedAt: "2026-08-24T09:41:00Z",
								},
								change: {
									repositories: 0,
									commits: 0,
									additions: 0,
									deletions: 0,
									filesChanged: 0,
									pullRequests: 0,
								},
							},
							decision: { canDecide: false, decider: "Rae Okafor" },
						}],
						changes: [{
							run: {
								execution: {
									id: "exec-01M0RCN1M3CGMBD9ZC12S4S5GF",
									reference: "DSG-14",
									workspaceId: "8f1c2f4a-6f2c-4a3e-9a1c-2b3d4e5f6071",
									issueId: "3a2b1c0d-9e8f-4a7b-8c6d-5e4f3a2b1c0d",
									issueReference: "DSG-14",
									issueTitle: "Median helper for the ledger",
									agentName: "Rae's agent",
									runnerName: "rae-mbp",
									codebaseName: "northwind",
									attempt: 1,
									state: "awaiting_review",
									stage: "review",
									params: { tool: "claude", model: "opus", permissionProfile: "standard" },
									queuedAt: "2026-08-24T09:02:00Z",
									startedAt: "2026-08-24T09:03:00Z",
									finishedAt: "2026-08-24T09:41:00Z",
								},
								change: {
									repositories: 2,
									commits: 5,
									additions: 1101,
									deletions: 89,
									filesChanged: 13,
									pullRequests: 0,
								},
							},
							decision: { canDecide: false, decider: "Rae Okafor" },
						}],
					},
				},
			},
		}
	: {};
