export type Emoji = {
	glyph: string;
	name: string;
	words?: string[];
};

export const emojiLimit = 8;

export const emoji: Emoji[] = [
	{ glyph: "😀", name: "grinning", words: ["smile", "happy"] },
	{ glyph: "😃", name: "smiley", words: ["happy"] },
	{ glyph: "😄", name: "smile", words: ["happy"] },
	{ glyph: "😁", name: "grin" },
	{ glyph: "😆", name: "laughing", words: ["haha"] },
	{ glyph: "😂", name: "joy", words: ["laugh", "tears"] },
	{ glyph: "🤣", name: "rofl", words: ["laugh"] },
	{ glyph: "🙂", name: "slightly_smiling_face" },
	{ glyph: "😉", name: "wink" },
	{ glyph: "😊", name: "blush" },
	{ glyph: "😍", name: "heart_eyes", words: ["love"] },
	{ glyph: "😘", name: "kissing_heart", words: ["kiss"] },
	{ glyph: "😎", name: "sunglasses", words: ["cool"] },
	{ glyph: "🤩", name: "star_struck", words: ["wow"] },
	{ glyph: "🤗", name: "hugs" },
	{ glyph: "🤔", name: "thinking", words: ["hmm"] },
	{ glyph: "🤨", name: "raised_eyebrow", words: ["suspicious"] },
	{ glyph: "😐", name: "neutral_face" },
	{ glyph: "😑", name: "expressionless" },
	{ glyph: "🙄", name: "roll_eyes" },
	{ glyph: "😬", name: "grimacing", words: ["awkward"] },
	{ glyph: "😴", name: "sleeping", words: ["zzz"] },
	{ glyph: "😌", name: "relieved" },
	{ glyph: "😔", name: "pensive", words: ["sad"] },
	{ glyph: "😕", name: "confused" },
	{ glyph: "🙁", name: "slightly_frowning_face" },
	{ glyph: "😢", name: "cry", words: ["sad", "tear"] },
	{ glyph: "😭", name: "sob", words: ["cry", "sad"] },
	{ glyph: "😤", name: "triumph", words: ["huff"] },
	{ glyph: "😡", name: "rage", words: ["angry", "mad"] },
	{ glyph: "🤯", name: "exploding_head", words: ["mind", "blown"] },
	{ glyph: "😱", name: "scream", words: ["fear"] },
	{ glyph: "😳", name: "flushed", words: ["embarrassed"] },
	{ glyph: "🥵", name: "hot_face", words: ["heat"] },
	{ glyph: "🥶", name: "cold_face", words: ["freezing"] },
	{ glyph: "😷", name: "mask", words: ["sick"] },
	{ glyph: "🤒", name: "face_with_thermometer", words: ["sick", "ill"] },
	{ glyph: "🤮", name: "vomiting_face", words: ["sick"] },
	{ glyph: "🥳", name: "partying_face", words: ["party", "celebrate"] },
	{ glyph: "😈", name: "smiling_imp", words: ["devil"] },
	{ glyph: "🤡", name: "clown_face" },
	{ glyph: "👻", name: "ghost" },
	{ glyph: "💀", name: "skull", words: ["dead"] },
	{ glyph: "👽", name: "alien" },
	{ glyph: "🤖", name: "robot", words: ["bot", "agent"] },
	{ glyph: "👋", name: "wave", words: ["hello", "hi"] },
	{ glyph: "👍", name: "thumbsup", words: ["yes", "agree", "+1"] },
	{ glyph: "👎", name: "thumbsdown", words: ["no", "disagree", "-1"] },
	{ glyph: "👌", name: "ok_hand" },
	{ glyph: "🤝", name: "handshake", words: ["deal", "agree"] },
	{ glyph: "🙏", name: "pray", words: ["please", "thanks"] },
	{ glyph: "👏", name: "clap", words: ["applause"] },
	{ glyph: "🙌", name: "raised_hands", words: ["hooray"] },
	{ glyph: "💪", name: "muscle", words: ["strong"] },
	{ glyph: "🤞", name: "crossed_fingers", words: ["luck"] },
	{ glyph: "✌️", name: "v", words: ["peace"] },
	{ glyph: "🤙", name: "call_me_hand" },
	{ glyph: "☝️", name: "point_up" },
	{ glyph: "👇", name: "point_down" },
	{ glyph: "👉", name: "point_right" },
	{ glyph: "👈", name: "point_left" },
	{ glyph: "🫡", name: "saluting_face", words: ["yes", "roger"] },
	{ glyph: "❤️", name: "heart", words: ["love", "red"] },
	{ glyph: "🧡", name: "orange_heart" },
	{ glyph: "💛", name: "yellow_heart" },
	{ glyph: "💚", name: "green_heart" },
	{ glyph: "💙", name: "blue_heart" },
	{ glyph: "💜", name: "purple_heart" },
	{ glyph: "🖤", name: "black_heart" },
	{ glyph: "💔", name: "broken_heart" },
	{ glyph: "💯", name: "100", words: ["hundred", "perfect"] },
	{ glyph: "💥", name: "boom", words: ["explosion", "crash"] },
	{ glyph: "💫", name: "dizzy" },
	{ glyph: "✨", name: "sparkles", words: ["shiny", "new"] },
	{ glyph: "🔥", name: "fire", words: ["hot", "lit"] },
	{ glyph: "🎉", name: "tada", words: ["party", "celebrate", "ship"] },
	{ glyph: "🎊", name: "confetti_ball", words: ["party"] },
	{ glyph: "🎈", name: "balloon" },
	{ glyph: "🎁", name: "gift", words: ["present"] },
	{ glyph: "🏆", name: "trophy", words: ["win"] },
	{ glyph: "🥇", name: "first_place", words: ["gold", "win"] },
	{ glyph: "⭐", name: "star" },
	{ glyph: "🌟", name: "star2", words: ["glowing"] },
	{ glyph: "⚡", name: "zap", words: ["lightning", "fast"] },
	{ glyph: "☀️", name: "sunny", words: ["sun"] },
	{ glyph: "🌈", name: "rainbow" },
	{ glyph: "☁️", name: "cloud" },
	{ glyph: "🌧️", name: "rain_cloud", words: ["rain"] },
	{ glyph: "❄️", name: "snowflake", words: ["cold", "snow"] },
	{ glyph: "🌊", name: "ocean", words: ["wave", "water"] },
	{ glyph: "🌍", name: "earth_africa", words: ["world", "globe"] },
	{ glyph: "🌙", name: "crescent_moon", words: ["night"] },
	{ glyph: "🚀", name: "rocket", words: ["ship", "launch", "deploy"] },
	{ glyph: "🛠️", name: "hammer_and_wrench", words: ["tools", "fix"] },
	{ glyph: "🔧", name: "wrench", words: ["fix", "tool"] },
	{ glyph: "🔨", name: "hammer", words: ["build"] },
	{ glyph: "🐛", name: "bug", words: ["defect", "insect"] },
	{ glyph: "🪲", name: "beetle", words: ["bug"] },
	{ glyph: "🧪", name: "test_tube", words: ["test", "experiment"] },
	{ glyph: "🔬", name: "microscope", words: ["research", "look"] },
	{ glyph: "🔍", name: "mag", words: ["search", "find"] },
	{ glyph: "🔒", name: "lock", words: ["secure", "private"] },
	{ glyph: "🔑", name: "key", words: ["access"] },
	{ glyph: "🗝️", name: "old_key" },
	{ glyph: "📦", name: "package", words: ["box", "release"] },
	{ glyph: "📈", name: "chart_increasing", words: ["growth", "up"] },
	{ glyph: "📉", name: "chart_decreasing", words: ["down", "drop"] },
	{ glyph: "📊", name: "bar_chart", words: ["stats", "metrics"] },
	{ glyph: "📝", name: "memo", words: ["note", "write", "edit"] },
	{ glyph: "📋", name: "clipboard", words: ["copy", "list"] },
	{ glyph: "📌", name: "pushpin", words: ["pin"] },
	{ glyph: "📎", name: "paperclip", words: ["attach"] },
	{ glyph: "🗂️", name: "card_index_dividers", words: ["files"] },
	{ glyph: "📁", name: "file_folder", words: ["folder"] },
	{ glyph: "📅", name: "calendar", words: ["date", "due"] },
	{ glyph: "⏰", name: "alarm_clock", words: ["time", "deadline"] },
	{ glyph: "⏳", name: "hourglass_flowing_sand", words: ["waiting", "time"] },
	{ glyph: "🕐", name: "clock", words: ["time"] },
	{ glyph: "💡", name: "bulb", words: ["idea", "light"] },
	{ glyph: "💬", name: "speech_balloon", words: ["comment", "talk"] },
	{ glyph: "🗣️", name: "speaking_head", words: ["say"] },
	{ glyph: "📣", name: "mega", words: ["announce", "shout"] },
	{ glyph: "🔔", name: "bell", words: ["notify", "alert"] },
	{ glyph: "🔕", name: "no_bell", words: ["mute", "silence"] },
	{ glyph: "📞", name: "telephone_receiver", words: ["call", "phone"] },
	{ glyph: "✉️", name: "envelope", words: ["mail", "email"] },
	{ glyph: "💻", name: "computer", words: ["laptop", "code"] },
	{ glyph: "🖥️", name: "desktop_computer", words: ["screen"] },
	{ glyph: "📱", name: "iphone", words: ["phone", "mobile"] },
	{ glyph: "⌨️", name: "keyboard", words: ["type"] },
	{ glyph: "🖱️", name: "computer_mouse", words: ["click"] },
	{ glyph: "🗑️", name: "wastebasket", words: ["delete", "trash"] },
	{ glyph: "♻️", name: "recycle", words: ["reuse"] },
	{ glyph: "✅", name: "white_check_mark", words: ["done", "yes", "pass"] },
	{ glyph: "☑️", name: "ballot_box_with_check", words: ["checked"] },
	{ glyph: "❌", name: "x", words: ["no", "fail", "wrong"] },
	{ glyph: "⛔", name: "no_entry", words: ["stop", "blocked"] },
	{ glyph: "⚠️", name: "warning", words: ["caution", "careful"] },
	{ glyph: "❗", name: "exclamation", words: ["important"] },
	{ glyph: "❓", name: "question", words: ["ask", "unknown"] },
	{ glyph: "🚧", name: "construction", words: ["wip", "progress"] },
	{ glyph: "🚦", name: "vertical_traffic_light", words: ["ci", "status"] },
	{ glyph: "🔁", name: "repeat", words: ["retry", "loop"] },
	{ glyph: "⏪", name: "rewind", words: ["revert", "back"] },
	{ glyph: "⏩", name: "fast_forward", words: ["skip", "forward"] },
	{ glyph: "⏸️", name: "pause_button", words: ["hold", "wait"] },
	{ glyph: "▶️", name: "play_button", words: ["start", "run"] },
	{ glyph: "⏹️", name: "stop_button", words: ["stop"] },
	{ glyph: "👀", name: "eyes", words: ["look", "review", "watching"] },
	{ glyph: "🧠", name: "brain", words: ["think", "smart"] },
	{ glyph: "🫶", name: "heart_hands", words: ["love", "thanks"] },
	{ glyph: "☕", name: "coffee", words: ["break"] },
	{ glyph: "🍕", name: "pizza", words: ["food"] },
	{ glyph: "🍻", name: "beers", words: ["cheers", "drink"] },
	{ glyph: "🎯", name: "dart", words: ["target", "goal"] },
	{ glyph: "🧹", name: "broom", words: ["cleanup", "chore"] },
	{ glyph: "🩹", name: "adhesive_bandage", words: ["patch", "fix"] },
	{ glyph: "🧩", name: "puzzle_piece", words: ["piece", "part"] },
	{ glyph: "🪄", name: "magic_wand", words: ["magic"] },
	{ glyph: "🦄", name: "unicorn", words: ["rare"] },
	{ glyph: "🐳", name: "whale", words: ["docker"] },
	{ glyph: "🐙", name: "octopus", words: ["git"] },
	{ glyph: "🌱", name: "seedling", words: ["new", "grow"] },
	{ glyph: "🏁", name: "checkered_flag", words: ["finish", "done"] },
];

export function matchingEmoji(query: string, limit = emojiLimit): Emoji[] {
	const asked = query.trim().toLowerCase().replace(/:$/, "");

	if (asked === "") return emoji.slice(0, limit);

	const scored = emoji
		.map((found) => ({ found, score: scoreEmoji(found, asked) }))
		.filter((held) => held.score > 0)
		.sort((first, second) => second.score - first.score);

	return scored.slice(0, limit).map((held) => held.found);
}

function scoreEmoji(found: Emoji, asked: string): number {
	if (found.name === asked) return 100;
	if (found.name.startsWith(asked)) return 70;
	if (found.name.includes(asked)) return 40;
	if (found.words?.some((word) => word === asked)) return 60;
	if (found.words?.some((word) => word.startsWith(asked))) return 30;

	return 0;
}
