// Code generated by MockGen. DO NOT EDIT.
// Source: agent_mcp_server.go
//
// Generated by this command:
//
//	mockgen -source=agent_mcp_server.go -destination=agentmcpserver/mock_agent_mcp_server.go -package=agentmcpserver -mock_names=AgentMCPServer=MockAgentMCPServer
//

// Package agentmcpserver is a generated GoMock package.
package agentmcpserver

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/usenorn/norn/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentMCPServer is a mock of AgentMCPServer interface.
type MockAgentMCPServer struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMCPServerMockRecorder
	isgomock struct{}
}

// MockAgentMCPServerMockRecorder is the mock recorder for MockAgentMCPServer.
type MockAgentMCPServerMockRecorder struct {
	mock *MockAgentMCPServer
}

// NewMockAgentMCPServer creates a new mock instance.
func NewMockAgentMCPServer(ctrl *gomock.Controller) *MockAgentMCPServer {
	mock := &MockAgentMCPServer{ctrl: ctrl}
	mock.recorder = &MockAgentMCPServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentMCPServer) EXPECT() *MockAgentMCPServerMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockAgentMCPServer) Attach(ctx context.Context, attachment entity.AgentCapabilityAttachment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, attachment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attach indicates an expected call of Attach.
func (mr *MockAgentMCPServerMockRecorder) Attach(ctx, attachment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockAgentMCPServer)(nil).Attach), ctx, attachment)
}

// AttachedAgents mocks base method.
func (m *MockAgentMCPServer) AttachedAgents(ctx context.Context, workspaceID uuid.UUID) (map[uuid.UUID][]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachedAgents", ctx, workspaceID)
	ret0, _ := ret[0].(map[uuid.UUID][]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachedAgents indicates an expected call of AttachedAgents.
func (mr *MockAgentMCPServerMockRecorder) AttachedAgents(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachedAgents", reflect.TypeOf((*MockAgentMCPServer)(nil).AttachedAgents), ctx, workspaceID)
}

// CountOwned mocks base method.
func (m *MockAgentMCPServer) CountOwned(ctx context.Context, workspaceID uuid.UUID, agentID *uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOwned", ctx, workspaceID, agentID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOwned indicates an expected call of CountOwned.
func (mr *MockAgentMCPServerMockRecorder) CountOwned(ctx, workspaceID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOwned", reflect.TypeOf((*MockAgentMCPServer)(nil).CountOwned), ctx, workspaceID, agentID)
}

// Create mocks base method.
func (m *MockAgentMCPServer) Create(ctx context.Context, server entity.AgentMCPServer, secrets entity.AgentMCPSecrets) (entity.AgentMCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, server, secrets)
	ret0, _ := ret[0].(entity.AgentMCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAgentMCPServerMockRecorder) Create(ctx, server, secrets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentMCPServer)(nil).Create), ctx, server, secrets)
}

// Delete mocks base method.
func (m *MockAgentMCPServer) Delete(ctx context.Context, workspaceID, serverID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, workspaceID, serverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentMCPServerMockRecorder) Delete(ctx, workspaceID, serverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentMCPServer)(nil).Delete), ctx, workspaceID, serverID)
}

// Detach mocks base method.
func (m *MockAgentMCPServer) Detach(ctx context.Context, workspaceID, agentID, serverID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detach", ctx, workspaceID, agentID, serverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Detach indicates an expected call of Detach.
func (mr *MockAgentMCPServerMockRecorder) Detach(ctx, workspaceID, agentID, serverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockAgentMCPServer)(nil).Detach), ctx, workspaceID, agentID, serverID)
}

// Get mocks base method.
func (m *MockAgentMCPServer) Get(ctx context.Context, workspaceID, serverID uuid.UUID) (entity.AgentMCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, workspaceID, serverID)
	ret0, _ := ret[0].(entity.AgentMCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAgentMCPServerMockRecorder) Get(ctx, workspaceID, serverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentMCPServer)(nil).Get), ctx, workspaceID, serverID)
}

// ListByAgent mocks base method.
func (m *MockAgentMCPServer) ListByAgent(ctx context.Context, workspaceID, agentID uuid.UUID) ([]entity.AgentMCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAgent", ctx, workspaceID, agentID)
	ret0, _ := ret[0].([]entity.AgentMCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAgent indicates an expected call of ListByAgent.
func (mr *MockAgentMCPServerMockRecorder) ListByAgent(ctx, workspaceID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAgent", reflect.TypeOf((*MockAgentMCPServer)(nil).ListByAgent), ctx, workspaceID, agentID)
}

// ListLibrary mocks base method.
func (m *MockAgentMCPServer) ListLibrary(ctx context.Context, workspaceID uuid.UUID) ([]entity.AgentMCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLibrary", ctx, workspaceID)
	ret0, _ := ret[0].([]entity.AgentMCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLibrary indicates an expected call of ListLibrary.
func (mr *MockAgentMCPServerMockRecorder) ListLibrary(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLibrary", reflect.TypeOf((*MockAgentMCPServer)(nil).ListLibrary), ctx, workspaceID)
}

// Secrets mocks base method.
func (m *MockAgentMCPServer) Secrets(ctx context.Context, workspaceID, serverID uuid.UUID) (entity.AgentMCPSecrets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secrets", ctx, workspaceID, serverID)
	ret0, _ := ret[0].(entity.AgentMCPSecrets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Secrets indicates an expected call of Secrets.
func (mr *MockAgentMCPServerMockRecorder) Secrets(ctx, workspaceID, serverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secrets", reflect.TypeOf((*MockAgentMCPServer)(nil).Secrets), ctx, workspaceID, serverID)
}

// Update mocks base method.
func (m *MockAgentMCPServer) Update(ctx context.Context, server entity.AgentMCPServer, secrets entity.AgentMCPSecrets) (entity.AgentMCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, server, secrets)
	ret0, _ := ret[0].(entity.AgentMCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAgentMCPServerMockRecorder) Update(ctx, server, secrets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentMCPServer)(nil).Update), ctx, server, secrets)
}
