// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PreviewGateway is an object representing the database table.
type PreviewGateway struct {
	ID         string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name       string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	SecretHash []byte    `boil:"secret_hash" json:"secret_hash" toml:"secret_hash" yaml:"secret_hash"`
	Status     string    `boil:"status" json:"status" toml:"status" yaml:"status"`
	LastSeenAt null.Time `boil:"last_seen_at" json:"last_seen_at,omitempty" toml:"last_seen_at" yaml:"last_seen_at,omitempty"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *previewGatewayR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L previewGatewayL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PreviewGatewayColumns = struct {
	ID         string
	Name       string
	SecretHash string
	Status     string
	LastSeenAt string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "id",
	Name:       "name",
	SecretHash: "secret_hash",
	Status:     "status",
	LastSeenAt: "last_seen_at",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

var PreviewGatewayTableColumns = struct {
	ID         string
	Name       string
	SecretHash string
	Status     string
	LastSeenAt string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "preview_gateways.id",
	Name:       "preview_gateways.name",
	SecretHash: "preview_gateways.secret_hash",
	Status:     "preview_gateways.status",
	LastSeenAt: "preview_gateways.last_seen_at",
	CreatedAt:  "preview_gateways.created_at",
	UpdatedAt:  "preview_gateways.updated_at",
}

// Generated where

var PreviewGatewayWhere = struct {
	ID         whereHelperstring
	Name       whereHelperstring
	SecretHash whereHelper__byte
	Status     whereHelperstring
	LastSeenAt whereHelpernull_Time
	CreatedAt  whereHelpertime_Time
	UpdatedAt  whereHelpertime_Time
}{
	ID:         whereHelperstring{field: "\"preview_gateways\".\"id\""},
	Name:       whereHelperstring{field: "\"preview_gateways\".\"name\""},
	SecretHash: whereHelper__byte{field: "\"preview_gateways\".\"secret_hash\""},
	Status:     whereHelperstring{field: "\"preview_gateways\".\"status\""},
	LastSeenAt: whereHelpernull_Time{field: "\"preview_gateways\".\"last_seen_at\""},
	CreatedAt:  whereHelpertime_Time{field: "\"preview_gateways\".\"created_at\""},
	UpdatedAt:  whereHelpertime_Time{field: "\"preview_gateways\".\"updated_at\""},
}

// PreviewGatewayRels is where relationship names are stored.
var PreviewGatewayRels = struct {
}{}

// previewGatewayR is where relationships are stored.
type previewGatewayR struct {
}

// NewStruct creates a new relationship struct
func (*previewGatewayR) NewStruct() *previewGatewayR {
	return &previewGatewayR{}
}

// previewGatewayL is where Load methods for each relationship are stored.
type previewGatewayL struct{}

var (
	previewGatewayAllColumns            = []string{"id", "name", "secret_hash", "status", "last_seen_at", "created_at", "updated_at"}
	previewGatewayColumnsWithoutDefault = []string{"name", "secret_hash"}
	previewGatewayColumnsWithDefault    = []string{"id", "status", "last_seen_at", "created_at", "updated_at"}
	previewGatewayPrimaryKeyColumns     = []string{"id"}
	previewGatewayGeneratedColumns      = []string{}
)

type (
	// PreviewGatewaySlice is an alias for a slice of pointers to PreviewGateway.
	// This should almost always be used instead of []PreviewGateway.
	PreviewGatewaySlice []*PreviewGateway
	// PreviewGatewayHook is the signature for custom PreviewGateway hook methods
	PreviewGatewayHook func(context.Context, boil.ContextExecutor, *PreviewGateway) error

	previewGatewayQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	previewGatewayType                 = reflect.TypeOf(&PreviewGateway{})
	previewGatewayMapping              = queries.MakeStructMapping(previewGatewayType)
	previewGatewayPrimaryKeyMapping, _ = queries.BindMapping(previewGatewayType, previewGatewayMapping, previewGatewayPrimaryKeyColumns)
	previewGatewayInsertCacheMut       sync.RWMutex
	previewGatewayInsertCache          = make(map[string]insertCache)
	previewGatewayUpdateCacheMut       sync.RWMutex
	previewGatewayUpdateCache          = make(map[string]updateCache)
	previewGatewayUpsertCacheMut       sync.RWMutex
	previewGatewayUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var previewGatewayAfterSelectMu sync.Mutex
var previewGatewayAfterSelectHooks []PreviewGatewayHook

var previewGatewayBeforeInsertMu sync.Mutex
var previewGatewayBeforeInsertHooks []PreviewGatewayHook
var previewGatewayAfterInsertMu sync.Mutex
var previewGatewayAfterInsertHooks []PreviewGatewayHook

var previewGatewayBeforeUpdateMu sync.Mutex
var previewGatewayBeforeUpdateHooks []PreviewGatewayHook
var previewGatewayAfterUpdateMu sync.Mutex
var previewGatewayAfterUpdateHooks []PreviewGatewayHook

var previewGatewayBeforeDeleteMu sync.Mutex
var previewGatewayBeforeDeleteHooks []PreviewGatewayHook
var previewGatewayAfterDeleteMu sync.Mutex
var previewGatewayAfterDeleteHooks []PreviewGatewayHook

var previewGatewayBeforeUpsertMu sync.Mutex
var previewGatewayBeforeUpsertHooks []PreviewGatewayHook
var previewGatewayAfterUpsertMu sync.Mutex
var previewGatewayAfterUpsertHooks []PreviewGatewayHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PreviewGateway) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range previewGatewayAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PreviewGateway) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range previewGatewayBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PreviewGateway) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range previewGatewayAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PreviewGateway) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range previewGatewayBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PreviewGateway) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range previewGatewayAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PreviewGateway) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range previewGatewayBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PreviewGateway) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range previewGatewayAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PreviewGateway) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range previewGatewayBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PreviewGateway) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range previewGatewayAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPreviewGatewayHook registers your hook function for all future operations.
func AddPreviewGatewayHook(hookPoint boil.HookPoint, previewGatewayHook PreviewGatewayHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		previewGatewayAfterSelectMu.Lock()
		previewGatewayAfterSelectHooks = append(previewGatewayAfterSelectHooks, previewGatewayHook)
		previewGatewayAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		previewGatewayBeforeInsertMu.Lock()
		previewGatewayBeforeInsertHooks = append(previewGatewayBeforeInsertHooks, previewGatewayHook)
		previewGatewayBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		previewGatewayAfterInsertMu.Lock()
		previewGatewayAfterInsertHooks = append(previewGatewayAfterInsertHooks, previewGatewayHook)
		previewGatewayAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		previewGatewayBeforeUpdateMu.Lock()
		previewGatewayBeforeUpdateHooks = append(previewGatewayBeforeUpdateHooks, previewGatewayHook)
		previewGatewayBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		previewGatewayAfterUpdateMu.Lock()
		previewGatewayAfterUpdateHooks = append(previewGatewayAfterUpdateHooks, previewGatewayHook)
		previewGatewayAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		previewGatewayBeforeDeleteMu.Lock()
		previewGatewayBeforeDeleteHooks = append(previewGatewayBeforeDeleteHooks, previewGatewayHook)
		previewGatewayBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		previewGatewayAfterDeleteMu.Lock()
		previewGatewayAfterDeleteHooks = append(previewGatewayAfterDeleteHooks, previewGatewayHook)
		previewGatewayAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		previewGatewayBeforeUpsertMu.Lock()
		previewGatewayBeforeUpsertHooks = append(previewGatewayBeforeUpsertHooks, previewGatewayHook)
		previewGatewayBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		previewGatewayAfterUpsertMu.Lock()
		previewGatewayAfterUpsertHooks = append(previewGatewayAfterUpsertHooks, previewGatewayHook)
		previewGatewayAfterUpsertMu.Unlock()
	}
}

// One returns a single previewGateway record from the query.
func (q previewGatewayQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PreviewGateway, error) {
	o := &PreviewGateway{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for preview_gateways")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PreviewGateway records from the query.
func (q previewGatewayQuery) All(ctx context.Context, exec boil.ContextExecutor) (PreviewGatewaySlice, error) {
	var o []*PreviewGateway

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to PreviewGateway slice")
	}

	if len(previewGatewayAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PreviewGateway records in the query.
func (q previewGatewayQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count preview_gateways rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q previewGatewayQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if preview_gateways exists")
	}

	return count > 0, nil
}

// PreviewGateways retrieves all the records using an executor.
func PreviewGateways(mods ...qm.QueryMod) previewGatewayQuery {
	mods = append(mods, qm.From("\"preview_gateways\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"preview_gateways\".*"})
	}

	return previewGatewayQuery{q}
}

// FindPreviewGateway retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPreviewGateway(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*PreviewGateway, error) {
	previewGatewayObj := &PreviewGateway{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"preview_gateways\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, previewGatewayObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from preview_gateways")
	}

	if err = previewGatewayObj.doAfterSelectHooks(ctx, exec); err != nil {
		return previewGatewayObj, err
	}

	return previewGatewayObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PreviewGateway) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no preview_gateways provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(previewGatewayColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	previewGatewayInsertCacheMut.RLock()
	cache, cached := previewGatewayInsertCache[key]
	previewGatewayInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			previewGatewayAllColumns,
			previewGatewayColumnsWithDefault,
			previewGatewayColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(previewGatewayType, previewGatewayMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(previewGatewayType, previewGatewayMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"preview_gateways\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"preview_gateways\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into preview_gateways")
	}

	if !cached {
		previewGatewayInsertCacheMut.Lock()
		previewGatewayInsertCache[key] = cache
		previewGatewayInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PreviewGateway.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PreviewGateway) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	previewGatewayUpdateCacheMut.RLock()
	cache, cached := previewGatewayUpdateCache[key]
	previewGatewayUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			previewGatewayAllColumns,
			previewGatewayPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update preview_gateways, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"preview_gateways\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, previewGatewayPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(previewGatewayType, previewGatewayMapping, append(wl, previewGatewayPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update preview_gateways row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for preview_gateways")
	}

	if !cached {
		previewGatewayUpdateCacheMut.Lock()
		previewGatewayUpdateCache[key] = cache
		previewGatewayUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q previewGatewayQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for preview_gateways")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for preview_gateways")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PreviewGatewaySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), previewGatewayPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"preview_gateways\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, previewGatewayPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in previewGateway slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all previewGateway")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PreviewGateway) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no preview_gateways provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(previewGatewayColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	previewGatewayUpsertCacheMut.RLock()
	cache, cached := previewGatewayUpsertCache[key]
	previewGatewayUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			previewGatewayAllColumns,
			previewGatewayColumnsWithDefault,
			previewGatewayColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			previewGatewayAllColumns,
			previewGatewayPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert preview_gateways, could not build update column list")
		}

		ret := strmangle.SetComplement(previewGatewayAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(previewGatewayPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert preview_gateways, could not build conflict column list")
			}

			conflict = make([]string, len(previewGatewayPrimaryKeyColumns))
			copy(conflict, previewGatewayPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"preview_gateways\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(previewGatewayType, previewGatewayMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(previewGatewayType, previewGatewayMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert preview_gateways")
	}

	if !cached {
		previewGatewayUpsertCacheMut.Lock()
		previewGatewayUpsertCache[key] = cache
		previewGatewayUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PreviewGateway record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PreviewGateway) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no PreviewGateway provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), previewGatewayPrimaryKeyMapping)
	sql := "DELETE FROM \"preview_gateways\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from preview_gateways")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for preview_gateways")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q previewGatewayQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no previewGatewayQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from preview_gateways")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for preview_gateways")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PreviewGatewaySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(previewGatewayBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), previewGatewayPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"preview_gateways\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, previewGatewayPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from previewGateway slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for preview_gateways")
	}

	if len(previewGatewayAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PreviewGateway) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPreviewGateway(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PreviewGatewaySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PreviewGatewaySlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), previewGatewayPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"preview_gateways\".* FROM \"preview_gateways\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, previewGatewayPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in PreviewGatewaySlice")
	}

	*o = slice

	return nil
}

// PreviewGatewayExists checks if the PreviewGateway row exists.
func PreviewGatewayExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"preview_gateways\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if preview_gateways exists")
	}

	return exists, nil
}

// Exists checks if the PreviewGateway row exists.
func (o *PreviewGateway) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PreviewGatewayExists(ctx, exec, o.ID)
}
