// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WorkspaceIssueCriterionEvidence is an object representing the database table.
type WorkspaceIssueCriterionEvidence struct {
	ID                    string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	WorkspaceID           string      `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	IssueID               string      `boil:"issue_id" json:"issue_id" toml:"issue_id" yaml:"issue_id"`
	CriterionID           string      `boil:"criterion_id" json:"criterion_id" toml:"criterion_id" yaml:"criterion_id"`
	CriterionText         string      `boil:"criterion_text" json:"criterion_text" toml:"criterion_text" yaml:"criterion_text"`
	Kind                  string      `boil:"kind" json:"kind" toml:"kind" yaml:"kind"`
	Label                 string      `boil:"label" json:"label" toml:"label" yaml:"label"`
	URL                   string      `boil:"url" json:"url" toml:"url" yaml:"url"`
	AttachmentID          null.String `boil:"attachment_id" json:"attachment_id,omitempty" toml:"attachment_id" yaml:"attachment_id,omitempty"`
	DescriptionRevisionID null.String `boil:"description_revision_id" json:"description_revision_id,omitempty" toml:"description_revision_id" yaml:"description_revision_id,omitempty"`
	RecordedByAccountID   null.String `boil:"recorded_by_account_id" json:"recorded_by_account_id,omitempty" toml:"recorded_by_account_id" yaml:"recorded_by_account_id,omitempty"`
	RecordedAt            time.Time   `boil:"recorded_at" json:"recorded_at" toml:"recorded_at" yaml:"recorded_at"`

	R *workspaceIssueCriterionEvidenceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workspaceIssueCriterionEvidenceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkspaceIssueCriterionEvidenceColumns = struct {
	ID                    string
	WorkspaceID           string
	IssueID               string
	CriterionID           string
	CriterionText         string
	Kind                  string
	Label                 string
	URL                   string
	AttachmentID          string
	DescriptionRevisionID string
	RecordedByAccountID   string
	RecordedAt            string
}{
	ID:                    "id",
	WorkspaceID:           "workspace_id",
	IssueID:               "issue_id",
	CriterionID:           "criterion_id",
	CriterionText:         "criterion_text",
	Kind:                  "kind",
	Label:                 "label",
	URL:                   "url",
	AttachmentID:          "attachment_id",
	DescriptionRevisionID: "description_revision_id",
	RecordedByAccountID:   "recorded_by_account_id",
	RecordedAt:            "recorded_at",
}

var WorkspaceIssueCriterionEvidenceTableColumns = struct {
	ID                    string
	WorkspaceID           string
	IssueID               string
	CriterionID           string
	CriterionText         string
	Kind                  string
	Label                 string
	URL                   string
	AttachmentID          string
	DescriptionRevisionID string
	RecordedByAccountID   string
	RecordedAt            string
}{
	ID:                    "workspace_issue_criterion_evidence.id",
	WorkspaceID:           "workspace_issue_criterion_evidence.workspace_id",
	IssueID:               "workspace_issue_criterion_evidence.issue_id",
	CriterionID:           "workspace_issue_criterion_evidence.criterion_id",
	CriterionText:         "workspace_issue_criterion_evidence.criterion_text",
	Kind:                  "workspace_issue_criterion_evidence.kind",
	Label:                 "workspace_issue_criterion_evidence.label",
	URL:                   "workspace_issue_criterion_evidence.url",
	AttachmentID:          "workspace_issue_criterion_evidence.attachment_id",
	DescriptionRevisionID: "workspace_issue_criterion_evidence.description_revision_id",
	RecordedByAccountID:   "workspace_issue_criterion_evidence.recorded_by_account_id",
	RecordedAt:            "workspace_issue_criterion_evidence.recorded_at",
}

// Generated where

var WorkspaceIssueCriterionEvidenceWhere = struct {
	ID                    whereHelperstring
	WorkspaceID           whereHelperstring
	IssueID               whereHelperstring
	CriterionID           whereHelperstring
	CriterionText         whereHelperstring
	Kind                  whereHelperstring
	Label                 whereHelperstring
	URL                   whereHelperstring
	AttachmentID          whereHelpernull_String
	DescriptionRevisionID whereHelpernull_String
	RecordedByAccountID   whereHelpernull_String
	RecordedAt            whereHelpertime_Time
}{
	ID:                    whereHelperstring{field: "\"workspace_issue_criterion_evidence\".\"id\""},
	WorkspaceID:           whereHelperstring{field: "\"workspace_issue_criterion_evidence\".\"workspace_id\""},
	IssueID:               whereHelperstring{field: "\"workspace_issue_criterion_evidence\".\"issue_id\""},
	CriterionID:           whereHelperstring{field: "\"workspace_issue_criterion_evidence\".\"criterion_id\""},
	CriterionText:         whereHelperstring{field: "\"workspace_issue_criterion_evidence\".\"criterion_text\""},
	Kind:                  whereHelperstring{field: "\"workspace_issue_criterion_evidence\".\"kind\""},
	Label:                 whereHelperstring{field: "\"workspace_issue_criterion_evidence\".\"label\""},
	URL:                   whereHelperstring{field: "\"workspace_issue_criterion_evidence\".\"url\""},
	AttachmentID:          whereHelpernull_String{field: "\"workspace_issue_criterion_evidence\".\"attachment_id\""},
	DescriptionRevisionID: whereHelpernull_String{field: "\"workspace_issue_criterion_evidence\".\"description_revision_id\""},
	RecordedByAccountID:   whereHelpernull_String{field: "\"workspace_issue_criterion_evidence\".\"recorded_by_account_id\""},
	RecordedAt:            whereHelpertime_Time{field: "\"workspace_issue_criterion_evidence\".\"recorded_at\""},
}

// WorkspaceIssueCriterionEvidenceRels is where relationship names are stored.
var WorkspaceIssueCriterionEvidenceRels = struct {
	Attachment          string
	DescriptionRevision string
	RecordedByAccount   string
}{
	Attachment:          "Attachment",
	DescriptionRevision: "DescriptionRevision",
	RecordedByAccount:   "RecordedByAccount",
}

// workspaceIssueCriterionEvidenceR is where relationships are stored.
type workspaceIssueCriterionEvidenceR struct {
	Attachment          *WorkspaceIssueAttachment          `boil:"Attachment" json:"Attachment" toml:"Attachment" yaml:"Attachment"`
	DescriptionRevision *WorkspaceIssueDescriptionRevision `boil:"DescriptionRevision" json:"DescriptionRevision" toml:"DescriptionRevision" yaml:"DescriptionRevision"`
	RecordedByAccount   *Account                           `boil:"RecordedByAccount" json:"RecordedByAccount" toml:"RecordedByAccount" yaml:"RecordedByAccount"`
}

// NewStruct creates a new relationship struct
func (*workspaceIssueCriterionEvidenceR) NewStruct() *workspaceIssueCriterionEvidenceR {
	return &workspaceIssueCriterionEvidenceR{}
}

func (o *WorkspaceIssueCriterionEvidence) GetAttachment() *WorkspaceIssueAttachment {
	if o == nil {
		return nil
	}

	return o.R.GetAttachment()
}

func (r *workspaceIssueCriterionEvidenceR) GetAttachment() *WorkspaceIssueAttachment {
	if r == nil {
		return nil
	}

	return r.Attachment
}

func (o *WorkspaceIssueCriterionEvidence) GetDescriptionRevision() *WorkspaceIssueDescriptionRevision {
	if o == nil {
		return nil
	}

	return o.R.GetDescriptionRevision()
}

func (r *workspaceIssueCriterionEvidenceR) GetDescriptionRevision() *WorkspaceIssueDescriptionRevision {
	if r == nil {
		return nil
	}

	return r.DescriptionRevision
}

func (o *WorkspaceIssueCriterionEvidence) GetRecordedByAccount() *Account {
	if o == nil {
		return nil
	}

	return o.R.GetRecordedByAccount()
}

func (r *workspaceIssueCriterionEvidenceR) GetRecordedByAccount() *Account {
	if r == nil {
		return nil
	}

	return r.RecordedByAccount
}

// workspaceIssueCriterionEvidenceL is where Load methods for each relationship are stored.
type workspaceIssueCriterionEvidenceL struct{}

var (
	workspaceIssueCriterionEvidenceAllColumns            = []string{"id", "workspace_id", "issue_id", "criterion_id", "criterion_text", "kind", "label", "url", "attachment_id", "description_revision_id", "recorded_by_account_id", "recorded_at"}
	workspaceIssueCriterionEvidenceColumnsWithoutDefault = []string{"workspace_id", "issue_id", "criterion_id", "kind"}
	workspaceIssueCriterionEvidenceColumnsWithDefault    = []string{"id", "criterion_text", "label", "url", "attachment_id", "description_revision_id", "recorded_by_account_id", "recorded_at"}
	workspaceIssueCriterionEvidencePrimaryKeyColumns     = []string{"id"}
	workspaceIssueCriterionEvidenceGeneratedColumns      = []string{}
)

type (
	// WorkspaceIssueCriterionEvidenceSlice is an alias for a slice of pointers to WorkspaceIssueCriterionEvidence.
	// This should almost always be used instead of []WorkspaceIssueCriterionEvidence.
	WorkspaceIssueCriterionEvidenceSlice []*WorkspaceIssueCriterionEvidence
	// WorkspaceIssueCriterionEvidenceHook is the signature for custom WorkspaceIssueCriterionEvidence hook methods
	WorkspaceIssueCriterionEvidenceHook func(context.Context, boil.ContextExecutor, *WorkspaceIssueCriterionEvidence) error

	workspaceIssueCriterionEvidenceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workspaceIssueCriterionEvidenceType                 = reflect.TypeOf(&WorkspaceIssueCriterionEvidence{})
	workspaceIssueCriterionEvidenceMapping              = queries.MakeStructMapping(workspaceIssueCriterionEvidenceType)
	workspaceIssueCriterionEvidencePrimaryKeyMapping, _ = queries.BindMapping(workspaceIssueCriterionEvidenceType, workspaceIssueCriterionEvidenceMapping, workspaceIssueCriterionEvidencePrimaryKeyColumns)
	workspaceIssueCriterionEvidenceInsertCacheMut       sync.RWMutex
	workspaceIssueCriterionEvidenceInsertCache          = make(map[string]insertCache)
	workspaceIssueCriterionEvidenceUpdateCacheMut       sync.RWMutex
	workspaceIssueCriterionEvidenceUpdateCache          = make(map[string]updateCache)
	workspaceIssueCriterionEvidenceUpsertCacheMut       sync.RWMutex
	workspaceIssueCriterionEvidenceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workspaceIssueCriterionEvidenceAfterSelectMu sync.Mutex
var workspaceIssueCriterionEvidenceAfterSelectHooks []WorkspaceIssueCriterionEvidenceHook

var workspaceIssueCriterionEvidenceBeforeInsertMu sync.Mutex
var workspaceIssueCriterionEvidenceBeforeInsertHooks []WorkspaceIssueCriterionEvidenceHook
var workspaceIssueCriterionEvidenceAfterInsertMu sync.Mutex
var workspaceIssueCriterionEvidenceAfterInsertHooks []WorkspaceIssueCriterionEvidenceHook

var workspaceIssueCriterionEvidenceBeforeUpdateMu sync.Mutex
var workspaceIssueCriterionEvidenceBeforeUpdateHooks []WorkspaceIssueCriterionEvidenceHook
var workspaceIssueCriterionEvidenceAfterUpdateMu sync.Mutex
var workspaceIssueCriterionEvidenceAfterUpdateHooks []WorkspaceIssueCriterionEvidenceHook

var workspaceIssueCriterionEvidenceBeforeDeleteMu sync.Mutex
var workspaceIssueCriterionEvidenceBeforeDeleteHooks []WorkspaceIssueCriterionEvidenceHook
var workspaceIssueCriterionEvidenceAfterDeleteMu sync.Mutex
var workspaceIssueCriterionEvidenceAfterDeleteHooks []WorkspaceIssueCriterionEvidenceHook

var workspaceIssueCriterionEvidenceBeforeUpsertMu sync.Mutex
var workspaceIssueCriterionEvidenceBeforeUpsertHooks []WorkspaceIssueCriterionEvidenceHook
var workspaceIssueCriterionEvidenceAfterUpsertMu sync.Mutex
var workspaceIssueCriterionEvidenceAfterUpsertHooks []WorkspaceIssueCriterionEvidenceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkspaceIssueCriterionEvidence) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceIssueCriterionEvidenceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkspaceIssueCriterionEvidence) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceIssueCriterionEvidenceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkspaceIssueCriterionEvidence) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceIssueCriterionEvidenceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkspaceIssueCriterionEvidence) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceIssueCriterionEvidenceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkspaceIssueCriterionEvidence) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceIssueCriterionEvidenceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkspaceIssueCriterionEvidence) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceIssueCriterionEvidenceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkspaceIssueCriterionEvidence) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceIssueCriterionEvidenceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkspaceIssueCriterionEvidence) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceIssueCriterionEvidenceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkspaceIssueCriterionEvidence) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceIssueCriterionEvidenceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkspaceIssueCriterionEvidenceHook registers your hook function for all future operations.
func AddWorkspaceIssueCriterionEvidenceHook(hookPoint boil.HookPoint, workspaceIssueCriterionEvidenceHook WorkspaceIssueCriterionEvidenceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workspaceIssueCriterionEvidenceAfterSelectMu.Lock()
		workspaceIssueCriterionEvidenceAfterSelectHooks = append(workspaceIssueCriterionEvidenceAfterSelectHooks, workspaceIssueCriterionEvidenceHook)
		workspaceIssueCriterionEvidenceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workspaceIssueCriterionEvidenceBeforeInsertMu.Lock()
		workspaceIssueCriterionEvidenceBeforeInsertHooks = append(workspaceIssueCriterionEvidenceBeforeInsertHooks, workspaceIssueCriterionEvidenceHook)
		workspaceIssueCriterionEvidenceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workspaceIssueCriterionEvidenceAfterInsertMu.Lock()
		workspaceIssueCriterionEvidenceAfterInsertHooks = append(workspaceIssueCriterionEvidenceAfterInsertHooks, workspaceIssueCriterionEvidenceHook)
		workspaceIssueCriterionEvidenceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workspaceIssueCriterionEvidenceBeforeUpdateMu.Lock()
		workspaceIssueCriterionEvidenceBeforeUpdateHooks = append(workspaceIssueCriterionEvidenceBeforeUpdateHooks, workspaceIssueCriterionEvidenceHook)
		workspaceIssueCriterionEvidenceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workspaceIssueCriterionEvidenceAfterUpdateMu.Lock()
		workspaceIssueCriterionEvidenceAfterUpdateHooks = append(workspaceIssueCriterionEvidenceAfterUpdateHooks, workspaceIssueCriterionEvidenceHook)
		workspaceIssueCriterionEvidenceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workspaceIssueCriterionEvidenceBeforeDeleteMu.Lock()
		workspaceIssueCriterionEvidenceBeforeDeleteHooks = append(workspaceIssueCriterionEvidenceBeforeDeleteHooks, workspaceIssueCriterionEvidenceHook)
		workspaceIssueCriterionEvidenceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workspaceIssueCriterionEvidenceAfterDeleteMu.Lock()
		workspaceIssueCriterionEvidenceAfterDeleteHooks = append(workspaceIssueCriterionEvidenceAfterDeleteHooks, workspaceIssueCriterionEvidenceHook)
		workspaceIssueCriterionEvidenceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workspaceIssueCriterionEvidenceBeforeUpsertMu.Lock()
		workspaceIssueCriterionEvidenceBeforeUpsertHooks = append(workspaceIssueCriterionEvidenceBeforeUpsertHooks, workspaceIssueCriterionEvidenceHook)
		workspaceIssueCriterionEvidenceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workspaceIssueCriterionEvidenceAfterUpsertMu.Lock()
		workspaceIssueCriterionEvidenceAfterUpsertHooks = append(workspaceIssueCriterionEvidenceAfterUpsertHooks, workspaceIssueCriterionEvidenceHook)
		workspaceIssueCriterionEvidenceAfterUpsertMu.Unlock()
	}
}

// One returns a single workspaceIssueCriterionEvidence record from the query.
func (q workspaceIssueCriterionEvidenceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkspaceIssueCriterionEvidence, error) {
	o := &WorkspaceIssueCriterionEvidence{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for workspace_issue_criterion_evidence")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkspaceIssueCriterionEvidence records from the query.
func (q workspaceIssueCriterionEvidenceQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkspaceIssueCriterionEvidenceSlice, error) {
	var o []*WorkspaceIssueCriterionEvidence

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to WorkspaceIssueCriterionEvidence slice")
	}

	if len(workspaceIssueCriterionEvidenceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkspaceIssueCriterionEvidence records in the query.
func (q workspaceIssueCriterionEvidenceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count workspace_issue_criterion_evidence rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workspaceIssueCriterionEvidenceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if workspace_issue_criterion_evidence exists")
	}

	return count > 0, nil
}

// Attachment pointed to by the foreign key.
func (o *WorkspaceIssueCriterionEvidence) Attachment(mods ...qm.QueryMod) workspaceIssueAttachmentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AttachmentID),
	}

	queryMods = append(queryMods, mods...)

	return WorkspaceIssueAttachments(queryMods...)
}

// DescriptionRevision pointed to by the foreign key.
func (o *WorkspaceIssueCriterionEvidence) DescriptionRevision(mods ...qm.QueryMod) workspaceIssueDescriptionRevisionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DescriptionRevisionID),
	}

	queryMods = append(queryMods, mods...)

	return WorkspaceIssueDescriptionRevisions(queryMods...)
}

// RecordedByAccount pointed to by the foreign key.
func (o *WorkspaceIssueCriterionEvidence) RecordedByAccount(mods ...qm.QueryMod) accountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.RecordedByAccountID),
	}

	queryMods = append(queryMods, mods...)

	return Accounts(queryMods...)
}

// LoadAttachment allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workspaceIssueCriterionEvidenceL) LoadAttachment(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceIssueCriterionEvidence any, mods queries.Applicator) error {
	var slice []*WorkspaceIssueCriterionEvidence
	var object *WorkspaceIssueCriterionEvidence

	if singular {
		var ok bool
		object, ok = maybeWorkspaceIssueCriterionEvidence.(*WorkspaceIssueCriterionEvidence)
		if !ok {
			object = new(WorkspaceIssueCriterionEvidence)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceIssueCriterionEvidence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceIssueCriterionEvidence))
			}
		}
	} else {
		s, ok := maybeWorkspaceIssueCriterionEvidence.(*[]*WorkspaceIssueCriterionEvidence)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceIssueCriterionEvidence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceIssueCriterionEvidence))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceIssueCriterionEvidenceR{}
		}
		if !queries.IsNil(object.AttachmentID) {
			args[object.AttachmentID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceIssueCriterionEvidenceR{}
			}

			if !queries.IsNil(obj.AttachmentID) {
				args[obj.AttachmentID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspace_issue_attachments`),
		qm.WhereIn(`workspace_issue_attachments.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load WorkspaceIssueAttachment")
	}

	var resultSlice []*WorkspaceIssueAttachment
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice WorkspaceIssueAttachment")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workspace_issue_attachments")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspace_issue_attachments")
	}

	if len(workspaceIssueAttachmentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Attachment = foreign
		if foreign.R == nil {
			foreign.R = &workspaceIssueAttachmentR{}
		}
		foreign.R.AttachmentWorkspaceIssueCriterionEvidences = append(foreign.R.AttachmentWorkspaceIssueCriterionEvidences, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.AttachmentID, foreign.ID) {
				local.R.Attachment = foreign
				if foreign.R == nil {
					foreign.R = &workspaceIssueAttachmentR{}
				}
				foreign.R.AttachmentWorkspaceIssueCriterionEvidences = append(foreign.R.AttachmentWorkspaceIssueCriterionEvidences, local)
				break
			}
		}
	}

	return nil
}

// LoadDescriptionRevision allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workspaceIssueCriterionEvidenceL) LoadDescriptionRevision(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceIssueCriterionEvidence any, mods queries.Applicator) error {
	var slice []*WorkspaceIssueCriterionEvidence
	var object *WorkspaceIssueCriterionEvidence

	if singular {
		var ok bool
		object, ok = maybeWorkspaceIssueCriterionEvidence.(*WorkspaceIssueCriterionEvidence)
		if !ok {
			object = new(WorkspaceIssueCriterionEvidence)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceIssueCriterionEvidence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceIssueCriterionEvidence))
			}
		}
	} else {
		s, ok := maybeWorkspaceIssueCriterionEvidence.(*[]*WorkspaceIssueCriterionEvidence)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceIssueCriterionEvidence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceIssueCriterionEvidence))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceIssueCriterionEvidenceR{}
		}
		if !queries.IsNil(object.DescriptionRevisionID) {
			args[object.DescriptionRevisionID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceIssueCriterionEvidenceR{}
			}

			if !queries.IsNil(obj.DescriptionRevisionID) {
				args[obj.DescriptionRevisionID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspace_issue_description_revisions`),
		qm.WhereIn(`workspace_issue_description_revisions.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load WorkspaceIssueDescriptionRevision")
	}

	var resultSlice []*WorkspaceIssueDescriptionRevision
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice WorkspaceIssueDescriptionRevision")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workspace_issue_description_revisions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspace_issue_description_revisions")
	}

	if len(workspaceIssueDescriptionRevisionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.DescriptionRevision = foreign
		if foreign.R == nil {
			foreign.R = &workspaceIssueDescriptionRevisionR{}
		}
		foreign.R.DescriptionRevisionWorkspaceIssueCriterionEvidences = append(foreign.R.DescriptionRevisionWorkspaceIssueCriterionEvidences, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.DescriptionRevisionID, foreign.ID) {
				local.R.DescriptionRevision = foreign
				if foreign.R == nil {
					foreign.R = &workspaceIssueDescriptionRevisionR{}
				}
				foreign.R.DescriptionRevisionWorkspaceIssueCriterionEvidences = append(foreign.R.DescriptionRevisionWorkspaceIssueCriterionEvidences, local)
				break
			}
		}
	}

	return nil
}

// LoadRecordedByAccount allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workspaceIssueCriterionEvidenceL) LoadRecordedByAccount(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceIssueCriterionEvidence any, mods queries.Applicator) error {
	var slice []*WorkspaceIssueCriterionEvidence
	var object *WorkspaceIssueCriterionEvidence

	if singular {
		var ok bool
		object, ok = maybeWorkspaceIssueCriterionEvidence.(*WorkspaceIssueCriterionEvidence)
		if !ok {
			object = new(WorkspaceIssueCriterionEvidence)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceIssueCriterionEvidence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceIssueCriterionEvidence))
			}
		}
	} else {
		s, ok := maybeWorkspaceIssueCriterionEvidence.(*[]*WorkspaceIssueCriterionEvidence)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceIssueCriterionEvidence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceIssueCriterionEvidence))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceIssueCriterionEvidenceR{}
		}
		if !queries.IsNil(object.RecordedByAccountID) {
			args[object.RecordedByAccountID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceIssueCriterionEvidenceR{}
			}

			if !queries.IsNil(obj.RecordedByAccountID) {
				args[obj.RecordedByAccountID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`accounts`),
		qm.WhereIn(`accounts.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Account")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for accounts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for accounts")
	}

	if len(accountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.RecordedByAccount = foreign
		if foreign.R == nil {
			foreign.R = &accountR{}
		}
		foreign.R.RecordedByAccountWorkspaceIssueCriterionEvidences = append(foreign.R.RecordedByAccountWorkspaceIssueCriterionEvidences, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.RecordedByAccountID, foreign.ID) {
				local.R.RecordedByAccount = foreign
				if foreign.R == nil {
					foreign.R = &accountR{}
				}
				foreign.R.RecordedByAccountWorkspaceIssueCriterionEvidences = append(foreign.R.RecordedByAccountWorkspaceIssueCriterionEvidences, local)
				break
			}
		}
	}

	return nil
}

// SetAttachment of the workspaceIssueCriterionEvidence to the related item.
// Sets o.R.Attachment to related.
// Adds o to related.R.AttachmentWorkspaceIssueCriterionEvidences.
func (o *WorkspaceIssueCriterionEvidence) SetAttachment(ctx context.Context, exec boil.ContextExecutor, insert bool, related *WorkspaceIssueAttachment) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"workspace_issue_criterion_evidence\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"attachment_id"}),
		strmangle.WhereClause("\"", "\"", 2, workspaceIssueCriterionEvidencePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.AttachmentID, related.ID)
	if o.R == nil {
		o.R = &workspaceIssueCriterionEvidenceR{
			Attachment: related,
		}
	} else {
		o.R.Attachment = related
	}

	if related.R == nil {
		related.R = &workspaceIssueAttachmentR{
			AttachmentWorkspaceIssueCriterionEvidences: WorkspaceIssueCriterionEvidenceSlice{o},
		}
	} else {
		related.R.AttachmentWorkspaceIssueCriterionEvidences = append(related.R.AttachmentWorkspaceIssueCriterionEvidences, o)
	}

	return nil
}

// RemoveAttachment relationship.
// Sets o.R.Attachment to nil.
// Removes o from all passed in related items' relationships struct.
func (o *WorkspaceIssueCriterionEvidence) RemoveAttachment(ctx context.Context, exec boil.ContextExecutor, related *WorkspaceIssueAttachment) error {
	var err error

	queries.SetScanner(&o.AttachmentID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("attachment_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Attachment = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.AttachmentWorkspaceIssueCriterionEvidences {
		if queries.Equal(o.AttachmentID, ri.AttachmentID) {
			continue
		}

		ln := len(related.R.AttachmentWorkspaceIssueCriterionEvidences)
		if ln > 1 && i < ln-1 {
			related.R.AttachmentWorkspaceIssueCriterionEvidences[i] = related.R.AttachmentWorkspaceIssueCriterionEvidences[ln-1]
		}
		related.R.AttachmentWorkspaceIssueCriterionEvidences = related.R.AttachmentWorkspaceIssueCriterionEvidences[:ln-1]
		break
	}
	return nil
}

// SetDescriptionRevision of the workspaceIssueCriterionEvidence to the related item.
// Sets o.R.DescriptionRevision to related.
// Adds o to related.R.DescriptionRevisionWorkspaceIssueCriterionEvidences.
func (o *WorkspaceIssueCriterionEvidence) SetDescriptionRevision(ctx context.Context, exec boil.ContextExecutor, insert bool, related *WorkspaceIssueDescriptionRevision) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"workspace_issue_criterion_evidence\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"description_revision_id"}),
		strmangle.WhereClause("\"", "\"", 2, workspaceIssueCriterionEvidencePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.DescriptionRevisionID, related.ID)
	if o.R == nil {
		o.R = &workspaceIssueCriterionEvidenceR{
			DescriptionRevision: related,
		}
	} else {
		o.R.DescriptionRevision = related
	}

	if related.R == nil {
		related.R = &workspaceIssueDescriptionRevisionR{
			DescriptionRevisionWorkspaceIssueCriterionEvidences: WorkspaceIssueCriterionEvidenceSlice{o},
		}
	} else {
		related.R.DescriptionRevisionWorkspaceIssueCriterionEvidences = append(related.R.DescriptionRevisionWorkspaceIssueCriterionEvidences, o)
	}

	return nil
}

// RemoveDescriptionRevision relationship.
// Sets o.R.DescriptionRevision to nil.
// Removes o from all passed in related items' relationships struct.
func (o *WorkspaceIssueCriterionEvidence) RemoveDescriptionRevision(ctx context.Context, exec boil.ContextExecutor, related *WorkspaceIssueDescriptionRevision) error {
	var err error

	queries.SetScanner(&o.DescriptionRevisionID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("description_revision_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.DescriptionRevision = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.DescriptionRevisionWorkspaceIssueCriterionEvidences {
		if queries.Equal(o.DescriptionRevisionID, ri.DescriptionRevisionID) {
			continue
		}

		ln := len(related.R.DescriptionRevisionWorkspaceIssueCriterionEvidences)
		if ln > 1 && i < ln-1 {
			related.R.DescriptionRevisionWorkspaceIssueCriterionEvidences[i] = related.R.DescriptionRevisionWorkspaceIssueCriterionEvidences[ln-1]
		}
		related.R.DescriptionRevisionWorkspaceIssueCriterionEvidences = related.R.DescriptionRevisionWorkspaceIssueCriterionEvidences[:ln-1]
		break
	}
	return nil
}

// SetRecordedByAccount of the workspaceIssueCriterionEvidence to the related item.
// Sets o.R.RecordedByAccount to related.
// Adds o to related.R.RecordedByAccountWorkspaceIssueCriterionEvidences.
func (o *WorkspaceIssueCriterionEvidence) SetRecordedByAccount(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Account) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"workspace_issue_criterion_evidence\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"recorded_by_account_id"}),
		strmangle.WhereClause("\"", "\"", 2, workspaceIssueCriterionEvidencePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.RecordedByAccountID, related.ID)
	if o.R == nil {
		o.R = &workspaceIssueCriterionEvidenceR{
			RecordedByAccount: related,
		}
	} else {
		o.R.RecordedByAccount = related
	}

	if related.R == nil {
		related.R = &accountR{
			RecordedByAccountWorkspaceIssueCriterionEvidences: WorkspaceIssueCriterionEvidenceSlice{o},
		}
	} else {
		related.R.RecordedByAccountWorkspaceIssueCriterionEvidences = append(related.R.RecordedByAccountWorkspaceIssueCriterionEvidences, o)
	}

	return nil
}

// RemoveRecordedByAccount relationship.
// Sets o.R.RecordedByAccount to nil.
// Removes o from all passed in related items' relationships struct.
func (o *WorkspaceIssueCriterionEvidence) RemoveRecordedByAccount(ctx context.Context, exec boil.ContextExecutor, related *Account) error {
	var err error

	queries.SetScanner(&o.RecordedByAccountID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("recorded_by_account_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.RecordedByAccount = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.RecordedByAccountWorkspaceIssueCriterionEvidences {
		if queries.Equal(o.RecordedByAccountID, ri.RecordedByAccountID) {
			continue
		}

		ln := len(related.R.RecordedByAccountWorkspaceIssueCriterionEvidences)
		if ln > 1 && i < ln-1 {
			related.R.RecordedByAccountWorkspaceIssueCriterionEvidences[i] = related.R.RecordedByAccountWorkspaceIssueCriterionEvidences[ln-1]
		}
		related.R.RecordedByAccountWorkspaceIssueCriterionEvidences = related.R.RecordedByAccountWorkspaceIssueCriterionEvidences[:ln-1]
		break
	}
	return nil
}

// WorkspaceIssueCriterionEvidences retrieves all the records using an executor.
func WorkspaceIssueCriterionEvidences(mods ...qm.QueryMod) workspaceIssueCriterionEvidenceQuery {
	mods = append(mods, qm.From("\"workspace_issue_criterion_evidence\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"workspace_issue_criterion_evidence\".*"})
	}

	return workspaceIssueCriterionEvidenceQuery{q}
}

// FindWorkspaceIssueCriterionEvidence retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkspaceIssueCriterionEvidence(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WorkspaceIssueCriterionEvidence, error) {
	workspaceIssueCriterionEvidenceObj := &WorkspaceIssueCriterionEvidence{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"workspace_issue_criterion_evidence\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workspaceIssueCriterionEvidenceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from workspace_issue_criterion_evidence")
	}

	if err = workspaceIssueCriterionEvidenceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workspaceIssueCriterionEvidenceObj, err
	}

	return workspaceIssueCriterionEvidenceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkspaceIssueCriterionEvidence) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_issue_criterion_evidence provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceIssueCriterionEvidenceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workspaceIssueCriterionEvidenceInsertCacheMut.RLock()
	cache, cached := workspaceIssueCriterionEvidenceInsertCache[key]
	workspaceIssueCriterionEvidenceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workspaceIssueCriterionEvidenceAllColumns,
			workspaceIssueCriterionEvidenceColumnsWithDefault,
			workspaceIssueCriterionEvidenceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workspaceIssueCriterionEvidenceType, workspaceIssueCriterionEvidenceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workspaceIssueCriterionEvidenceType, workspaceIssueCriterionEvidenceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"workspace_issue_criterion_evidence\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"workspace_issue_criterion_evidence\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into workspace_issue_criterion_evidence")
	}

	if !cached {
		workspaceIssueCriterionEvidenceInsertCacheMut.Lock()
		workspaceIssueCriterionEvidenceInsertCache[key] = cache
		workspaceIssueCriterionEvidenceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkspaceIssueCriterionEvidence.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkspaceIssueCriterionEvidence) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workspaceIssueCriterionEvidenceUpdateCacheMut.RLock()
	cache, cached := workspaceIssueCriterionEvidenceUpdateCache[key]
	workspaceIssueCriterionEvidenceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workspaceIssueCriterionEvidenceAllColumns,
			workspaceIssueCriterionEvidencePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update workspace_issue_criterion_evidence, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"workspace_issue_criterion_evidence\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workspaceIssueCriterionEvidencePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workspaceIssueCriterionEvidenceType, workspaceIssueCriterionEvidenceMapping, append(wl, workspaceIssueCriterionEvidencePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update workspace_issue_criterion_evidence row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for workspace_issue_criterion_evidence")
	}

	if !cached {
		workspaceIssueCriterionEvidenceUpdateCacheMut.Lock()
		workspaceIssueCriterionEvidenceUpdateCache[key] = cache
		workspaceIssueCriterionEvidenceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workspaceIssueCriterionEvidenceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for workspace_issue_criterion_evidence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for workspace_issue_criterion_evidence")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkspaceIssueCriterionEvidenceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceIssueCriterionEvidencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"workspace_issue_criterion_evidence\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workspaceIssueCriterionEvidencePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in workspaceIssueCriterionEvidence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all workspaceIssueCriterionEvidence")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkspaceIssueCriterionEvidence) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_issue_criterion_evidence provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceIssueCriterionEvidenceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workspaceIssueCriterionEvidenceUpsertCacheMut.RLock()
	cache, cached := workspaceIssueCriterionEvidenceUpsertCache[key]
	workspaceIssueCriterionEvidenceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workspaceIssueCriterionEvidenceAllColumns,
			workspaceIssueCriterionEvidenceColumnsWithDefault,
			workspaceIssueCriterionEvidenceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workspaceIssueCriterionEvidenceAllColumns,
			workspaceIssueCriterionEvidencePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert workspace_issue_criterion_evidence, could not build update column list")
		}

		ret := strmangle.SetComplement(workspaceIssueCriterionEvidenceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(workspaceIssueCriterionEvidencePrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert workspace_issue_criterion_evidence, could not build conflict column list")
			}

			conflict = make([]string, len(workspaceIssueCriterionEvidencePrimaryKeyColumns))
			copy(conflict, workspaceIssueCriterionEvidencePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"workspace_issue_criterion_evidence\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(workspaceIssueCriterionEvidenceType, workspaceIssueCriterionEvidenceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workspaceIssueCriterionEvidenceType, workspaceIssueCriterionEvidenceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert workspace_issue_criterion_evidence")
	}

	if !cached {
		workspaceIssueCriterionEvidenceUpsertCacheMut.Lock()
		workspaceIssueCriterionEvidenceUpsertCache[key] = cache
		workspaceIssueCriterionEvidenceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkspaceIssueCriterionEvidence record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkspaceIssueCriterionEvidence) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no WorkspaceIssueCriterionEvidence provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workspaceIssueCriterionEvidencePrimaryKeyMapping)
	sql := "DELETE FROM \"workspace_issue_criterion_evidence\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from workspace_issue_criterion_evidence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for workspace_issue_criterion_evidence")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workspaceIssueCriterionEvidenceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no workspaceIssueCriterionEvidenceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspace_issue_criterion_evidence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_issue_criterion_evidence")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkspaceIssueCriterionEvidenceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workspaceIssueCriterionEvidenceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceIssueCriterionEvidencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"workspace_issue_criterion_evidence\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceIssueCriterionEvidencePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspaceIssueCriterionEvidence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_issue_criterion_evidence")
	}

	if len(workspaceIssueCriterionEvidenceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkspaceIssueCriterionEvidence) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkspaceIssueCriterionEvidence(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkspaceIssueCriterionEvidenceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkspaceIssueCriterionEvidenceSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceIssueCriterionEvidencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"workspace_issue_criterion_evidence\".* FROM \"workspace_issue_criterion_evidence\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceIssueCriterionEvidencePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in WorkspaceIssueCriterionEvidenceSlice")
	}

	*o = slice

	return nil
}

// WorkspaceIssueCriterionEvidenceExists checks if the WorkspaceIssueCriterionEvidence row exists.
func WorkspaceIssueCriterionEvidenceExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"workspace_issue_criterion_evidence\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if workspace_issue_criterion_evidence exists")
	}

	return exists, nil
}

// Exists checks if the WorkspaceIssueCriterionEvidence row exists.
func (o *WorkspaceIssueCriterionEvidence) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkspaceIssueCriterionEvidenceExists(ctx, exec, o.ID)
}
