// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WorkspaceExecutionPolicy is an object representing the database table.
type WorkspaceExecutionPolicy struct {
	WorkspaceID         string    `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	Telemetry           string    `boil:"telemetry" json:"telemetry" toml:"telemetry" yaml:"telemetry"`
	UploadRetentionDays int       `boil:"upload_retention_days" json:"upload_retention_days" toml:"upload_retention_days" yaml:"upload_retention_days"`
	CreatedAt           time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt           time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *workspaceExecutionPolicyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workspaceExecutionPolicyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkspaceExecutionPolicyColumns = struct {
	WorkspaceID         string
	Telemetry           string
	UploadRetentionDays string
	CreatedAt           string
	UpdatedAt           string
}{
	WorkspaceID:         "workspace_id",
	Telemetry:           "telemetry",
	UploadRetentionDays: "upload_retention_days",
	CreatedAt:           "created_at",
	UpdatedAt:           "updated_at",
}

var WorkspaceExecutionPolicyTableColumns = struct {
	WorkspaceID         string
	Telemetry           string
	UploadRetentionDays string
	CreatedAt           string
	UpdatedAt           string
}{
	WorkspaceID:         "workspace_execution_policies.workspace_id",
	Telemetry:           "workspace_execution_policies.telemetry",
	UploadRetentionDays: "workspace_execution_policies.upload_retention_days",
	CreatedAt:           "workspace_execution_policies.created_at",
	UpdatedAt:           "workspace_execution_policies.updated_at",
}

// Generated where

var WorkspaceExecutionPolicyWhere = struct {
	WorkspaceID         whereHelperstring
	Telemetry           whereHelperstring
	UploadRetentionDays whereHelperint
	CreatedAt           whereHelpertime_Time
	UpdatedAt           whereHelpertime_Time
}{
	WorkspaceID:         whereHelperstring{field: "\"workspace_execution_policies\".\"workspace_id\""},
	Telemetry:           whereHelperstring{field: "\"workspace_execution_policies\".\"telemetry\""},
	UploadRetentionDays: whereHelperint{field: "\"workspace_execution_policies\".\"upload_retention_days\""},
	CreatedAt:           whereHelpertime_Time{field: "\"workspace_execution_policies\".\"created_at\""},
	UpdatedAt:           whereHelpertime_Time{field: "\"workspace_execution_policies\".\"updated_at\""},
}

// WorkspaceExecutionPolicyRels is where relationship names are stored.
var WorkspaceExecutionPolicyRels = struct {
	Workspace string
}{
	Workspace: "Workspace",
}

// workspaceExecutionPolicyR is where relationships are stored.
type workspaceExecutionPolicyR struct {
	Workspace *Workspace `boil:"Workspace" json:"Workspace" toml:"Workspace" yaml:"Workspace"`
}

// NewStruct creates a new relationship struct
func (*workspaceExecutionPolicyR) NewStruct() *workspaceExecutionPolicyR {
	return &workspaceExecutionPolicyR{}
}

func (o *WorkspaceExecutionPolicy) GetWorkspace() *Workspace {
	if o == nil {
		return nil
	}

	return o.R.GetWorkspace()
}

func (r *workspaceExecutionPolicyR) GetWorkspace() *Workspace {
	if r == nil {
		return nil
	}

	return r.Workspace
}

// workspaceExecutionPolicyL is where Load methods for each relationship are stored.
type workspaceExecutionPolicyL struct{}

var (
	workspaceExecutionPolicyAllColumns            = []string{"workspace_id", "telemetry", "upload_retention_days", "created_at", "updated_at"}
	workspaceExecutionPolicyColumnsWithoutDefault = []string{"workspace_id", "upload_retention_days"}
	workspaceExecutionPolicyColumnsWithDefault    = []string{"telemetry", "created_at", "updated_at"}
	workspaceExecutionPolicyPrimaryKeyColumns     = []string{"workspace_id"}
	workspaceExecutionPolicyGeneratedColumns      = []string{}
)

type (
	// WorkspaceExecutionPolicySlice is an alias for a slice of pointers to WorkspaceExecutionPolicy.
	// This should almost always be used instead of []WorkspaceExecutionPolicy.
	WorkspaceExecutionPolicySlice []*WorkspaceExecutionPolicy
	// WorkspaceExecutionPolicyHook is the signature for custom WorkspaceExecutionPolicy hook methods
	WorkspaceExecutionPolicyHook func(context.Context, boil.ContextExecutor, *WorkspaceExecutionPolicy) error

	workspaceExecutionPolicyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workspaceExecutionPolicyType                 = reflect.TypeOf(&WorkspaceExecutionPolicy{})
	workspaceExecutionPolicyMapping              = queries.MakeStructMapping(workspaceExecutionPolicyType)
	workspaceExecutionPolicyPrimaryKeyMapping, _ = queries.BindMapping(workspaceExecutionPolicyType, workspaceExecutionPolicyMapping, workspaceExecutionPolicyPrimaryKeyColumns)
	workspaceExecutionPolicyInsertCacheMut       sync.RWMutex
	workspaceExecutionPolicyInsertCache          = make(map[string]insertCache)
	workspaceExecutionPolicyUpdateCacheMut       sync.RWMutex
	workspaceExecutionPolicyUpdateCache          = make(map[string]updateCache)
	workspaceExecutionPolicyUpsertCacheMut       sync.RWMutex
	workspaceExecutionPolicyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workspaceExecutionPolicyAfterSelectMu sync.Mutex
var workspaceExecutionPolicyAfterSelectHooks []WorkspaceExecutionPolicyHook

var workspaceExecutionPolicyBeforeInsertMu sync.Mutex
var workspaceExecutionPolicyBeforeInsertHooks []WorkspaceExecutionPolicyHook
var workspaceExecutionPolicyAfterInsertMu sync.Mutex
var workspaceExecutionPolicyAfterInsertHooks []WorkspaceExecutionPolicyHook

var workspaceExecutionPolicyBeforeUpdateMu sync.Mutex
var workspaceExecutionPolicyBeforeUpdateHooks []WorkspaceExecutionPolicyHook
var workspaceExecutionPolicyAfterUpdateMu sync.Mutex
var workspaceExecutionPolicyAfterUpdateHooks []WorkspaceExecutionPolicyHook

var workspaceExecutionPolicyBeforeDeleteMu sync.Mutex
var workspaceExecutionPolicyBeforeDeleteHooks []WorkspaceExecutionPolicyHook
var workspaceExecutionPolicyAfterDeleteMu sync.Mutex
var workspaceExecutionPolicyAfterDeleteHooks []WorkspaceExecutionPolicyHook

var workspaceExecutionPolicyBeforeUpsertMu sync.Mutex
var workspaceExecutionPolicyBeforeUpsertHooks []WorkspaceExecutionPolicyHook
var workspaceExecutionPolicyAfterUpsertMu sync.Mutex
var workspaceExecutionPolicyAfterUpsertHooks []WorkspaceExecutionPolicyHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkspaceExecutionPolicy) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceExecutionPolicyAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkspaceExecutionPolicy) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceExecutionPolicyBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkspaceExecutionPolicy) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceExecutionPolicyAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkspaceExecutionPolicy) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceExecutionPolicyBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkspaceExecutionPolicy) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceExecutionPolicyAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkspaceExecutionPolicy) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceExecutionPolicyBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkspaceExecutionPolicy) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceExecutionPolicyAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkspaceExecutionPolicy) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceExecutionPolicyBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkspaceExecutionPolicy) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceExecutionPolicyAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkspaceExecutionPolicyHook registers your hook function for all future operations.
func AddWorkspaceExecutionPolicyHook(hookPoint boil.HookPoint, workspaceExecutionPolicyHook WorkspaceExecutionPolicyHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workspaceExecutionPolicyAfterSelectMu.Lock()
		workspaceExecutionPolicyAfterSelectHooks = append(workspaceExecutionPolicyAfterSelectHooks, workspaceExecutionPolicyHook)
		workspaceExecutionPolicyAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workspaceExecutionPolicyBeforeInsertMu.Lock()
		workspaceExecutionPolicyBeforeInsertHooks = append(workspaceExecutionPolicyBeforeInsertHooks, workspaceExecutionPolicyHook)
		workspaceExecutionPolicyBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workspaceExecutionPolicyAfterInsertMu.Lock()
		workspaceExecutionPolicyAfterInsertHooks = append(workspaceExecutionPolicyAfterInsertHooks, workspaceExecutionPolicyHook)
		workspaceExecutionPolicyAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workspaceExecutionPolicyBeforeUpdateMu.Lock()
		workspaceExecutionPolicyBeforeUpdateHooks = append(workspaceExecutionPolicyBeforeUpdateHooks, workspaceExecutionPolicyHook)
		workspaceExecutionPolicyBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workspaceExecutionPolicyAfterUpdateMu.Lock()
		workspaceExecutionPolicyAfterUpdateHooks = append(workspaceExecutionPolicyAfterUpdateHooks, workspaceExecutionPolicyHook)
		workspaceExecutionPolicyAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workspaceExecutionPolicyBeforeDeleteMu.Lock()
		workspaceExecutionPolicyBeforeDeleteHooks = append(workspaceExecutionPolicyBeforeDeleteHooks, workspaceExecutionPolicyHook)
		workspaceExecutionPolicyBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workspaceExecutionPolicyAfterDeleteMu.Lock()
		workspaceExecutionPolicyAfterDeleteHooks = append(workspaceExecutionPolicyAfterDeleteHooks, workspaceExecutionPolicyHook)
		workspaceExecutionPolicyAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workspaceExecutionPolicyBeforeUpsertMu.Lock()
		workspaceExecutionPolicyBeforeUpsertHooks = append(workspaceExecutionPolicyBeforeUpsertHooks, workspaceExecutionPolicyHook)
		workspaceExecutionPolicyBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workspaceExecutionPolicyAfterUpsertMu.Lock()
		workspaceExecutionPolicyAfterUpsertHooks = append(workspaceExecutionPolicyAfterUpsertHooks, workspaceExecutionPolicyHook)
		workspaceExecutionPolicyAfterUpsertMu.Unlock()
	}
}

// One returns a single workspaceExecutionPolicy record from the query.
func (q workspaceExecutionPolicyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkspaceExecutionPolicy, error) {
	o := &WorkspaceExecutionPolicy{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for workspace_execution_policies")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkspaceExecutionPolicy records from the query.
func (q workspaceExecutionPolicyQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkspaceExecutionPolicySlice, error) {
	var o []*WorkspaceExecutionPolicy

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to WorkspaceExecutionPolicy slice")
	}

	if len(workspaceExecutionPolicyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkspaceExecutionPolicy records in the query.
func (q workspaceExecutionPolicyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count workspace_execution_policies rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workspaceExecutionPolicyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if workspace_execution_policies exists")
	}

	return count > 0, nil
}

// Workspace pointed to by the foreign key.
func (o *WorkspaceExecutionPolicy) Workspace(mods ...qm.QueryMod) workspaceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorkspaceID),
	}

	queryMods = append(queryMods, mods...)

	return Workspaces(queryMods...)
}

// LoadWorkspace allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workspaceExecutionPolicyL) LoadWorkspace(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceExecutionPolicy any, mods queries.Applicator) error {
	var slice []*WorkspaceExecutionPolicy
	var object *WorkspaceExecutionPolicy

	if singular {
		var ok bool
		object, ok = maybeWorkspaceExecutionPolicy.(*WorkspaceExecutionPolicy)
		if !ok {
			object = new(WorkspaceExecutionPolicy)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceExecutionPolicy)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceExecutionPolicy))
			}
		}
	} else {
		s, ok := maybeWorkspaceExecutionPolicy.(*[]*WorkspaceExecutionPolicy)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceExecutionPolicy)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceExecutionPolicy))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceExecutionPolicyR{}
		}
		args[object.WorkspaceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceExecutionPolicyR{}
			}

			args[obj.WorkspaceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspaces`),
		qm.WhereIn(`workspaces.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Workspace")
	}

	var resultSlice []*Workspace
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Workspace")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workspaces")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspaces")
	}

	if len(workspaceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Workspace = foreign
		if foreign.R == nil {
			foreign.R = &workspaceR{}
		}
		foreign.R.WorkspaceExecutionPolicy = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkspaceID == foreign.ID {
				local.R.Workspace = foreign
				if foreign.R == nil {
					foreign.R = &workspaceR{}
				}
				foreign.R.WorkspaceExecutionPolicy = local
				break
			}
		}
	}

	return nil
}

// SetWorkspace of the workspaceExecutionPolicy to the related item.
// Sets o.R.Workspace to related.
// Adds o to related.R.WorkspaceExecutionPolicy.
func (o *WorkspaceExecutionPolicy) SetWorkspace(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Workspace) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"workspace_execution_policies\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"workspace_id"}),
		strmangle.WhereClause("\"", "\"", 2, workspaceExecutionPolicyPrimaryKeyColumns),
	)
	values := []any{related.ID, o.WorkspaceID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkspaceID = related.ID
	if o.R == nil {
		o.R = &workspaceExecutionPolicyR{
			Workspace: related,
		}
	} else {
		o.R.Workspace = related
	}

	if related.R == nil {
		related.R = &workspaceR{
			WorkspaceExecutionPolicy: o,
		}
	} else {
		related.R.WorkspaceExecutionPolicy = o
	}

	return nil
}

// WorkspaceExecutionPolicies retrieves all the records using an executor.
func WorkspaceExecutionPolicies(mods ...qm.QueryMod) workspaceExecutionPolicyQuery {
	mods = append(mods, qm.From("\"workspace_execution_policies\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"workspace_execution_policies\".*"})
	}

	return workspaceExecutionPolicyQuery{q}
}

// FindWorkspaceExecutionPolicy retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkspaceExecutionPolicy(ctx context.Context, exec boil.ContextExecutor, workspaceID string, selectCols ...string) (*WorkspaceExecutionPolicy, error) {
	workspaceExecutionPolicyObj := &WorkspaceExecutionPolicy{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"workspace_execution_policies\" where \"workspace_id\"=$1", sel,
	)

	q := queries.Raw(query, workspaceID)

	err := q.Bind(ctx, exec, workspaceExecutionPolicyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from workspace_execution_policies")
	}

	if err = workspaceExecutionPolicyObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workspaceExecutionPolicyObj, err
	}

	return workspaceExecutionPolicyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkspaceExecutionPolicy) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_execution_policies provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceExecutionPolicyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workspaceExecutionPolicyInsertCacheMut.RLock()
	cache, cached := workspaceExecutionPolicyInsertCache[key]
	workspaceExecutionPolicyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workspaceExecutionPolicyAllColumns,
			workspaceExecutionPolicyColumnsWithDefault,
			workspaceExecutionPolicyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workspaceExecutionPolicyType, workspaceExecutionPolicyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workspaceExecutionPolicyType, workspaceExecutionPolicyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"workspace_execution_policies\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"workspace_execution_policies\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into workspace_execution_policies")
	}

	if !cached {
		workspaceExecutionPolicyInsertCacheMut.Lock()
		workspaceExecutionPolicyInsertCache[key] = cache
		workspaceExecutionPolicyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkspaceExecutionPolicy.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkspaceExecutionPolicy) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workspaceExecutionPolicyUpdateCacheMut.RLock()
	cache, cached := workspaceExecutionPolicyUpdateCache[key]
	workspaceExecutionPolicyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workspaceExecutionPolicyAllColumns,
			workspaceExecutionPolicyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update workspace_execution_policies, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"workspace_execution_policies\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workspaceExecutionPolicyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workspaceExecutionPolicyType, workspaceExecutionPolicyMapping, append(wl, workspaceExecutionPolicyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update workspace_execution_policies row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for workspace_execution_policies")
	}

	if !cached {
		workspaceExecutionPolicyUpdateCacheMut.Lock()
		workspaceExecutionPolicyUpdateCache[key] = cache
		workspaceExecutionPolicyUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workspaceExecutionPolicyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for workspace_execution_policies")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for workspace_execution_policies")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkspaceExecutionPolicySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceExecutionPolicyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"workspace_execution_policies\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workspaceExecutionPolicyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in workspaceExecutionPolicy slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all workspaceExecutionPolicy")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkspaceExecutionPolicy) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_execution_policies provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceExecutionPolicyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workspaceExecutionPolicyUpsertCacheMut.RLock()
	cache, cached := workspaceExecutionPolicyUpsertCache[key]
	workspaceExecutionPolicyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workspaceExecutionPolicyAllColumns,
			workspaceExecutionPolicyColumnsWithDefault,
			workspaceExecutionPolicyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workspaceExecutionPolicyAllColumns,
			workspaceExecutionPolicyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert workspace_execution_policies, could not build update column list")
		}

		ret := strmangle.SetComplement(workspaceExecutionPolicyAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(workspaceExecutionPolicyPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert workspace_execution_policies, could not build conflict column list")
			}

			conflict = make([]string, len(workspaceExecutionPolicyPrimaryKeyColumns))
			copy(conflict, workspaceExecutionPolicyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"workspace_execution_policies\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(workspaceExecutionPolicyType, workspaceExecutionPolicyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workspaceExecutionPolicyType, workspaceExecutionPolicyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert workspace_execution_policies")
	}

	if !cached {
		workspaceExecutionPolicyUpsertCacheMut.Lock()
		workspaceExecutionPolicyUpsertCache[key] = cache
		workspaceExecutionPolicyUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkspaceExecutionPolicy record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkspaceExecutionPolicy) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no WorkspaceExecutionPolicy provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workspaceExecutionPolicyPrimaryKeyMapping)
	sql := "DELETE FROM \"workspace_execution_policies\" WHERE \"workspace_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from workspace_execution_policies")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for workspace_execution_policies")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workspaceExecutionPolicyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no workspaceExecutionPolicyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspace_execution_policies")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_execution_policies")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkspaceExecutionPolicySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workspaceExecutionPolicyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceExecutionPolicyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"workspace_execution_policies\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceExecutionPolicyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspaceExecutionPolicy slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_execution_policies")
	}

	if len(workspaceExecutionPolicyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkspaceExecutionPolicy) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkspaceExecutionPolicy(ctx, exec, o.WorkspaceID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkspaceExecutionPolicySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkspaceExecutionPolicySlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceExecutionPolicyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"workspace_execution_policies\".* FROM \"workspace_execution_policies\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceExecutionPolicyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in WorkspaceExecutionPolicySlice")
	}

	*o = slice

	return nil
}

// WorkspaceExecutionPolicyExists checks if the WorkspaceExecutionPolicy row exists.
func WorkspaceExecutionPolicyExists(ctx context.Context, exec boil.ContextExecutor, workspaceID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"workspace_execution_policies\" where \"workspace_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, workspaceID)
	}
	row := exec.QueryRowContext(ctx, sql, workspaceID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if workspace_execution_policies exists")
	}

	return exists, nil
}

// Exists checks if the WorkspaceExecutionPolicy row exists.
func (o *WorkspaceExecutionPolicy) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkspaceExecutionPolicyExists(ctx, exec, o.WorkspaceID)
}
