// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WorkspaceSavedViewPlacement is an object representing the database table.
type WorkspaceSavedViewPlacement struct {
	WorkspaceID string    `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	AccountID   string    `boil:"account_id" json:"account_id" toml:"account_id" yaml:"account_id"`
	SavedViewID string    `boil:"saved_view_id" json:"saved_view_id" toml:"saved_view_id" yaml:"saved_view_id"`
	Position    int       `boil:"position" json:"position" toml:"position" yaml:"position"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *workspaceSavedViewPlacementR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workspaceSavedViewPlacementL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkspaceSavedViewPlacementColumns = struct {
	WorkspaceID string
	AccountID   string
	SavedViewID string
	Position    string
	CreatedAt   string
	UpdatedAt   string
}{
	WorkspaceID: "workspace_id",
	AccountID:   "account_id",
	SavedViewID: "saved_view_id",
	Position:    "position",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

var WorkspaceSavedViewPlacementTableColumns = struct {
	WorkspaceID string
	AccountID   string
	SavedViewID string
	Position    string
	CreatedAt   string
	UpdatedAt   string
}{
	WorkspaceID: "workspace_saved_view_placements.workspace_id",
	AccountID:   "workspace_saved_view_placements.account_id",
	SavedViewID: "workspace_saved_view_placements.saved_view_id",
	Position:    "workspace_saved_view_placements.position",
	CreatedAt:   "workspace_saved_view_placements.created_at",
	UpdatedAt:   "workspace_saved_view_placements.updated_at",
}

// Generated where

var WorkspaceSavedViewPlacementWhere = struct {
	WorkspaceID whereHelperstring
	AccountID   whereHelperstring
	SavedViewID whereHelperstring
	Position    whereHelperint
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
}{
	WorkspaceID: whereHelperstring{field: "\"workspace_saved_view_placements\".\"workspace_id\""},
	AccountID:   whereHelperstring{field: "\"workspace_saved_view_placements\".\"account_id\""},
	SavedViewID: whereHelperstring{field: "\"workspace_saved_view_placements\".\"saved_view_id\""},
	Position:    whereHelperint{field: "\"workspace_saved_view_placements\".\"position\""},
	CreatedAt:   whereHelpertime_Time{field: "\"workspace_saved_view_placements\".\"created_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"workspace_saved_view_placements\".\"updated_at\""},
}

// WorkspaceSavedViewPlacementRels is where relationship names are stored.
var WorkspaceSavedViewPlacementRels = struct {
}{}

// workspaceSavedViewPlacementR is where relationships are stored.
type workspaceSavedViewPlacementR struct {
}

// NewStruct creates a new relationship struct
func (*workspaceSavedViewPlacementR) NewStruct() *workspaceSavedViewPlacementR {
	return &workspaceSavedViewPlacementR{}
}

// workspaceSavedViewPlacementL is where Load methods for each relationship are stored.
type workspaceSavedViewPlacementL struct{}

var (
	workspaceSavedViewPlacementAllColumns            = []string{"workspace_id", "account_id", "saved_view_id", "position", "created_at", "updated_at"}
	workspaceSavedViewPlacementColumnsWithoutDefault = []string{"workspace_id", "account_id", "saved_view_id", "position"}
	workspaceSavedViewPlacementColumnsWithDefault    = []string{"created_at", "updated_at"}
	workspaceSavedViewPlacementPrimaryKeyColumns     = []string{"account_id", "saved_view_id"}
	workspaceSavedViewPlacementGeneratedColumns      = []string{}
)

type (
	// WorkspaceSavedViewPlacementSlice is an alias for a slice of pointers to WorkspaceSavedViewPlacement.
	// This should almost always be used instead of []WorkspaceSavedViewPlacement.
	WorkspaceSavedViewPlacementSlice []*WorkspaceSavedViewPlacement
	// WorkspaceSavedViewPlacementHook is the signature for custom WorkspaceSavedViewPlacement hook methods
	WorkspaceSavedViewPlacementHook func(context.Context, boil.ContextExecutor, *WorkspaceSavedViewPlacement) error

	workspaceSavedViewPlacementQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workspaceSavedViewPlacementType                 = reflect.TypeOf(&WorkspaceSavedViewPlacement{})
	workspaceSavedViewPlacementMapping              = queries.MakeStructMapping(workspaceSavedViewPlacementType)
	workspaceSavedViewPlacementPrimaryKeyMapping, _ = queries.BindMapping(workspaceSavedViewPlacementType, workspaceSavedViewPlacementMapping, workspaceSavedViewPlacementPrimaryKeyColumns)
	workspaceSavedViewPlacementInsertCacheMut       sync.RWMutex
	workspaceSavedViewPlacementInsertCache          = make(map[string]insertCache)
	workspaceSavedViewPlacementUpdateCacheMut       sync.RWMutex
	workspaceSavedViewPlacementUpdateCache          = make(map[string]updateCache)
	workspaceSavedViewPlacementUpsertCacheMut       sync.RWMutex
	workspaceSavedViewPlacementUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workspaceSavedViewPlacementAfterSelectMu sync.Mutex
var workspaceSavedViewPlacementAfterSelectHooks []WorkspaceSavedViewPlacementHook

var workspaceSavedViewPlacementBeforeInsertMu sync.Mutex
var workspaceSavedViewPlacementBeforeInsertHooks []WorkspaceSavedViewPlacementHook
var workspaceSavedViewPlacementAfterInsertMu sync.Mutex
var workspaceSavedViewPlacementAfterInsertHooks []WorkspaceSavedViewPlacementHook

var workspaceSavedViewPlacementBeforeUpdateMu sync.Mutex
var workspaceSavedViewPlacementBeforeUpdateHooks []WorkspaceSavedViewPlacementHook
var workspaceSavedViewPlacementAfterUpdateMu sync.Mutex
var workspaceSavedViewPlacementAfterUpdateHooks []WorkspaceSavedViewPlacementHook

var workspaceSavedViewPlacementBeforeDeleteMu sync.Mutex
var workspaceSavedViewPlacementBeforeDeleteHooks []WorkspaceSavedViewPlacementHook
var workspaceSavedViewPlacementAfterDeleteMu sync.Mutex
var workspaceSavedViewPlacementAfterDeleteHooks []WorkspaceSavedViewPlacementHook

var workspaceSavedViewPlacementBeforeUpsertMu sync.Mutex
var workspaceSavedViewPlacementBeforeUpsertHooks []WorkspaceSavedViewPlacementHook
var workspaceSavedViewPlacementAfterUpsertMu sync.Mutex
var workspaceSavedViewPlacementAfterUpsertHooks []WorkspaceSavedViewPlacementHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkspaceSavedViewPlacement) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceSavedViewPlacementAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkspaceSavedViewPlacement) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceSavedViewPlacementBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkspaceSavedViewPlacement) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceSavedViewPlacementAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkspaceSavedViewPlacement) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceSavedViewPlacementBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkspaceSavedViewPlacement) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceSavedViewPlacementAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkspaceSavedViewPlacement) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceSavedViewPlacementBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkspaceSavedViewPlacement) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceSavedViewPlacementAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkspaceSavedViewPlacement) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceSavedViewPlacementBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkspaceSavedViewPlacement) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceSavedViewPlacementAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkspaceSavedViewPlacementHook registers your hook function for all future operations.
func AddWorkspaceSavedViewPlacementHook(hookPoint boil.HookPoint, workspaceSavedViewPlacementHook WorkspaceSavedViewPlacementHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workspaceSavedViewPlacementAfterSelectMu.Lock()
		workspaceSavedViewPlacementAfterSelectHooks = append(workspaceSavedViewPlacementAfterSelectHooks, workspaceSavedViewPlacementHook)
		workspaceSavedViewPlacementAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workspaceSavedViewPlacementBeforeInsertMu.Lock()
		workspaceSavedViewPlacementBeforeInsertHooks = append(workspaceSavedViewPlacementBeforeInsertHooks, workspaceSavedViewPlacementHook)
		workspaceSavedViewPlacementBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workspaceSavedViewPlacementAfterInsertMu.Lock()
		workspaceSavedViewPlacementAfterInsertHooks = append(workspaceSavedViewPlacementAfterInsertHooks, workspaceSavedViewPlacementHook)
		workspaceSavedViewPlacementAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workspaceSavedViewPlacementBeforeUpdateMu.Lock()
		workspaceSavedViewPlacementBeforeUpdateHooks = append(workspaceSavedViewPlacementBeforeUpdateHooks, workspaceSavedViewPlacementHook)
		workspaceSavedViewPlacementBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workspaceSavedViewPlacementAfterUpdateMu.Lock()
		workspaceSavedViewPlacementAfterUpdateHooks = append(workspaceSavedViewPlacementAfterUpdateHooks, workspaceSavedViewPlacementHook)
		workspaceSavedViewPlacementAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workspaceSavedViewPlacementBeforeDeleteMu.Lock()
		workspaceSavedViewPlacementBeforeDeleteHooks = append(workspaceSavedViewPlacementBeforeDeleteHooks, workspaceSavedViewPlacementHook)
		workspaceSavedViewPlacementBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workspaceSavedViewPlacementAfterDeleteMu.Lock()
		workspaceSavedViewPlacementAfterDeleteHooks = append(workspaceSavedViewPlacementAfterDeleteHooks, workspaceSavedViewPlacementHook)
		workspaceSavedViewPlacementAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workspaceSavedViewPlacementBeforeUpsertMu.Lock()
		workspaceSavedViewPlacementBeforeUpsertHooks = append(workspaceSavedViewPlacementBeforeUpsertHooks, workspaceSavedViewPlacementHook)
		workspaceSavedViewPlacementBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workspaceSavedViewPlacementAfterUpsertMu.Lock()
		workspaceSavedViewPlacementAfterUpsertHooks = append(workspaceSavedViewPlacementAfterUpsertHooks, workspaceSavedViewPlacementHook)
		workspaceSavedViewPlacementAfterUpsertMu.Unlock()
	}
}

// One returns a single workspaceSavedViewPlacement record from the query.
func (q workspaceSavedViewPlacementQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkspaceSavedViewPlacement, error) {
	o := &WorkspaceSavedViewPlacement{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for workspace_saved_view_placements")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkspaceSavedViewPlacement records from the query.
func (q workspaceSavedViewPlacementQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkspaceSavedViewPlacementSlice, error) {
	var o []*WorkspaceSavedViewPlacement

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to WorkspaceSavedViewPlacement slice")
	}

	if len(workspaceSavedViewPlacementAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkspaceSavedViewPlacement records in the query.
func (q workspaceSavedViewPlacementQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count workspace_saved_view_placements rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workspaceSavedViewPlacementQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if workspace_saved_view_placements exists")
	}

	return count > 0, nil
}

// WorkspaceSavedViewPlacements retrieves all the records using an executor.
func WorkspaceSavedViewPlacements(mods ...qm.QueryMod) workspaceSavedViewPlacementQuery {
	mods = append(mods, qm.From("\"workspace_saved_view_placements\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"workspace_saved_view_placements\".*"})
	}

	return workspaceSavedViewPlacementQuery{q}
}

// FindWorkspaceSavedViewPlacement retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkspaceSavedViewPlacement(ctx context.Context, exec boil.ContextExecutor, accountID string, savedViewID string, selectCols ...string) (*WorkspaceSavedViewPlacement, error) {
	workspaceSavedViewPlacementObj := &WorkspaceSavedViewPlacement{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"workspace_saved_view_placements\" where \"account_id\"=$1 AND \"saved_view_id\"=$2", sel,
	)

	q := queries.Raw(query, accountID, savedViewID)

	err := q.Bind(ctx, exec, workspaceSavedViewPlacementObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from workspace_saved_view_placements")
	}

	if err = workspaceSavedViewPlacementObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workspaceSavedViewPlacementObj, err
	}

	return workspaceSavedViewPlacementObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkspaceSavedViewPlacement) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_saved_view_placements provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceSavedViewPlacementColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workspaceSavedViewPlacementInsertCacheMut.RLock()
	cache, cached := workspaceSavedViewPlacementInsertCache[key]
	workspaceSavedViewPlacementInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workspaceSavedViewPlacementAllColumns,
			workspaceSavedViewPlacementColumnsWithDefault,
			workspaceSavedViewPlacementColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workspaceSavedViewPlacementType, workspaceSavedViewPlacementMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workspaceSavedViewPlacementType, workspaceSavedViewPlacementMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"workspace_saved_view_placements\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"workspace_saved_view_placements\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into workspace_saved_view_placements")
	}

	if !cached {
		workspaceSavedViewPlacementInsertCacheMut.Lock()
		workspaceSavedViewPlacementInsertCache[key] = cache
		workspaceSavedViewPlacementInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkspaceSavedViewPlacement.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkspaceSavedViewPlacement) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workspaceSavedViewPlacementUpdateCacheMut.RLock()
	cache, cached := workspaceSavedViewPlacementUpdateCache[key]
	workspaceSavedViewPlacementUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workspaceSavedViewPlacementAllColumns,
			workspaceSavedViewPlacementPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update workspace_saved_view_placements, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"workspace_saved_view_placements\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workspaceSavedViewPlacementPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workspaceSavedViewPlacementType, workspaceSavedViewPlacementMapping, append(wl, workspaceSavedViewPlacementPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update workspace_saved_view_placements row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for workspace_saved_view_placements")
	}

	if !cached {
		workspaceSavedViewPlacementUpdateCacheMut.Lock()
		workspaceSavedViewPlacementUpdateCache[key] = cache
		workspaceSavedViewPlacementUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workspaceSavedViewPlacementQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for workspace_saved_view_placements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for workspace_saved_view_placements")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkspaceSavedViewPlacementSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceSavedViewPlacementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"workspace_saved_view_placements\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workspaceSavedViewPlacementPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in workspaceSavedViewPlacement slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all workspaceSavedViewPlacement")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkspaceSavedViewPlacement) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_saved_view_placements provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceSavedViewPlacementColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workspaceSavedViewPlacementUpsertCacheMut.RLock()
	cache, cached := workspaceSavedViewPlacementUpsertCache[key]
	workspaceSavedViewPlacementUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workspaceSavedViewPlacementAllColumns,
			workspaceSavedViewPlacementColumnsWithDefault,
			workspaceSavedViewPlacementColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workspaceSavedViewPlacementAllColumns,
			workspaceSavedViewPlacementPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert workspace_saved_view_placements, could not build update column list")
		}

		ret := strmangle.SetComplement(workspaceSavedViewPlacementAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(workspaceSavedViewPlacementPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert workspace_saved_view_placements, could not build conflict column list")
			}

			conflict = make([]string, len(workspaceSavedViewPlacementPrimaryKeyColumns))
			copy(conflict, workspaceSavedViewPlacementPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"workspace_saved_view_placements\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(workspaceSavedViewPlacementType, workspaceSavedViewPlacementMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workspaceSavedViewPlacementType, workspaceSavedViewPlacementMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert workspace_saved_view_placements")
	}

	if !cached {
		workspaceSavedViewPlacementUpsertCacheMut.Lock()
		workspaceSavedViewPlacementUpsertCache[key] = cache
		workspaceSavedViewPlacementUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkspaceSavedViewPlacement record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkspaceSavedViewPlacement) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no WorkspaceSavedViewPlacement provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workspaceSavedViewPlacementPrimaryKeyMapping)
	sql := "DELETE FROM \"workspace_saved_view_placements\" WHERE \"account_id\"=$1 AND \"saved_view_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from workspace_saved_view_placements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for workspace_saved_view_placements")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workspaceSavedViewPlacementQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no workspaceSavedViewPlacementQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspace_saved_view_placements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_saved_view_placements")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkspaceSavedViewPlacementSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workspaceSavedViewPlacementBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceSavedViewPlacementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"workspace_saved_view_placements\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceSavedViewPlacementPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspaceSavedViewPlacement slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_saved_view_placements")
	}

	if len(workspaceSavedViewPlacementAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkspaceSavedViewPlacement) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkspaceSavedViewPlacement(ctx, exec, o.AccountID, o.SavedViewID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkspaceSavedViewPlacementSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkspaceSavedViewPlacementSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceSavedViewPlacementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"workspace_saved_view_placements\".* FROM \"workspace_saved_view_placements\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceSavedViewPlacementPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in WorkspaceSavedViewPlacementSlice")
	}

	*o = slice

	return nil
}

// WorkspaceSavedViewPlacementExists checks if the WorkspaceSavedViewPlacement row exists.
func WorkspaceSavedViewPlacementExists(ctx context.Context, exec boil.ContextExecutor, accountID string, savedViewID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"workspace_saved_view_placements\" where \"account_id\"=$1 AND \"saved_view_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, accountID, savedViewID)
	}
	row := exec.QueryRowContext(ctx, sql, accountID, savedViewID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if workspace_saved_view_placements exists")
	}

	return exists, nil
}

// Exists checks if the WorkspaceSavedViewPlacement row exists.
func (o *WorkspaceSavedViewPlacement) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkspaceSavedViewPlacementExists(ctx, exec, o.AccountID, o.SavedViewID)
}
