// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WorkspaceNotificationSetting is an object representing the database table.
type WorkspaceNotificationSetting struct {
	WorkspaceID       string    `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	AccountID         string    `boil:"account_id" json:"account_id" toml:"account_id" yaml:"account_id"`
	InboxAssigned     bool      `boil:"inbox_assigned" json:"inbox_assigned" toml:"inbox_assigned" yaml:"inbox_assigned"`
	InboxMentioned    bool      `boil:"inbox_mentioned" json:"inbox_mentioned" toml:"inbox_mentioned" yaml:"inbox_mentioned"`
	InboxCommented    bool      `boil:"inbox_commented" json:"inbox_commented" toml:"inbox_commented" yaml:"inbox_commented"`
	InboxStateChanged bool      `boil:"inbox_state_changed" json:"inbox_state_changed" toml:"inbox_state_changed" yaml:"inbox_state_changed"`
	InboxMembership   bool      `boil:"inbox_membership" json:"inbox_membership" toml:"inbox_membership" yaml:"inbox_membership"`
	InboxAgents       bool      `boil:"inbox_agents" json:"inbox_agents" toml:"inbox_agents" yaml:"inbox_agents"`
	EmailAssigned     bool      `boil:"email_assigned" json:"email_assigned" toml:"email_assigned" yaml:"email_assigned"`
	EmailMentioned    bool      `boil:"email_mentioned" json:"email_mentioned" toml:"email_mentioned" yaml:"email_mentioned"`
	EmailCommented    bool      `boil:"email_commented" json:"email_commented" toml:"email_commented" yaml:"email_commented"`
	EmailStateChanged bool      `boil:"email_state_changed" json:"email_state_changed" toml:"email_state_changed" yaml:"email_state_changed"`
	EmailMembership   bool      `boil:"email_membership" json:"email_membership" toml:"email_membership" yaml:"email_membership"`
	EmailAgents       bool      `boil:"email_agents" json:"email_agents" toml:"email_agents" yaml:"email_agents"`
	CreatedAt         time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt         time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	InboxChecks       bool      `boil:"inbox_checks" json:"inbox_checks" toml:"inbox_checks" yaml:"inbox_checks"`
	EmailChecks       bool      `boil:"email_checks" json:"email_checks" toml:"email_checks" yaml:"email_checks"`

	R *workspaceNotificationSettingR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workspaceNotificationSettingL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkspaceNotificationSettingColumns = struct {
	WorkspaceID       string
	AccountID         string
	InboxAssigned     string
	InboxMentioned    string
	InboxCommented    string
	InboxStateChanged string
	InboxMembership   string
	InboxAgents       string
	EmailAssigned     string
	EmailMentioned    string
	EmailCommented    string
	EmailStateChanged string
	EmailMembership   string
	EmailAgents       string
	CreatedAt         string
	UpdatedAt         string
	InboxChecks       string
	EmailChecks       string
}{
	WorkspaceID:       "workspace_id",
	AccountID:         "account_id",
	InboxAssigned:     "inbox_assigned",
	InboxMentioned:    "inbox_mentioned",
	InboxCommented:    "inbox_commented",
	InboxStateChanged: "inbox_state_changed",
	InboxMembership:   "inbox_membership",
	InboxAgents:       "inbox_agents",
	EmailAssigned:     "email_assigned",
	EmailMentioned:    "email_mentioned",
	EmailCommented:    "email_commented",
	EmailStateChanged: "email_state_changed",
	EmailMembership:   "email_membership",
	EmailAgents:       "email_agents",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
	InboxChecks:       "inbox_checks",
	EmailChecks:       "email_checks",
}

var WorkspaceNotificationSettingTableColumns = struct {
	WorkspaceID       string
	AccountID         string
	InboxAssigned     string
	InboxMentioned    string
	InboxCommented    string
	InboxStateChanged string
	InboxMembership   string
	InboxAgents       string
	EmailAssigned     string
	EmailMentioned    string
	EmailCommented    string
	EmailStateChanged string
	EmailMembership   string
	EmailAgents       string
	CreatedAt         string
	UpdatedAt         string
	InboxChecks       string
	EmailChecks       string
}{
	WorkspaceID:       "workspace_notification_settings.workspace_id",
	AccountID:         "workspace_notification_settings.account_id",
	InboxAssigned:     "workspace_notification_settings.inbox_assigned",
	InboxMentioned:    "workspace_notification_settings.inbox_mentioned",
	InboxCommented:    "workspace_notification_settings.inbox_commented",
	InboxStateChanged: "workspace_notification_settings.inbox_state_changed",
	InboxMembership:   "workspace_notification_settings.inbox_membership",
	InboxAgents:       "workspace_notification_settings.inbox_agents",
	EmailAssigned:     "workspace_notification_settings.email_assigned",
	EmailMentioned:    "workspace_notification_settings.email_mentioned",
	EmailCommented:    "workspace_notification_settings.email_commented",
	EmailStateChanged: "workspace_notification_settings.email_state_changed",
	EmailMembership:   "workspace_notification_settings.email_membership",
	EmailAgents:       "workspace_notification_settings.email_agents",
	CreatedAt:         "workspace_notification_settings.created_at",
	UpdatedAt:         "workspace_notification_settings.updated_at",
	InboxChecks:       "workspace_notification_settings.inbox_checks",
	EmailChecks:       "workspace_notification_settings.email_checks",
}

// Generated where

var WorkspaceNotificationSettingWhere = struct {
	WorkspaceID       whereHelperstring
	AccountID         whereHelperstring
	InboxAssigned     whereHelperbool
	InboxMentioned    whereHelperbool
	InboxCommented    whereHelperbool
	InboxStateChanged whereHelperbool
	InboxMembership   whereHelperbool
	InboxAgents       whereHelperbool
	EmailAssigned     whereHelperbool
	EmailMentioned    whereHelperbool
	EmailCommented    whereHelperbool
	EmailStateChanged whereHelperbool
	EmailMembership   whereHelperbool
	EmailAgents       whereHelperbool
	CreatedAt         whereHelpertime_Time
	UpdatedAt         whereHelpertime_Time
	InboxChecks       whereHelperbool
	EmailChecks       whereHelperbool
}{
	WorkspaceID:       whereHelperstring{field: "\"workspace_notification_settings\".\"workspace_id\""},
	AccountID:         whereHelperstring{field: "\"workspace_notification_settings\".\"account_id\""},
	InboxAssigned:     whereHelperbool{field: "\"workspace_notification_settings\".\"inbox_assigned\""},
	InboxMentioned:    whereHelperbool{field: "\"workspace_notification_settings\".\"inbox_mentioned\""},
	InboxCommented:    whereHelperbool{field: "\"workspace_notification_settings\".\"inbox_commented\""},
	InboxStateChanged: whereHelperbool{field: "\"workspace_notification_settings\".\"inbox_state_changed\""},
	InboxMembership:   whereHelperbool{field: "\"workspace_notification_settings\".\"inbox_membership\""},
	InboxAgents:       whereHelperbool{field: "\"workspace_notification_settings\".\"inbox_agents\""},
	EmailAssigned:     whereHelperbool{field: "\"workspace_notification_settings\".\"email_assigned\""},
	EmailMentioned:    whereHelperbool{field: "\"workspace_notification_settings\".\"email_mentioned\""},
	EmailCommented:    whereHelperbool{field: "\"workspace_notification_settings\".\"email_commented\""},
	EmailStateChanged: whereHelperbool{field: "\"workspace_notification_settings\".\"email_state_changed\""},
	EmailMembership:   whereHelperbool{field: "\"workspace_notification_settings\".\"email_membership\""},
	EmailAgents:       whereHelperbool{field: "\"workspace_notification_settings\".\"email_agents\""},
	CreatedAt:         whereHelpertime_Time{field: "\"workspace_notification_settings\".\"created_at\""},
	UpdatedAt:         whereHelpertime_Time{field: "\"workspace_notification_settings\".\"updated_at\""},
	InboxChecks:       whereHelperbool{field: "\"workspace_notification_settings\".\"inbox_checks\""},
	EmailChecks:       whereHelperbool{field: "\"workspace_notification_settings\".\"email_checks\""},
}

// WorkspaceNotificationSettingRels is where relationship names are stored.
var WorkspaceNotificationSettingRels = struct {
}{}

// workspaceNotificationSettingR is where relationships are stored.
type workspaceNotificationSettingR struct {
}

// NewStruct creates a new relationship struct
func (*workspaceNotificationSettingR) NewStruct() *workspaceNotificationSettingR {
	return &workspaceNotificationSettingR{}
}

// workspaceNotificationSettingL is where Load methods for each relationship are stored.
type workspaceNotificationSettingL struct{}

var (
	workspaceNotificationSettingAllColumns            = []string{"workspace_id", "account_id", "inbox_assigned", "inbox_mentioned", "inbox_commented", "inbox_state_changed", "inbox_membership", "inbox_agents", "email_assigned", "email_mentioned", "email_commented", "email_state_changed", "email_membership", "email_agents", "created_at", "updated_at", "inbox_checks", "email_checks"}
	workspaceNotificationSettingColumnsWithoutDefault = []string{"workspace_id", "account_id"}
	workspaceNotificationSettingColumnsWithDefault    = []string{"inbox_assigned", "inbox_mentioned", "inbox_commented", "inbox_state_changed", "inbox_membership", "inbox_agents", "email_assigned", "email_mentioned", "email_commented", "email_state_changed", "email_membership", "email_agents", "created_at", "updated_at", "inbox_checks", "email_checks"}
	workspaceNotificationSettingPrimaryKeyColumns     = []string{"workspace_id", "account_id"}
	workspaceNotificationSettingGeneratedColumns      = []string{}
)

type (
	// WorkspaceNotificationSettingSlice is an alias for a slice of pointers to WorkspaceNotificationSetting.
	// This should almost always be used instead of []WorkspaceNotificationSetting.
	WorkspaceNotificationSettingSlice []*WorkspaceNotificationSetting
	// WorkspaceNotificationSettingHook is the signature for custom WorkspaceNotificationSetting hook methods
	WorkspaceNotificationSettingHook func(context.Context, boil.ContextExecutor, *WorkspaceNotificationSetting) error

	workspaceNotificationSettingQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workspaceNotificationSettingType                 = reflect.TypeOf(&WorkspaceNotificationSetting{})
	workspaceNotificationSettingMapping              = queries.MakeStructMapping(workspaceNotificationSettingType)
	workspaceNotificationSettingPrimaryKeyMapping, _ = queries.BindMapping(workspaceNotificationSettingType, workspaceNotificationSettingMapping, workspaceNotificationSettingPrimaryKeyColumns)
	workspaceNotificationSettingInsertCacheMut       sync.RWMutex
	workspaceNotificationSettingInsertCache          = make(map[string]insertCache)
	workspaceNotificationSettingUpdateCacheMut       sync.RWMutex
	workspaceNotificationSettingUpdateCache          = make(map[string]updateCache)
	workspaceNotificationSettingUpsertCacheMut       sync.RWMutex
	workspaceNotificationSettingUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workspaceNotificationSettingAfterSelectMu sync.Mutex
var workspaceNotificationSettingAfterSelectHooks []WorkspaceNotificationSettingHook

var workspaceNotificationSettingBeforeInsertMu sync.Mutex
var workspaceNotificationSettingBeforeInsertHooks []WorkspaceNotificationSettingHook
var workspaceNotificationSettingAfterInsertMu sync.Mutex
var workspaceNotificationSettingAfterInsertHooks []WorkspaceNotificationSettingHook

var workspaceNotificationSettingBeforeUpdateMu sync.Mutex
var workspaceNotificationSettingBeforeUpdateHooks []WorkspaceNotificationSettingHook
var workspaceNotificationSettingAfterUpdateMu sync.Mutex
var workspaceNotificationSettingAfterUpdateHooks []WorkspaceNotificationSettingHook

var workspaceNotificationSettingBeforeDeleteMu sync.Mutex
var workspaceNotificationSettingBeforeDeleteHooks []WorkspaceNotificationSettingHook
var workspaceNotificationSettingAfterDeleteMu sync.Mutex
var workspaceNotificationSettingAfterDeleteHooks []WorkspaceNotificationSettingHook

var workspaceNotificationSettingBeforeUpsertMu sync.Mutex
var workspaceNotificationSettingBeforeUpsertHooks []WorkspaceNotificationSettingHook
var workspaceNotificationSettingAfterUpsertMu sync.Mutex
var workspaceNotificationSettingAfterUpsertHooks []WorkspaceNotificationSettingHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkspaceNotificationSetting) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceNotificationSettingAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkspaceNotificationSetting) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceNotificationSettingBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkspaceNotificationSetting) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceNotificationSettingAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkspaceNotificationSetting) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceNotificationSettingBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkspaceNotificationSetting) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceNotificationSettingAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkspaceNotificationSetting) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceNotificationSettingBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkspaceNotificationSetting) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceNotificationSettingAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkspaceNotificationSetting) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceNotificationSettingBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkspaceNotificationSetting) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceNotificationSettingAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkspaceNotificationSettingHook registers your hook function for all future operations.
func AddWorkspaceNotificationSettingHook(hookPoint boil.HookPoint, workspaceNotificationSettingHook WorkspaceNotificationSettingHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workspaceNotificationSettingAfterSelectMu.Lock()
		workspaceNotificationSettingAfterSelectHooks = append(workspaceNotificationSettingAfterSelectHooks, workspaceNotificationSettingHook)
		workspaceNotificationSettingAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workspaceNotificationSettingBeforeInsertMu.Lock()
		workspaceNotificationSettingBeforeInsertHooks = append(workspaceNotificationSettingBeforeInsertHooks, workspaceNotificationSettingHook)
		workspaceNotificationSettingBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workspaceNotificationSettingAfterInsertMu.Lock()
		workspaceNotificationSettingAfterInsertHooks = append(workspaceNotificationSettingAfterInsertHooks, workspaceNotificationSettingHook)
		workspaceNotificationSettingAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workspaceNotificationSettingBeforeUpdateMu.Lock()
		workspaceNotificationSettingBeforeUpdateHooks = append(workspaceNotificationSettingBeforeUpdateHooks, workspaceNotificationSettingHook)
		workspaceNotificationSettingBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workspaceNotificationSettingAfterUpdateMu.Lock()
		workspaceNotificationSettingAfterUpdateHooks = append(workspaceNotificationSettingAfterUpdateHooks, workspaceNotificationSettingHook)
		workspaceNotificationSettingAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workspaceNotificationSettingBeforeDeleteMu.Lock()
		workspaceNotificationSettingBeforeDeleteHooks = append(workspaceNotificationSettingBeforeDeleteHooks, workspaceNotificationSettingHook)
		workspaceNotificationSettingBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workspaceNotificationSettingAfterDeleteMu.Lock()
		workspaceNotificationSettingAfterDeleteHooks = append(workspaceNotificationSettingAfterDeleteHooks, workspaceNotificationSettingHook)
		workspaceNotificationSettingAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workspaceNotificationSettingBeforeUpsertMu.Lock()
		workspaceNotificationSettingBeforeUpsertHooks = append(workspaceNotificationSettingBeforeUpsertHooks, workspaceNotificationSettingHook)
		workspaceNotificationSettingBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workspaceNotificationSettingAfterUpsertMu.Lock()
		workspaceNotificationSettingAfterUpsertHooks = append(workspaceNotificationSettingAfterUpsertHooks, workspaceNotificationSettingHook)
		workspaceNotificationSettingAfterUpsertMu.Unlock()
	}
}

// One returns a single workspaceNotificationSetting record from the query.
func (q workspaceNotificationSettingQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkspaceNotificationSetting, error) {
	o := &WorkspaceNotificationSetting{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for workspace_notification_settings")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkspaceNotificationSetting records from the query.
func (q workspaceNotificationSettingQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkspaceNotificationSettingSlice, error) {
	var o []*WorkspaceNotificationSetting

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to WorkspaceNotificationSetting slice")
	}

	if len(workspaceNotificationSettingAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkspaceNotificationSetting records in the query.
func (q workspaceNotificationSettingQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count workspace_notification_settings rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workspaceNotificationSettingQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if workspace_notification_settings exists")
	}

	return count > 0, nil
}

// WorkspaceNotificationSettings retrieves all the records using an executor.
func WorkspaceNotificationSettings(mods ...qm.QueryMod) workspaceNotificationSettingQuery {
	mods = append(mods, qm.From("\"workspace_notification_settings\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"workspace_notification_settings\".*"})
	}

	return workspaceNotificationSettingQuery{q}
}

// FindWorkspaceNotificationSetting retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkspaceNotificationSetting(ctx context.Context, exec boil.ContextExecutor, workspaceID string, accountID string, selectCols ...string) (*WorkspaceNotificationSetting, error) {
	workspaceNotificationSettingObj := &WorkspaceNotificationSetting{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"workspace_notification_settings\" where \"workspace_id\"=$1 AND \"account_id\"=$2", sel,
	)

	q := queries.Raw(query, workspaceID, accountID)

	err := q.Bind(ctx, exec, workspaceNotificationSettingObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from workspace_notification_settings")
	}

	if err = workspaceNotificationSettingObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workspaceNotificationSettingObj, err
	}

	return workspaceNotificationSettingObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkspaceNotificationSetting) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_notification_settings provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceNotificationSettingColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workspaceNotificationSettingInsertCacheMut.RLock()
	cache, cached := workspaceNotificationSettingInsertCache[key]
	workspaceNotificationSettingInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workspaceNotificationSettingAllColumns,
			workspaceNotificationSettingColumnsWithDefault,
			workspaceNotificationSettingColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workspaceNotificationSettingType, workspaceNotificationSettingMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workspaceNotificationSettingType, workspaceNotificationSettingMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"workspace_notification_settings\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"workspace_notification_settings\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into workspace_notification_settings")
	}

	if !cached {
		workspaceNotificationSettingInsertCacheMut.Lock()
		workspaceNotificationSettingInsertCache[key] = cache
		workspaceNotificationSettingInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkspaceNotificationSetting.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkspaceNotificationSetting) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workspaceNotificationSettingUpdateCacheMut.RLock()
	cache, cached := workspaceNotificationSettingUpdateCache[key]
	workspaceNotificationSettingUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workspaceNotificationSettingAllColumns,
			workspaceNotificationSettingPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update workspace_notification_settings, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"workspace_notification_settings\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workspaceNotificationSettingPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workspaceNotificationSettingType, workspaceNotificationSettingMapping, append(wl, workspaceNotificationSettingPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update workspace_notification_settings row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for workspace_notification_settings")
	}

	if !cached {
		workspaceNotificationSettingUpdateCacheMut.Lock()
		workspaceNotificationSettingUpdateCache[key] = cache
		workspaceNotificationSettingUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workspaceNotificationSettingQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for workspace_notification_settings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for workspace_notification_settings")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkspaceNotificationSettingSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceNotificationSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"workspace_notification_settings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workspaceNotificationSettingPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in workspaceNotificationSetting slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all workspaceNotificationSetting")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkspaceNotificationSetting) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_notification_settings provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceNotificationSettingColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workspaceNotificationSettingUpsertCacheMut.RLock()
	cache, cached := workspaceNotificationSettingUpsertCache[key]
	workspaceNotificationSettingUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workspaceNotificationSettingAllColumns,
			workspaceNotificationSettingColumnsWithDefault,
			workspaceNotificationSettingColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workspaceNotificationSettingAllColumns,
			workspaceNotificationSettingPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert workspace_notification_settings, could not build update column list")
		}

		ret := strmangle.SetComplement(workspaceNotificationSettingAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(workspaceNotificationSettingPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert workspace_notification_settings, could not build conflict column list")
			}

			conflict = make([]string, len(workspaceNotificationSettingPrimaryKeyColumns))
			copy(conflict, workspaceNotificationSettingPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"workspace_notification_settings\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(workspaceNotificationSettingType, workspaceNotificationSettingMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workspaceNotificationSettingType, workspaceNotificationSettingMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert workspace_notification_settings")
	}

	if !cached {
		workspaceNotificationSettingUpsertCacheMut.Lock()
		workspaceNotificationSettingUpsertCache[key] = cache
		workspaceNotificationSettingUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkspaceNotificationSetting record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkspaceNotificationSetting) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no WorkspaceNotificationSetting provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workspaceNotificationSettingPrimaryKeyMapping)
	sql := "DELETE FROM \"workspace_notification_settings\" WHERE \"workspace_id\"=$1 AND \"account_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from workspace_notification_settings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for workspace_notification_settings")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workspaceNotificationSettingQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no workspaceNotificationSettingQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspace_notification_settings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_notification_settings")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkspaceNotificationSettingSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workspaceNotificationSettingBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceNotificationSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"workspace_notification_settings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceNotificationSettingPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspaceNotificationSetting slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_notification_settings")
	}

	if len(workspaceNotificationSettingAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkspaceNotificationSetting) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkspaceNotificationSetting(ctx, exec, o.WorkspaceID, o.AccountID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkspaceNotificationSettingSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkspaceNotificationSettingSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceNotificationSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"workspace_notification_settings\".* FROM \"workspace_notification_settings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceNotificationSettingPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in WorkspaceNotificationSettingSlice")
	}

	*o = slice

	return nil
}

// WorkspaceNotificationSettingExists checks if the WorkspaceNotificationSetting row exists.
func WorkspaceNotificationSettingExists(ctx context.Context, exec boil.ContextExecutor, workspaceID string, accountID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"workspace_notification_settings\" where \"workspace_id\"=$1 AND \"account_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, workspaceID, accountID)
	}
	row := exec.QueryRowContext(ctx, sql, workspaceID, accountID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if workspace_notification_settings exists")
	}

	return exists, nil
}

// Exists checks if the WorkspaceNotificationSetting row exists.
func (o *WorkspaceNotificationSetting) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkspaceNotificationSettingExists(ctx, exec, o.WorkspaceID, o.AccountID)
}
