// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WorkspaceCodebaseRepository is an object representing the database table.
type WorkspaceCodebaseRepository struct {
	ID             string `boil:"id" json:"id" toml:"id" yaml:"id"`
	CodebaseID     string `boil:"codebase_id" json:"codebase_id" toml:"codebase_id" yaml:"codebase_id"`
	Ordinal        int    `boil:"ordinal" json:"ordinal" toml:"ordinal" yaml:"ordinal"`
	Name           string `boil:"name" json:"name" toml:"name" yaml:"name"`
	RelPath        string `boil:"rel_path" json:"rel_path" toml:"rel_path" yaml:"rel_path"`
	DefaultBranch  string `boil:"default_branch" json:"default_branch" toml:"default_branch" yaml:"default_branch"`
	RemoteHash     string `boil:"remote_hash" json:"remote_hash" toml:"remote_hash" yaml:"remote_hash"`
	RemoteHost     string `boil:"remote_host" json:"remote_host" toml:"remote_host" yaml:"remote_host"`
	RemotePathTail string `boil:"remote_path_tail" json:"remote_path_tail" toml:"remote_path_tail" yaml:"remote_path_tail"`

	R *workspaceCodebaseRepositoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workspaceCodebaseRepositoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkspaceCodebaseRepositoryColumns = struct {
	ID             string
	CodebaseID     string
	Ordinal        string
	Name           string
	RelPath        string
	DefaultBranch  string
	RemoteHash     string
	RemoteHost     string
	RemotePathTail string
}{
	ID:             "id",
	CodebaseID:     "codebase_id",
	Ordinal:        "ordinal",
	Name:           "name",
	RelPath:        "rel_path",
	DefaultBranch:  "default_branch",
	RemoteHash:     "remote_hash",
	RemoteHost:     "remote_host",
	RemotePathTail: "remote_path_tail",
}

var WorkspaceCodebaseRepositoryTableColumns = struct {
	ID             string
	CodebaseID     string
	Ordinal        string
	Name           string
	RelPath        string
	DefaultBranch  string
	RemoteHash     string
	RemoteHost     string
	RemotePathTail string
}{
	ID:             "workspace_codebase_repositories.id",
	CodebaseID:     "workspace_codebase_repositories.codebase_id",
	Ordinal:        "workspace_codebase_repositories.ordinal",
	Name:           "workspace_codebase_repositories.name",
	RelPath:        "workspace_codebase_repositories.rel_path",
	DefaultBranch:  "workspace_codebase_repositories.default_branch",
	RemoteHash:     "workspace_codebase_repositories.remote_hash",
	RemoteHost:     "workspace_codebase_repositories.remote_host",
	RemotePathTail: "workspace_codebase_repositories.remote_path_tail",
}

// Generated where

var WorkspaceCodebaseRepositoryWhere = struct {
	ID             whereHelperstring
	CodebaseID     whereHelperstring
	Ordinal        whereHelperint
	Name           whereHelperstring
	RelPath        whereHelperstring
	DefaultBranch  whereHelperstring
	RemoteHash     whereHelperstring
	RemoteHost     whereHelperstring
	RemotePathTail whereHelperstring
}{
	ID:             whereHelperstring{field: "\"workspace_codebase_repositories\".\"id\""},
	CodebaseID:     whereHelperstring{field: "\"workspace_codebase_repositories\".\"codebase_id\""},
	Ordinal:        whereHelperint{field: "\"workspace_codebase_repositories\".\"ordinal\""},
	Name:           whereHelperstring{field: "\"workspace_codebase_repositories\".\"name\""},
	RelPath:        whereHelperstring{field: "\"workspace_codebase_repositories\".\"rel_path\""},
	DefaultBranch:  whereHelperstring{field: "\"workspace_codebase_repositories\".\"default_branch\""},
	RemoteHash:     whereHelperstring{field: "\"workspace_codebase_repositories\".\"remote_hash\""},
	RemoteHost:     whereHelperstring{field: "\"workspace_codebase_repositories\".\"remote_host\""},
	RemotePathTail: whereHelperstring{field: "\"workspace_codebase_repositories\".\"remote_path_tail\""},
}

// WorkspaceCodebaseRepositoryRels is where relationship names are stored.
var WorkspaceCodebaseRepositoryRels = struct {
	Codebase string
}{
	Codebase: "Codebase",
}

// workspaceCodebaseRepositoryR is where relationships are stored.
type workspaceCodebaseRepositoryR struct {
	Codebase *WorkspaceCodebasis `boil:"Codebase" json:"Codebase" toml:"Codebase" yaml:"Codebase"`
}

// NewStruct creates a new relationship struct
func (*workspaceCodebaseRepositoryR) NewStruct() *workspaceCodebaseRepositoryR {
	return &workspaceCodebaseRepositoryR{}
}

func (o *WorkspaceCodebaseRepository) GetCodebase() *WorkspaceCodebasis {
	if o == nil {
		return nil
	}

	return o.R.GetCodebase()
}

func (r *workspaceCodebaseRepositoryR) GetCodebase() *WorkspaceCodebasis {
	if r == nil {
		return nil
	}

	return r.Codebase
}

// workspaceCodebaseRepositoryL is where Load methods for each relationship are stored.
type workspaceCodebaseRepositoryL struct{}

var (
	workspaceCodebaseRepositoryAllColumns            = []string{"id", "codebase_id", "ordinal", "name", "rel_path", "default_branch", "remote_hash", "remote_host", "remote_path_tail"}
	workspaceCodebaseRepositoryColumnsWithoutDefault = []string{"codebase_id", "ordinal", "name", "rel_path"}
	workspaceCodebaseRepositoryColumnsWithDefault    = []string{"id", "default_branch", "remote_hash", "remote_host", "remote_path_tail"}
	workspaceCodebaseRepositoryPrimaryKeyColumns     = []string{"id"}
	workspaceCodebaseRepositoryGeneratedColumns      = []string{}
)

type (
	// WorkspaceCodebaseRepositorySlice is an alias for a slice of pointers to WorkspaceCodebaseRepository.
	// This should almost always be used instead of []WorkspaceCodebaseRepository.
	WorkspaceCodebaseRepositorySlice []*WorkspaceCodebaseRepository
	// WorkspaceCodebaseRepositoryHook is the signature for custom WorkspaceCodebaseRepository hook methods
	WorkspaceCodebaseRepositoryHook func(context.Context, boil.ContextExecutor, *WorkspaceCodebaseRepository) error

	workspaceCodebaseRepositoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workspaceCodebaseRepositoryType                 = reflect.TypeOf(&WorkspaceCodebaseRepository{})
	workspaceCodebaseRepositoryMapping              = queries.MakeStructMapping(workspaceCodebaseRepositoryType)
	workspaceCodebaseRepositoryPrimaryKeyMapping, _ = queries.BindMapping(workspaceCodebaseRepositoryType, workspaceCodebaseRepositoryMapping, workspaceCodebaseRepositoryPrimaryKeyColumns)
	workspaceCodebaseRepositoryInsertCacheMut       sync.RWMutex
	workspaceCodebaseRepositoryInsertCache          = make(map[string]insertCache)
	workspaceCodebaseRepositoryUpdateCacheMut       sync.RWMutex
	workspaceCodebaseRepositoryUpdateCache          = make(map[string]updateCache)
	workspaceCodebaseRepositoryUpsertCacheMut       sync.RWMutex
	workspaceCodebaseRepositoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workspaceCodebaseRepositoryAfterSelectMu sync.Mutex
var workspaceCodebaseRepositoryAfterSelectHooks []WorkspaceCodebaseRepositoryHook

var workspaceCodebaseRepositoryBeforeInsertMu sync.Mutex
var workspaceCodebaseRepositoryBeforeInsertHooks []WorkspaceCodebaseRepositoryHook
var workspaceCodebaseRepositoryAfterInsertMu sync.Mutex
var workspaceCodebaseRepositoryAfterInsertHooks []WorkspaceCodebaseRepositoryHook

var workspaceCodebaseRepositoryBeforeUpdateMu sync.Mutex
var workspaceCodebaseRepositoryBeforeUpdateHooks []WorkspaceCodebaseRepositoryHook
var workspaceCodebaseRepositoryAfterUpdateMu sync.Mutex
var workspaceCodebaseRepositoryAfterUpdateHooks []WorkspaceCodebaseRepositoryHook

var workspaceCodebaseRepositoryBeforeDeleteMu sync.Mutex
var workspaceCodebaseRepositoryBeforeDeleteHooks []WorkspaceCodebaseRepositoryHook
var workspaceCodebaseRepositoryAfterDeleteMu sync.Mutex
var workspaceCodebaseRepositoryAfterDeleteHooks []WorkspaceCodebaseRepositoryHook

var workspaceCodebaseRepositoryBeforeUpsertMu sync.Mutex
var workspaceCodebaseRepositoryBeforeUpsertHooks []WorkspaceCodebaseRepositoryHook
var workspaceCodebaseRepositoryAfterUpsertMu sync.Mutex
var workspaceCodebaseRepositoryAfterUpsertHooks []WorkspaceCodebaseRepositoryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkspaceCodebaseRepository) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceCodebaseRepositoryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkspaceCodebaseRepository) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceCodebaseRepositoryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkspaceCodebaseRepository) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceCodebaseRepositoryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkspaceCodebaseRepository) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceCodebaseRepositoryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkspaceCodebaseRepository) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceCodebaseRepositoryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkspaceCodebaseRepository) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceCodebaseRepositoryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkspaceCodebaseRepository) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceCodebaseRepositoryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkspaceCodebaseRepository) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceCodebaseRepositoryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkspaceCodebaseRepository) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceCodebaseRepositoryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkspaceCodebaseRepositoryHook registers your hook function for all future operations.
func AddWorkspaceCodebaseRepositoryHook(hookPoint boil.HookPoint, workspaceCodebaseRepositoryHook WorkspaceCodebaseRepositoryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workspaceCodebaseRepositoryAfterSelectMu.Lock()
		workspaceCodebaseRepositoryAfterSelectHooks = append(workspaceCodebaseRepositoryAfterSelectHooks, workspaceCodebaseRepositoryHook)
		workspaceCodebaseRepositoryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workspaceCodebaseRepositoryBeforeInsertMu.Lock()
		workspaceCodebaseRepositoryBeforeInsertHooks = append(workspaceCodebaseRepositoryBeforeInsertHooks, workspaceCodebaseRepositoryHook)
		workspaceCodebaseRepositoryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workspaceCodebaseRepositoryAfterInsertMu.Lock()
		workspaceCodebaseRepositoryAfterInsertHooks = append(workspaceCodebaseRepositoryAfterInsertHooks, workspaceCodebaseRepositoryHook)
		workspaceCodebaseRepositoryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workspaceCodebaseRepositoryBeforeUpdateMu.Lock()
		workspaceCodebaseRepositoryBeforeUpdateHooks = append(workspaceCodebaseRepositoryBeforeUpdateHooks, workspaceCodebaseRepositoryHook)
		workspaceCodebaseRepositoryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workspaceCodebaseRepositoryAfterUpdateMu.Lock()
		workspaceCodebaseRepositoryAfterUpdateHooks = append(workspaceCodebaseRepositoryAfterUpdateHooks, workspaceCodebaseRepositoryHook)
		workspaceCodebaseRepositoryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workspaceCodebaseRepositoryBeforeDeleteMu.Lock()
		workspaceCodebaseRepositoryBeforeDeleteHooks = append(workspaceCodebaseRepositoryBeforeDeleteHooks, workspaceCodebaseRepositoryHook)
		workspaceCodebaseRepositoryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workspaceCodebaseRepositoryAfterDeleteMu.Lock()
		workspaceCodebaseRepositoryAfterDeleteHooks = append(workspaceCodebaseRepositoryAfterDeleteHooks, workspaceCodebaseRepositoryHook)
		workspaceCodebaseRepositoryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workspaceCodebaseRepositoryBeforeUpsertMu.Lock()
		workspaceCodebaseRepositoryBeforeUpsertHooks = append(workspaceCodebaseRepositoryBeforeUpsertHooks, workspaceCodebaseRepositoryHook)
		workspaceCodebaseRepositoryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workspaceCodebaseRepositoryAfterUpsertMu.Lock()
		workspaceCodebaseRepositoryAfterUpsertHooks = append(workspaceCodebaseRepositoryAfterUpsertHooks, workspaceCodebaseRepositoryHook)
		workspaceCodebaseRepositoryAfterUpsertMu.Unlock()
	}
}

// One returns a single workspaceCodebaseRepository record from the query.
func (q workspaceCodebaseRepositoryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkspaceCodebaseRepository, error) {
	o := &WorkspaceCodebaseRepository{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for workspace_codebase_repositories")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkspaceCodebaseRepository records from the query.
func (q workspaceCodebaseRepositoryQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkspaceCodebaseRepositorySlice, error) {
	var o []*WorkspaceCodebaseRepository

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to WorkspaceCodebaseRepository slice")
	}

	if len(workspaceCodebaseRepositoryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkspaceCodebaseRepository records in the query.
func (q workspaceCodebaseRepositoryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count workspace_codebase_repositories rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workspaceCodebaseRepositoryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if workspace_codebase_repositories exists")
	}

	return count > 0, nil
}

// Codebase pointed to by the foreign key.
func (o *WorkspaceCodebaseRepository) Codebase(mods ...qm.QueryMod) workspaceCodebasisQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CodebaseID),
	}

	queryMods = append(queryMods, mods...)

	return WorkspaceCodebases(queryMods...)
}

// LoadCodebase allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workspaceCodebaseRepositoryL) LoadCodebase(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceCodebaseRepository any, mods queries.Applicator) error {
	var slice []*WorkspaceCodebaseRepository
	var object *WorkspaceCodebaseRepository

	if singular {
		var ok bool
		object, ok = maybeWorkspaceCodebaseRepository.(*WorkspaceCodebaseRepository)
		if !ok {
			object = new(WorkspaceCodebaseRepository)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceCodebaseRepository)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceCodebaseRepository))
			}
		}
	} else {
		s, ok := maybeWorkspaceCodebaseRepository.(*[]*WorkspaceCodebaseRepository)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceCodebaseRepository)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceCodebaseRepository))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceCodebaseRepositoryR{}
		}
		args[object.CodebaseID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceCodebaseRepositoryR{}
			}

			args[obj.CodebaseID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspace_codebases`),
		qm.WhereIn(`workspace_codebases.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load WorkspaceCodebasis")
	}

	var resultSlice []*WorkspaceCodebasis
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice WorkspaceCodebasis")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workspace_codebases")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspace_codebases")
	}

	if len(workspaceCodebasisAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Codebase = foreign
		if foreign.R == nil {
			foreign.R = &workspaceCodebasisR{}
		}
		foreign.R.CodebaseWorkspaceCodebaseRepositories = append(foreign.R.CodebaseWorkspaceCodebaseRepositories, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CodebaseID == foreign.ID {
				local.R.Codebase = foreign
				if foreign.R == nil {
					foreign.R = &workspaceCodebasisR{}
				}
				foreign.R.CodebaseWorkspaceCodebaseRepositories = append(foreign.R.CodebaseWorkspaceCodebaseRepositories, local)
				break
			}
		}
	}

	return nil
}

// SetCodebase of the workspaceCodebaseRepository to the related item.
// Sets o.R.Codebase to related.
// Adds o to related.R.CodebaseWorkspaceCodebaseRepositories.
func (o *WorkspaceCodebaseRepository) SetCodebase(ctx context.Context, exec boil.ContextExecutor, insert bool, related *WorkspaceCodebasis) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"workspace_codebase_repositories\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"codebase_id"}),
		strmangle.WhereClause("\"", "\"", 2, workspaceCodebaseRepositoryPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CodebaseID = related.ID
	if o.R == nil {
		o.R = &workspaceCodebaseRepositoryR{
			Codebase: related,
		}
	} else {
		o.R.Codebase = related
	}

	if related.R == nil {
		related.R = &workspaceCodebasisR{
			CodebaseWorkspaceCodebaseRepositories: WorkspaceCodebaseRepositorySlice{o},
		}
	} else {
		related.R.CodebaseWorkspaceCodebaseRepositories = append(related.R.CodebaseWorkspaceCodebaseRepositories, o)
	}

	return nil
}

// WorkspaceCodebaseRepositories retrieves all the records using an executor.
func WorkspaceCodebaseRepositories(mods ...qm.QueryMod) workspaceCodebaseRepositoryQuery {
	mods = append(mods, qm.From("\"workspace_codebase_repositories\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"workspace_codebase_repositories\".*"})
	}

	return workspaceCodebaseRepositoryQuery{q}
}

// FindWorkspaceCodebaseRepository retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkspaceCodebaseRepository(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WorkspaceCodebaseRepository, error) {
	workspaceCodebaseRepositoryObj := &WorkspaceCodebaseRepository{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"workspace_codebase_repositories\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workspaceCodebaseRepositoryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from workspace_codebase_repositories")
	}

	if err = workspaceCodebaseRepositoryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workspaceCodebaseRepositoryObj, err
	}

	return workspaceCodebaseRepositoryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkspaceCodebaseRepository) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_codebase_repositories provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceCodebaseRepositoryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workspaceCodebaseRepositoryInsertCacheMut.RLock()
	cache, cached := workspaceCodebaseRepositoryInsertCache[key]
	workspaceCodebaseRepositoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workspaceCodebaseRepositoryAllColumns,
			workspaceCodebaseRepositoryColumnsWithDefault,
			workspaceCodebaseRepositoryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workspaceCodebaseRepositoryType, workspaceCodebaseRepositoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workspaceCodebaseRepositoryType, workspaceCodebaseRepositoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"workspace_codebase_repositories\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"workspace_codebase_repositories\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into workspace_codebase_repositories")
	}

	if !cached {
		workspaceCodebaseRepositoryInsertCacheMut.Lock()
		workspaceCodebaseRepositoryInsertCache[key] = cache
		workspaceCodebaseRepositoryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkspaceCodebaseRepository.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkspaceCodebaseRepository) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workspaceCodebaseRepositoryUpdateCacheMut.RLock()
	cache, cached := workspaceCodebaseRepositoryUpdateCache[key]
	workspaceCodebaseRepositoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workspaceCodebaseRepositoryAllColumns,
			workspaceCodebaseRepositoryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update workspace_codebase_repositories, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"workspace_codebase_repositories\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workspaceCodebaseRepositoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workspaceCodebaseRepositoryType, workspaceCodebaseRepositoryMapping, append(wl, workspaceCodebaseRepositoryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update workspace_codebase_repositories row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for workspace_codebase_repositories")
	}

	if !cached {
		workspaceCodebaseRepositoryUpdateCacheMut.Lock()
		workspaceCodebaseRepositoryUpdateCache[key] = cache
		workspaceCodebaseRepositoryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workspaceCodebaseRepositoryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for workspace_codebase_repositories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for workspace_codebase_repositories")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkspaceCodebaseRepositorySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceCodebaseRepositoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"workspace_codebase_repositories\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workspaceCodebaseRepositoryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in workspaceCodebaseRepository slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all workspaceCodebaseRepository")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkspaceCodebaseRepository) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_codebase_repositories provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceCodebaseRepositoryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workspaceCodebaseRepositoryUpsertCacheMut.RLock()
	cache, cached := workspaceCodebaseRepositoryUpsertCache[key]
	workspaceCodebaseRepositoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workspaceCodebaseRepositoryAllColumns,
			workspaceCodebaseRepositoryColumnsWithDefault,
			workspaceCodebaseRepositoryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workspaceCodebaseRepositoryAllColumns,
			workspaceCodebaseRepositoryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert workspace_codebase_repositories, could not build update column list")
		}

		ret := strmangle.SetComplement(workspaceCodebaseRepositoryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(workspaceCodebaseRepositoryPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert workspace_codebase_repositories, could not build conflict column list")
			}

			conflict = make([]string, len(workspaceCodebaseRepositoryPrimaryKeyColumns))
			copy(conflict, workspaceCodebaseRepositoryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"workspace_codebase_repositories\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(workspaceCodebaseRepositoryType, workspaceCodebaseRepositoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workspaceCodebaseRepositoryType, workspaceCodebaseRepositoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert workspace_codebase_repositories")
	}

	if !cached {
		workspaceCodebaseRepositoryUpsertCacheMut.Lock()
		workspaceCodebaseRepositoryUpsertCache[key] = cache
		workspaceCodebaseRepositoryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkspaceCodebaseRepository record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkspaceCodebaseRepository) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no WorkspaceCodebaseRepository provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workspaceCodebaseRepositoryPrimaryKeyMapping)
	sql := "DELETE FROM \"workspace_codebase_repositories\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from workspace_codebase_repositories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for workspace_codebase_repositories")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workspaceCodebaseRepositoryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no workspaceCodebaseRepositoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspace_codebase_repositories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_codebase_repositories")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkspaceCodebaseRepositorySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workspaceCodebaseRepositoryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceCodebaseRepositoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"workspace_codebase_repositories\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceCodebaseRepositoryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspaceCodebaseRepository slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_codebase_repositories")
	}

	if len(workspaceCodebaseRepositoryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkspaceCodebaseRepository) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkspaceCodebaseRepository(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkspaceCodebaseRepositorySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkspaceCodebaseRepositorySlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceCodebaseRepositoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"workspace_codebase_repositories\".* FROM \"workspace_codebase_repositories\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceCodebaseRepositoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in WorkspaceCodebaseRepositorySlice")
	}

	*o = slice

	return nil
}

// WorkspaceCodebaseRepositoryExists checks if the WorkspaceCodebaseRepository row exists.
func WorkspaceCodebaseRepositoryExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"workspace_codebase_repositories\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if workspace_codebase_repositories exists")
	}

	return exists, nil
}

// Exists checks if the WorkspaceCodebaseRepository row exists.
func (o *WorkspaceCodebaseRepository) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkspaceCodebaseRepositoryExists(ctx, exec, o.ID)
}
