// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WorkspaceLabel is an object representing the database table.
type WorkspaceLabel struct {
	ID          string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	WorkspaceID string      `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	TeamID      null.String `boil:"team_id" json:"team_id,omitempty" toml:"team_id" yaml:"team_id,omitempty"`
	GroupID     null.String `boil:"group_id" json:"group_id,omitempty" toml:"group_id" yaml:"group_id,omitempty"`
	Name        string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Color       string      `boil:"color" json:"color" toml:"color" yaml:"color"`
	CreatedAt   time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *workspaceLabelR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workspaceLabelL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkspaceLabelColumns = struct {
	ID          string
	WorkspaceID string
	TeamID      string
	GroupID     string
	Name        string
	Color       string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "id",
	WorkspaceID: "workspace_id",
	TeamID:      "team_id",
	GroupID:     "group_id",
	Name:        "name",
	Color:       "color",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

var WorkspaceLabelTableColumns = struct {
	ID          string
	WorkspaceID string
	TeamID      string
	GroupID     string
	Name        string
	Color       string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "workspace_labels.id",
	WorkspaceID: "workspace_labels.workspace_id",
	TeamID:      "workspace_labels.team_id",
	GroupID:     "workspace_labels.group_id",
	Name:        "workspace_labels.name",
	Color:       "workspace_labels.color",
	CreatedAt:   "workspace_labels.created_at",
	UpdatedAt:   "workspace_labels.updated_at",
}

// Generated where

var WorkspaceLabelWhere = struct {
	ID          whereHelperstring
	WorkspaceID whereHelperstring
	TeamID      whereHelpernull_String
	GroupID     whereHelpernull_String
	Name        whereHelperstring
	Color       whereHelperstring
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
}{
	ID:          whereHelperstring{field: "\"workspace_labels\".\"id\""},
	WorkspaceID: whereHelperstring{field: "\"workspace_labels\".\"workspace_id\""},
	TeamID:      whereHelpernull_String{field: "\"workspace_labels\".\"team_id\""},
	GroupID:     whereHelpernull_String{field: "\"workspace_labels\".\"group_id\""},
	Name:        whereHelperstring{field: "\"workspace_labels\".\"name\""},
	Color:       whereHelperstring{field: "\"workspace_labels\".\"color\""},
	CreatedAt:   whereHelpertime_Time{field: "\"workspace_labels\".\"created_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"workspace_labels\".\"updated_at\""},
}

// WorkspaceLabelRels is where relationship names are stored.
var WorkspaceLabelRels = struct {
	Workspace string
}{
	Workspace: "Workspace",
}

// workspaceLabelR is where relationships are stored.
type workspaceLabelR struct {
	Workspace *Workspace `boil:"Workspace" json:"Workspace" toml:"Workspace" yaml:"Workspace"`
}

// NewStruct creates a new relationship struct
func (*workspaceLabelR) NewStruct() *workspaceLabelR {
	return &workspaceLabelR{}
}

func (o *WorkspaceLabel) GetWorkspace() *Workspace {
	if o == nil {
		return nil
	}

	return o.R.GetWorkspace()
}

func (r *workspaceLabelR) GetWorkspace() *Workspace {
	if r == nil {
		return nil
	}

	return r.Workspace
}

// workspaceLabelL is where Load methods for each relationship are stored.
type workspaceLabelL struct{}

var (
	workspaceLabelAllColumns            = []string{"id", "workspace_id", "team_id", "group_id", "name", "color", "created_at", "updated_at"}
	workspaceLabelColumnsWithoutDefault = []string{"workspace_id", "name", "color"}
	workspaceLabelColumnsWithDefault    = []string{"id", "team_id", "group_id", "created_at", "updated_at"}
	workspaceLabelPrimaryKeyColumns     = []string{"id"}
	workspaceLabelGeneratedColumns      = []string{}
)

type (
	// WorkspaceLabelSlice is an alias for a slice of pointers to WorkspaceLabel.
	// This should almost always be used instead of []WorkspaceLabel.
	WorkspaceLabelSlice []*WorkspaceLabel
	// WorkspaceLabelHook is the signature for custom WorkspaceLabel hook methods
	WorkspaceLabelHook func(context.Context, boil.ContextExecutor, *WorkspaceLabel) error

	workspaceLabelQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workspaceLabelType                 = reflect.TypeOf(&WorkspaceLabel{})
	workspaceLabelMapping              = queries.MakeStructMapping(workspaceLabelType)
	workspaceLabelPrimaryKeyMapping, _ = queries.BindMapping(workspaceLabelType, workspaceLabelMapping, workspaceLabelPrimaryKeyColumns)
	workspaceLabelInsertCacheMut       sync.RWMutex
	workspaceLabelInsertCache          = make(map[string]insertCache)
	workspaceLabelUpdateCacheMut       sync.RWMutex
	workspaceLabelUpdateCache          = make(map[string]updateCache)
	workspaceLabelUpsertCacheMut       sync.RWMutex
	workspaceLabelUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workspaceLabelAfterSelectMu sync.Mutex
var workspaceLabelAfterSelectHooks []WorkspaceLabelHook

var workspaceLabelBeforeInsertMu sync.Mutex
var workspaceLabelBeforeInsertHooks []WorkspaceLabelHook
var workspaceLabelAfterInsertMu sync.Mutex
var workspaceLabelAfterInsertHooks []WorkspaceLabelHook

var workspaceLabelBeforeUpdateMu sync.Mutex
var workspaceLabelBeforeUpdateHooks []WorkspaceLabelHook
var workspaceLabelAfterUpdateMu sync.Mutex
var workspaceLabelAfterUpdateHooks []WorkspaceLabelHook

var workspaceLabelBeforeDeleteMu sync.Mutex
var workspaceLabelBeforeDeleteHooks []WorkspaceLabelHook
var workspaceLabelAfterDeleteMu sync.Mutex
var workspaceLabelAfterDeleteHooks []WorkspaceLabelHook

var workspaceLabelBeforeUpsertMu sync.Mutex
var workspaceLabelBeforeUpsertHooks []WorkspaceLabelHook
var workspaceLabelAfterUpsertMu sync.Mutex
var workspaceLabelAfterUpsertHooks []WorkspaceLabelHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkspaceLabel) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceLabelAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkspaceLabel) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceLabelBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkspaceLabel) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceLabelAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkspaceLabel) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceLabelBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkspaceLabel) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceLabelAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkspaceLabel) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceLabelBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkspaceLabel) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceLabelAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkspaceLabel) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceLabelBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkspaceLabel) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceLabelAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkspaceLabelHook registers your hook function for all future operations.
func AddWorkspaceLabelHook(hookPoint boil.HookPoint, workspaceLabelHook WorkspaceLabelHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workspaceLabelAfterSelectMu.Lock()
		workspaceLabelAfterSelectHooks = append(workspaceLabelAfterSelectHooks, workspaceLabelHook)
		workspaceLabelAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workspaceLabelBeforeInsertMu.Lock()
		workspaceLabelBeforeInsertHooks = append(workspaceLabelBeforeInsertHooks, workspaceLabelHook)
		workspaceLabelBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workspaceLabelAfterInsertMu.Lock()
		workspaceLabelAfterInsertHooks = append(workspaceLabelAfterInsertHooks, workspaceLabelHook)
		workspaceLabelAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workspaceLabelBeforeUpdateMu.Lock()
		workspaceLabelBeforeUpdateHooks = append(workspaceLabelBeforeUpdateHooks, workspaceLabelHook)
		workspaceLabelBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workspaceLabelAfterUpdateMu.Lock()
		workspaceLabelAfterUpdateHooks = append(workspaceLabelAfterUpdateHooks, workspaceLabelHook)
		workspaceLabelAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workspaceLabelBeforeDeleteMu.Lock()
		workspaceLabelBeforeDeleteHooks = append(workspaceLabelBeforeDeleteHooks, workspaceLabelHook)
		workspaceLabelBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workspaceLabelAfterDeleteMu.Lock()
		workspaceLabelAfterDeleteHooks = append(workspaceLabelAfterDeleteHooks, workspaceLabelHook)
		workspaceLabelAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workspaceLabelBeforeUpsertMu.Lock()
		workspaceLabelBeforeUpsertHooks = append(workspaceLabelBeforeUpsertHooks, workspaceLabelHook)
		workspaceLabelBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workspaceLabelAfterUpsertMu.Lock()
		workspaceLabelAfterUpsertHooks = append(workspaceLabelAfterUpsertHooks, workspaceLabelHook)
		workspaceLabelAfterUpsertMu.Unlock()
	}
}

// One returns a single workspaceLabel record from the query.
func (q workspaceLabelQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkspaceLabel, error) {
	o := &WorkspaceLabel{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for workspace_labels")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkspaceLabel records from the query.
func (q workspaceLabelQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkspaceLabelSlice, error) {
	var o []*WorkspaceLabel

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to WorkspaceLabel slice")
	}

	if len(workspaceLabelAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkspaceLabel records in the query.
func (q workspaceLabelQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count workspace_labels rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workspaceLabelQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if workspace_labels exists")
	}

	return count > 0, nil
}

// Workspace pointed to by the foreign key.
func (o *WorkspaceLabel) Workspace(mods ...qm.QueryMod) workspaceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorkspaceID),
	}

	queryMods = append(queryMods, mods...)

	return Workspaces(queryMods...)
}

// LoadWorkspace allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workspaceLabelL) LoadWorkspace(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceLabel any, mods queries.Applicator) error {
	var slice []*WorkspaceLabel
	var object *WorkspaceLabel

	if singular {
		var ok bool
		object, ok = maybeWorkspaceLabel.(*WorkspaceLabel)
		if !ok {
			object = new(WorkspaceLabel)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceLabel)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceLabel))
			}
		}
	} else {
		s, ok := maybeWorkspaceLabel.(*[]*WorkspaceLabel)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceLabel)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceLabel))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceLabelR{}
		}
		args[object.WorkspaceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceLabelR{}
			}

			args[obj.WorkspaceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspaces`),
		qm.WhereIn(`workspaces.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Workspace")
	}

	var resultSlice []*Workspace
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Workspace")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workspaces")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspaces")
	}

	if len(workspaceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Workspace = foreign
		if foreign.R == nil {
			foreign.R = &workspaceR{}
		}
		foreign.R.WorkspaceLabels = append(foreign.R.WorkspaceLabels, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkspaceID == foreign.ID {
				local.R.Workspace = foreign
				if foreign.R == nil {
					foreign.R = &workspaceR{}
				}
				foreign.R.WorkspaceLabels = append(foreign.R.WorkspaceLabels, local)
				break
			}
		}
	}

	return nil
}

// SetWorkspace of the workspaceLabel to the related item.
// Sets o.R.Workspace to related.
// Adds o to related.R.WorkspaceLabels.
func (o *WorkspaceLabel) SetWorkspace(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Workspace) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"workspace_labels\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"workspace_id"}),
		strmangle.WhereClause("\"", "\"", 2, workspaceLabelPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkspaceID = related.ID
	if o.R == nil {
		o.R = &workspaceLabelR{
			Workspace: related,
		}
	} else {
		o.R.Workspace = related
	}

	if related.R == nil {
		related.R = &workspaceR{
			WorkspaceLabels: WorkspaceLabelSlice{o},
		}
	} else {
		related.R.WorkspaceLabels = append(related.R.WorkspaceLabels, o)
	}

	return nil
}

// WorkspaceLabels retrieves all the records using an executor.
func WorkspaceLabels(mods ...qm.QueryMod) workspaceLabelQuery {
	mods = append(mods, qm.From("\"workspace_labels\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"workspace_labels\".*"})
	}

	return workspaceLabelQuery{q}
}

// FindWorkspaceLabel retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkspaceLabel(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WorkspaceLabel, error) {
	workspaceLabelObj := &WorkspaceLabel{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"workspace_labels\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workspaceLabelObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from workspace_labels")
	}

	if err = workspaceLabelObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workspaceLabelObj, err
	}

	return workspaceLabelObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkspaceLabel) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_labels provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceLabelColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workspaceLabelInsertCacheMut.RLock()
	cache, cached := workspaceLabelInsertCache[key]
	workspaceLabelInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workspaceLabelAllColumns,
			workspaceLabelColumnsWithDefault,
			workspaceLabelColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workspaceLabelType, workspaceLabelMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workspaceLabelType, workspaceLabelMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"workspace_labels\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"workspace_labels\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into workspace_labels")
	}

	if !cached {
		workspaceLabelInsertCacheMut.Lock()
		workspaceLabelInsertCache[key] = cache
		workspaceLabelInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkspaceLabel.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkspaceLabel) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workspaceLabelUpdateCacheMut.RLock()
	cache, cached := workspaceLabelUpdateCache[key]
	workspaceLabelUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workspaceLabelAllColumns,
			workspaceLabelPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update workspace_labels, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"workspace_labels\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workspaceLabelPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workspaceLabelType, workspaceLabelMapping, append(wl, workspaceLabelPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update workspace_labels row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for workspace_labels")
	}

	if !cached {
		workspaceLabelUpdateCacheMut.Lock()
		workspaceLabelUpdateCache[key] = cache
		workspaceLabelUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workspaceLabelQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for workspace_labels")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for workspace_labels")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkspaceLabelSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceLabelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"workspace_labels\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workspaceLabelPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in workspaceLabel slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all workspaceLabel")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkspaceLabel) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_labels provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceLabelColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workspaceLabelUpsertCacheMut.RLock()
	cache, cached := workspaceLabelUpsertCache[key]
	workspaceLabelUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workspaceLabelAllColumns,
			workspaceLabelColumnsWithDefault,
			workspaceLabelColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workspaceLabelAllColumns,
			workspaceLabelPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert workspace_labels, could not build update column list")
		}

		ret := strmangle.SetComplement(workspaceLabelAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(workspaceLabelPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert workspace_labels, could not build conflict column list")
			}

			conflict = make([]string, len(workspaceLabelPrimaryKeyColumns))
			copy(conflict, workspaceLabelPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"workspace_labels\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(workspaceLabelType, workspaceLabelMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workspaceLabelType, workspaceLabelMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert workspace_labels")
	}

	if !cached {
		workspaceLabelUpsertCacheMut.Lock()
		workspaceLabelUpsertCache[key] = cache
		workspaceLabelUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkspaceLabel record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkspaceLabel) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no WorkspaceLabel provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workspaceLabelPrimaryKeyMapping)
	sql := "DELETE FROM \"workspace_labels\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from workspace_labels")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for workspace_labels")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workspaceLabelQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no workspaceLabelQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspace_labels")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_labels")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkspaceLabelSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workspaceLabelBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceLabelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"workspace_labels\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceLabelPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspaceLabel slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_labels")
	}

	if len(workspaceLabelAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkspaceLabel) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkspaceLabel(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkspaceLabelSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkspaceLabelSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceLabelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"workspace_labels\".* FROM \"workspace_labels\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceLabelPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in WorkspaceLabelSlice")
	}

	*o = slice

	return nil
}

// WorkspaceLabelExists checks if the WorkspaceLabel row exists.
func WorkspaceLabelExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"workspace_labels\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if workspace_labels exists")
	}

	return exists, nil
}

// Exists checks if the WorkspaceLabel row exists.
func (o *WorkspaceLabel) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkspaceLabelExists(ctx, exec, o.ID)
}
