// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WorkspaceProject is an object representing the database table.
type WorkspaceProject struct {
	ID             string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	WorkspaceID    string      `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	Slug           string      `boil:"slug" json:"slug" toml:"slug" yaml:"slug"`
	Name           string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description    string      `boil:"description" json:"description" toml:"description" yaml:"description"`
	State          string      `boil:"state" json:"state" toml:"state" yaml:"state"`
	LeadAccountID  null.String `boil:"lead_account_id" json:"lead_account_id,omitempty" toml:"lead_account_id" yaml:"lead_account_id,omitempty"`
	TargetOn       null.Time   `boil:"target_on" json:"target_on,omitempty" toml:"target_on" yaml:"target_on,omitempty"`
	ArchivedAt     null.Time   `boil:"archived_at" json:"archived_at,omitempty" toml:"archived_at" yaml:"archived_at,omitempty"`
	CreatedAt      time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	SearchDocument null.String `boil:"search_document" json:"search_document,omitempty" toml:"search_document" yaml:"search_document,omitempty"`

	R *workspaceProjectR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workspaceProjectL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkspaceProjectColumns = struct {
	ID             string
	WorkspaceID    string
	Slug           string
	Name           string
	Description    string
	State          string
	LeadAccountID  string
	TargetOn       string
	ArchivedAt     string
	CreatedAt      string
	UpdatedAt      string
	SearchDocument string
}{
	ID:             "id",
	WorkspaceID:    "workspace_id",
	Slug:           "slug",
	Name:           "name",
	Description:    "description",
	State:          "state",
	LeadAccountID:  "lead_account_id",
	TargetOn:       "target_on",
	ArchivedAt:     "archived_at",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
	SearchDocument: "search_document",
}

var WorkspaceProjectTableColumns = struct {
	ID             string
	WorkspaceID    string
	Slug           string
	Name           string
	Description    string
	State          string
	LeadAccountID  string
	TargetOn       string
	ArchivedAt     string
	CreatedAt      string
	UpdatedAt      string
	SearchDocument string
}{
	ID:             "workspace_projects.id",
	WorkspaceID:    "workspace_projects.workspace_id",
	Slug:           "workspace_projects.slug",
	Name:           "workspace_projects.name",
	Description:    "workspace_projects.description",
	State:          "workspace_projects.state",
	LeadAccountID:  "workspace_projects.lead_account_id",
	TargetOn:       "workspace_projects.target_on",
	ArchivedAt:     "workspace_projects.archived_at",
	CreatedAt:      "workspace_projects.created_at",
	UpdatedAt:      "workspace_projects.updated_at",
	SearchDocument: "workspace_projects.search_document",
}

// Generated where

var WorkspaceProjectWhere = struct {
	ID             whereHelperstring
	WorkspaceID    whereHelperstring
	Slug           whereHelperstring
	Name           whereHelperstring
	Description    whereHelperstring
	State          whereHelperstring
	LeadAccountID  whereHelpernull_String
	TargetOn       whereHelpernull_Time
	ArchivedAt     whereHelpernull_Time
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
	SearchDocument whereHelpernull_String
}{
	ID:             whereHelperstring{field: "\"workspace_projects\".\"id\""},
	WorkspaceID:    whereHelperstring{field: "\"workspace_projects\".\"workspace_id\""},
	Slug:           whereHelperstring{field: "\"workspace_projects\".\"slug\""},
	Name:           whereHelperstring{field: "\"workspace_projects\".\"name\""},
	Description:    whereHelperstring{field: "\"workspace_projects\".\"description\""},
	State:          whereHelperstring{field: "\"workspace_projects\".\"state\""},
	LeadAccountID:  whereHelpernull_String{field: "\"workspace_projects\".\"lead_account_id\""},
	TargetOn:       whereHelpernull_Time{field: "\"workspace_projects\".\"target_on\""},
	ArchivedAt:     whereHelpernull_Time{field: "\"workspace_projects\".\"archived_at\""},
	CreatedAt:      whereHelpertime_Time{field: "\"workspace_projects\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"workspace_projects\".\"updated_at\""},
	SearchDocument: whereHelpernull_String{field: "\"workspace_projects\".\"search_document\""},
}

// WorkspaceProjectRels is where relationship names are stored.
var WorkspaceProjectRels = struct {
	LeadAccount                          string
	Workspace                            string
	ProjectWorkspaceProjectStatusUpdates string
}{
	LeadAccount:                          "LeadAccount",
	Workspace:                            "Workspace",
	ProjectWorkspaceProjectStatusUpdates: "ProjectWorkspaceProjectStatusUpdates",
}

// workspaceProjectR is where relationships are stored.
type workspaceProjectR struct {
	LeadAccount                          *Account                          `boil:"LeadAccount" json:"LeadAccount" toml:"LeadAccount" yaml:"LeadAccount"`
	Workspace                            *Workspace                        `boil:"Workspace" json:"Workspace" toml:"Workspace" yaml:"Workspace"`
	ProjectWorkspaceProjectStatusUpdates WorkspaceProjectStatusUpdateSlice `boil:"ProjectWorkspaceProjectStatusUpdates" json:"ProjectWorkspaceProjectStatusUpdates" toml:"ProjectWorkspaceProjectStatusUpdates" yaml:"ProjectWorkspaceProjectStatusUpdates"`
}

// NewStruct creates a new relationship struct
func (*workspaceProjectR) NewStruct() *workspaceProjectR {
	return &workspaceProjectR{}
}

func (o *WorkspaceProject) GetLeadAccount() *Account {
	if o == nil {
		return nil
	}

	return o.R.GetLeadAccount()
}

func (r *workspaceProjectR) GetLeadAccount() *Account {
	if r == nil {
		return nil
	}

	return r.LeadAccount
}

func (o *WorkspaceProject) GetWorkspace() *Workspace {
	if o == nil {
		return nil
	}

	return o.R.GetWorkspace()
}

func (r *workspaceProjectR) GetWorkspace() *Workspace {
	if r == nil {
		return nil
	}

	return r.Workspace
}

func (o *WorkspaceProject) GetProjectWorkspaceProjectStatusUpdates() WorkspaceProjectStatusUpdateSlice {
	if o == nil {
		return nil
	}

	return o.R.GetProjectWorkspaceProjectStatusUpdates()
}

func (r *workspaceProjectR) GetProjectWorkspaceProjectStatusUpdates() WorkspaceProjectStatusUpdateSlice {
	if r == nil {
		return nil
	}

	return r.ProjectWorkspaceProjectStatusUpdates
}

// workspaceProjectL is where Load methods for each relationship are stored.
type workspaceProjectL struct{}

var (
	workspaceProjectAllColumns            = []string{"id", "workspace_id", "slug", "name", "description", "state", "lead_account_id", "target_on", "archived_at", "created_at", "updated_at", "search_document"}
	workspaceProjectColumnsWithoutDefault = []string{"workspace_id", "slug", "name"}
	workspaceProjectColumnsWithDefault    = []string{"id", "description", "state", "lead_account_id", "target_on", "archived_at", "created_at", "updated_at", "search_document"}
	workspaceProjectPrimaryKeyColumns     = []string{"id"}
	workspaceProjectGeneratedColumns      = []string{"search_document"}
)

type (
	// WorkspaceProjectSlice is an alias for a slice of pointers to WorkspaceProject.
	// This should almost always be used instead of []WorkspaceProject.
	WorkspaceProjectSlice []*WorkspaceProject
	// WorkspaceProjectHook is the signature for custom WorkspaceProject hook methods
	WorkspaceProjectHook func(context.Context, boil.ContextExecutor, *WorkspaceProject) error

	workspaceProjectQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workspaceProjectType                 = reflect.TypeOf(&WorkspaceProject{})
	workspaceProjectMapping              = queries.MakeStructMapping(workspaceProjectType)
	workspaceProjectPrimaryKeyMapping, _ = queries.BindMapping(workspaceProjectType, workspaceProjectMapping, workspaceProjectPrimaryKeyColumns)
	workspaceProjectInsertCacheMut       sync.RWMutex
	workspaceProjectInsertCache          = make(map[string]insertCache)
	workspaceProjectUpdateCacheMut       sync.RWMutex
	workspaceProjectUpdateCache          = make(map[string]updateCache)
	workspaceProjectUpsertCacheMut       sync.RWMutex
	workspaceProjectUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workspaceProjectAfterSelectMu sync.Mutex
var workspaceProjectAfterSelectHooks []WorkspaceProjectHook

var workspaceProjectBeforeInsertMu sync.Mutex
var workspaceProjectBeforeInsertHooks []WorkspaceProjectHook
var workspaceProjectAfterInsertMu sync.Mutex
var workspaceProjectAfterInsertHooks []WorkspaceProjectHook

var workspaceProjectBeforeUpdateMu sync.Mutex
var workspaceProjectBeforeUpdateHooks []WorkspaceProjectHook
var workspaceProjectAfterUpdateMu sync.Mutex
var workspaceProjectAfterUpdateHooks []WorkspaceProjectHook

var workspaceProjectBeforeDeleteMu sync.Mutex
var workspaceProjectBeforeDeleteHooks []WorkspaceProjectHook
var workspaceProjectAfterDeleteMu sync.Mutex
var workspaceProjectAfterDeleteHooks []WorkspaceProjectHook

var workspaceProjectBeforeUpsertMu sync.Mutex
var workspaceProjectBeforeUpsertHooks []WorkspaceProjectHook
var workspaceProjectAfterUpsertMu sync.Mutex
var workspaceProjectAfterUpsertHooks []WorkspaceProjectHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkspaceProject) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceProjectAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkspaceProject) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceProjectBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkspaceProject) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceProjectAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkspaceProject) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceProjectBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkspaceProject) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceProjectAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkspaceProject) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceProjectBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkspaceProject) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceProjectAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkspaceProject) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceProjectBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkspaceProject) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceProjectAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkspaceProjectHook registers your hook function for all future operations.
func AddWorkspaceProjectHook(hookPoint boil.HookPoint, workspaceProjectHook WorkspaceProjectHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workspaceProjectAfterSelectMu.Lock()
		workspaceProjectAfterSelectHooks = append(workspaceProjectAfterSelectHooks, workspaceProjectHook)
		workspaceProjectAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workspaceProjectBeforeInsertMu.Lock()
		workspaceProjectBeforeInsertHooks = append(workspaceProjectBeforeInsertHooks, workspaceProjectHook)
		workspaceProjectBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workspaceProjectAfterInsertMu.Lock()
		workspaceProjectAfterInsertHooks = append(workspaceProjectAfterInsertHooks, workspaceProjectHook)
		workspaceProjectAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workspaceProjectBeforeUpdateMu.Lock()
		workspaceProjectBeforeUpdateHooks = append(workspaceProjectBeforeUpdateHooks, workspaceProjectHook)
		workspaceProjectBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workspaceProjectAfterUpdateMu.Lock()
		workspaceProjectAfterUpdateHooks = append(workspaceProjectAfterUpdateHooks, workspaceProjectHook)
		workspaceProjectAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workspaceProjectBeforeDeleteMu.Lock()
		workspaceProjectBeforeDeleteHooks = append(workspaceProjectBeforeDeleteHooks, workspaceProjectHook)
		workspaceProjectBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workspaceProjectAfterDeleteMu.Lock()
		workspaceProjectAfterDeleteHooks = append(workspaceProjectAfterDeleteHooks, workspaceProjectHook)
		workspaceProjectAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workspaceProjectBeforeUpsertMu.Lock()
		workspaceProjectBeforeUpsertHooks = append(workspaceProjectBeforeUpsertHooks, workspaceProjectHook)
		workspaceProjectBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workspaceProjectAfterUpsertMu.Lock()
		workspaceProjectAfterUpsertHooks = append(workspaceProjectAfterUpsertHooks, workspaceProjectHook)
		workspaceProjectAfterUpsertMu.Unlock()
	}
}

// One returns a single workspaceProject record from the query.
func (q workspaceProjectQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkspaceProject, error) {
	o := &WorkspaceProject{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for workspace_projects")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkspaceProject records from the query.
func (q workspaceProjectQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkspaceProjectSlice, error) {
	var o []*WorkspaceProject

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to WorkspaceProject slice")
	}

	if len(workspaceProjectAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkspaceProject records in the query.
func (q workspaceProjectQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count workspace_projects rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workspaceProjectQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if workspace_projects exists")
	}

	return count > 0, nil
}

// LeadAccount pointed to by the foreign key.
func (o *WorkspaceProject) LeadAccount(mods ...qm.QueryMod) accountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.LeadAccountID),
	}

	queryMods = append(queryMods, mods...)

	return Accounts(queryMods...)
}

// Workspace pointed to by the foreign key.
func (o *WorkspaceProject) Workspace(mods ...qm.QueryMod) workspaceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorkspaceID),
	}

	queryMods = append(queryMods, mods...)

	return Workspaces(queryMods...)
}

// ProjectWorkspaceProjectStatusUpdates retrieves all the workspace_project_status_update's WorkspaceProjectStatusUpdates with an executor via project_id column.
func (o *WorkspaceProject) ProjectWorkspaceProjectStatusUpdates(mods ...qm.QueryMod) workspaceProjectStatusUpdateQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"workspace_project_status_updates\".\"project_id\"=?", o.ID),
	)

	return WorkspaceProjectStatusUpdates(queryMods...)
}

// LoadLeadAccount allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workspaceProjectL) LoadLeadAccount(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceProject any, mods queries.Applicator) error {
	var slice []*WorkspaceProject
	var object *WorkspaceProject

	if singular {
		var ok bool
		object, ok = maybeWorkspaceProject.(*WorkspaceProject)
		if !ok {
			object = new(WorkspaceProject)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceProject)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceProject))
			}
		}
	} else {
		s, ok := maybeWorkspaceProject.(*[]*WorkspaceProject)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceProject)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceProject))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceProjectR{}
		}
		if !queries.IsNil(object.LeadAccountID) {
			args[object.LeadAccountID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceProjectR{}
			}

			if !queries.IsNil(obj.LeadAccountID) {
				args[obj.LeadAccountID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`accounts`),
		qm.WhereIn(`accounts.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Account")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for accounts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for accounts")
	}

	if len(accountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.LeadAccount = foreign
		if foreign.R == nil {
			foreign.R = &accountR{}
		}
		foreign.R.LeadAccountWorkspaceProjects = append(foreign.R.LeadAccountWorkspaceProjects, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.LeadAccountID, foreign.ID) {
				local.R.LeadAccount = foreign
				if foreign.R == nil {
					foreign.R = &accountR{}
				}
				foreign.R.LeadAccountWorkspaceProjects = append(foreign.R.LeadAccountWorkspaceProjects, local)
				break
			}
		}
	}

	return nil
}

// LoadWorkspace allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workspaceProjectL) LoadWorkspace(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceProject any, mods queries.Applicator) error {
	var slice []*WorkspaceProject
	var object *WorkspaceProject

	if singular {
		var ok bool
		object, ok = maybeWorkspaceProject.(*WorkspaceProject)
		if !ok {
			object = new(WorkspaceProject)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceProject)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceProject))
			}
		}
	} else {
		s, ok := maybeWorkspaceProject.(*[]*WorkspaceProject)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceProject)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceProject))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceProjectR{}
		}
		args[object.WorkspaceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceProjectR{}
			}

			args[obj.WorkspaceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspaces`),
		qm.WhereIn(`workspaces.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Workspace")
	}

	var resultSlice []*Workspace
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Workspace")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workspaces")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspaces")
	}

	if len(workspaceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Workspace = foreign
		if foreign.R == nil {
			foreign.R = &workspaceR{}
		}
		foreign.R.WorkspaceProjects = append(foreign.R.WorkspaceProjects, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkspaceID == foreign.ID {
				local.R.Workspace = foreign
				if foreign.R == nil {
					foreign.R = &workspaceR{}
				}
				foreign.R.WorkspaceProjects = append(foreign.R.WorkspaceProjects, local)
				break
			}
		}
	}

	return nil
}

// LoadProjectWorkspaceProjectStatusUpdates allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (workspaceProjectL) LoadProjectWorkspaceProjectStatusUpdates(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceProject any, mods queries.Applicator) error {
	var slice []*WorkspaceProject
	var object *WorkspaceProject

	if singular {
		var ok bool
		object, ok = maybeWorkspaceProject.(*WorkspaceProject)
		if !ok {
			object = new(WorkspaceProject)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceProject)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceProject))
			}
		}
	} else {
		s, ok := maybeWorkspaceProject.(*[]*WorkspaceProject)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceProject)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceProject))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceProjectR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceProjectR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspace_project_status_updates`),
		qm.WhereIn(`workspace_project_status_updates.project_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load workspace_project_status_updates")
	}

	var resultSlice []*WorkspaceProjectStatusUpdate
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice workspace_project_status_updates")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on workspace_project_status_updates")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspace_project_status_updates")
	}

	if len(workspaceProjectStatusUpdateAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ProjectWorkspaceProjectStatusUpdates = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &workspaceProjectStatusUpdateR{}
			}
			foreign.R.Project = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ProjectID {
				local.R.ProjectWorkspaceProjectStatusUpdates = append(local.R.ProjectWorkspaceProjectStatusUpdates, foreign)
				if foreign.R == nil {
					foreign.R = &workspaceProjectStatusUpdateR{}
				}
				foreign.R.Project = local
				break
			}
		}
	}

	return nil
}

// SetLeadAccount of the workspaceProject to the related item.
// Sets o.R.LeadAccount to related.
// Adds o to related.R.LeadAccountWorkspaceProjects.
func (o *WorkspaceProject) SetLeadAccount(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Account) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"workspace_projects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"lead_account_id"}),
		strmangle.WhereClause("\"", "\"", 2, workspaceProjectPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.LeadAccountID, related.ID)
	if o.R == nil {
		o.R = &workspaceProjectR{
			LeadAccount: related,
		}
	} else {
		o.R.LeadAccount = related
	}

	if related.R == nil {
		related.R = &accountR{
			LeadAccountWorkspaceProjects: WorkspaceProjectSlice{o},
		}
	} else {
		related.R.LeadAccountWorkspaceProjects = append(related.R.LeadAccountWorkspaceProjects, o)
	}

	return nil
}

// RemoveLeadAccount relationship.
// Sets o.R.LeadAccount to nil.
// Removes o from all passed in related items' relationships struct.
func (o *WorkspaceProject) RemoveLeadAccount(ctx context.Context, exec boil.ContextExecutor, related *Account) error {
	var err error

	queries.SetScanner(&o.LeadAccountID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("lead_account_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.LeadAccount = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.LeadAccountWorkspaceProjects {
		if queries.Equal(o.LeadAccountID, ri.LeadAccountID) {
			continue
		}

		ln := len(related.R.LeadAccountWorkspaceProjects)
		if ln > 1 && i < ln-1 {
			related.R.LeadAccountWorkspaceProjects[i] = related.R.LeadAccountWorkspaceProjects[ln-1]
		}
		related.R.LeadAccountWorkspaceProjects = related.R.LeadAccountWorkspaceProjects[:ln-1]
		break
	}
	return nil
}

// SetWorkspace of the workspaceProject to the related item.
// Sets o.R.Workspace to related.
// Adds o to related.R.WorkspaceProjects.
func (o *WorkspaceProject) SetWorkspace(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Workspace) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"workspace_projects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"workspace_id"}),
		strmangle.WhereClause("\"", "\"", 2, workspaceProjectPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkspaceID = related.ID
	if o.R == nil {
		o.R = &workspaceProjectR{
			Workspace: related,
		}
	} else {
		o.R.Workspace = related
	}

	if related.R == nil {
		related.R = &workspaceR{
			WorkspaceProjects: WorkspaceProjectSlice{o},
		}
	} else {
		related.R.WorkspaceProjects = append(related.R.WorkspaceProjects, o)
	}

	return nil
}

// AddProjectWorkspaceProjectStatusUpdates adds the given related objects to the existing relationships
// of the workspace_project, optionally inserting them as new records.
// Appends related to o.R.ProjectWorkspaceProjectStatusUpdates.
// Sets related.R.Project appropriately.
func (o *WorkspaceProject) AddProjectWorkspaceProjectStatusUpdates(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WorkspaceProjectStatusUpdate) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ProjectID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"workspace_project_status_updates\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"project_id"}),
				strmangle.WhereClause("\"", "\"", 2, workspaceProjectStatusUpdatePrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ProjectID = o.ID
		}
	}

	if o.R == nil {
		o.R = &workspaceProjectR{
			ProjectWorkspaceProjectStatusUpdates: related,
		}
	} else {
		o.R.ProjectWorkspaceProjectStatusUpdates = append(o.R.ProjectWorkspaceProjectStatusUpdates, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &workspaceProjectStatusUpdateR{
				Project: o,
			}
		} else {
			rel.R.Project = o
		}
	}
	return nil
}

// WorkspaceProjects retrieves all the records using an executor.
func WorkspaceProjects(mods ...qm.QueryMod) workspaceProjectQuery {
	mods = append(mods, qm.From("\"workspace_projects\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"workspace_projects\".*"})
	}

	return workspaceProjectQuery{q}
}

// FindWorkspaceProject retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkspaceProject(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WorkspaceProject, error) {
	workspaceProjectObj := &WorkspaceProject{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"workspace_projects\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workspaceProjectObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from workspace_projects")
	}

	if err = workspaceProjectObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workspaceProjectObj, err
	}

	return workspaceProjectObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkspaceProject) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_projects provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceProjectColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workspaceProjectInsertCacheMut.RLock()
	cache, cached := workspaceProjectInsertCache[key]
	workspaceProjectInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workspaceProjectAllColumns,
			workspaceProjectColumnsWithDefault,
			workspaceProjectColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, workspaceProjectGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(workspaceProjectType, workspaceProjectMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workspaceProjectType, workspaceProjectMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"workspace_projects\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"workspace_projects\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into workspace_projects")
	}

	if !cached {
		workspaceProjectInsertCacheMut.Lock()
		workspaceProjectInsertCache[key] = cache
		workspaceProjectInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkspaceProject.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkspaceProject) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workspaceProjectUpdateCacheMut.RLock()
	cache, cached := workspaceProjectUpdateCache[key]
	workspaceProjectUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workspaceProjectAllColumns,
			workspaceProjectPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, workspaceProjectGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update workspace_projects, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"workspace_projects\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workspaceProjectPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workspaceProjectType, workspaceProjectMapping, append(wl, workspaceProjectPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update workspace_projects row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for workspace_projects")
	}

	if !cached {
		workspaceProjectUpdateCacheMut.Lock()
		workspaceProjectUpdateCache[key] = cache
		workspaceProjectUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workspaceProjectQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for workspace_projects")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for workspace_projects")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkspaceProjectSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceProjectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"workspace_projects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workspaceProjectPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in workspaceProject slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all workspaceProject")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkspaceProject) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_projects provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceProjectColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workspaceProjectUpsertCacheMut.RLock()
	cache, cached := workspaceProjectUpsertCache[key]
	workspaceProjectUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workspaceProjectAllColumns,
			workspaceProjectColumnsWithDefault,
			workspaceProjectColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workspaceProjectAllColumns,
			workspaceProjectPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, workspaceProjectGeneratedColumns)
		update = strmangle.SetComplement(update, workspaceProjectGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert workspace_projects, could not build update column list")
		}

		ret := strmangle.SetComplement(workspaceProjectAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(workspaceProjectPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert workspace_projects, could not build conflict column list")
			}

			conflict = make([]string, len(workspaceProjectPrimaryKeyColumns))
			copy(conflict, workspaceProjectPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"workspace_projects\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(workspaceProjectType, workspaceProjectMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workspaceProjectType, workspaceProjectMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert workspace_projects")
	}

	if !cached {
		workspaceProjectUpsertCacheMut.Lock()
		workspaceProjectUpsertCache[key] = cache
		workspaceProjectUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkspaceProject record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkspaceProject) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no WorkspaceProject provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workspaceProjectPrimaryKeyMapping)
	sql := "DELETE FROM \"workspace_projects\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from workspace_projects")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for workspace_projects")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workspaceProjectQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no workspaceProjectQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspace_projects")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_projects")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkspaceProjectSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workspaceProjectBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceProjectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"workspace_projects\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceProjectPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspaceProject slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_projects")
	}

	if len(workspaceProjectAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkspaceProject) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkspaceProject(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkspaceProjectSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkspaceProjectSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceProjectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"workspace_projects\".* FROM \"workspace_projects\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceProjectPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in WorkspaceProjectSlice")
	}

	*o = slice

	return nil
}

// WorkspaceProjectExists checks if the WorkspaceProject row exists.
func WorkspaceProjectExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"workspace_projects\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if workspace_projects exists")
	}

	return exists, nil
}

// Exists checks if the WorkspaceProject row exists.
func (o *WorkspaceProject) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkspaceProjectExists(ctx, exec, o.ID)
}
