// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WorkspaceDirectoryConnection is an object representing the database table.
type WorkspaceDirectoryConnection struct {
	WorkspaceID string    `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	TokenHash   []byte    `boil:"token_hash" json:"token_hash" toml:"token_hash" yaml:"token_hash"`
	Enabled     bool      `boil:"enabled" json:"enabled" toml:"enabled" yaml:"enabled"`
	OnUnknown   string    `boil:"on_unknown" json:"on_unknown" toml:"on_unknown" yaml:"on_unknown"`
	OnAbsent    string    `boil:"on_absent" json:"on_absent" toml:"on_absent" yaml:"on_absent"`
	AdminGroup  string    `boil:"admin_group" json:"admin_group" toml:"admin_group" yaml:"admin_group"`
	LastSyncAt  null.Time `boil:"last_sync_at" json:"last_sync_at,omitempty" toml:"last_sync_at" yaml:"last_sync_at,omitempty"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *workspaceDirectoryConnectionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workspaceDirectoryConnectionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkspaceDirectoryConnectionColumns = struct {
	WorkspaceID string
	TokenHash   string
	Enabled     string
	OnUnknown   string
	OnAbsent    string
	AdminGroup  string
	LastSyncAt  string
	CreatedAt   string
	UpdatedAt   string
}{
	WorkspaceID: "workspace_id",
	TokenHash:   "token_hash",
	Enabled:     "enabled",
	OnUnknown:   "on_unknown",
	OnAbsent:    "on_absent",
	AdminGroup:  "admin_group",
	LastSyncAt:  "last_sync_at",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

var WorkspaceDirectoryConnectionTableColumns = struct {
	WorkspaceID string
	TokenHash   string
	Enabled     string
	OnUnknown   string
	OnAbsent    string
	AdminGroup  string
	LastSyncAt  string
	CreatedAt   string
	UpdatedAt   string
}{
	WorkspaceID: "workspace_directory_connections.workspace_id",
	TokenHash:   "workspace_directory_connections.token_hash",
	Enabled:     "workspace_directory_connections.enabled",
	OnUnknown:   "workspace_directory_connections.on_unknown",
	OnAbsent:    "workspace_directory_connections.on_absent",
	AdminGroup:  "workspace_directory_connections.admin_group",
	LastSyncAt:  "workspace_directory_connections.last_sync_at",
	CreatedAt:   "workspace_directory_connections.created_at",
	UpdatedAt:   "workspace_directory_connections.updated_at",
}

// Generated where

var WorkspaceDirectoryConnectionWhere = struct {
	WorkspaceID whereHelperstring
	TokenHash   whereHelper__byte
	Enabled     whereHelperbool
	OnUnknown   whereHelperstring
	OnAbsent    whereHelperstring
	AdminGroup  whereHelperstring
	LastSyncAt  whereHelpernull_Time
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
}{
	WorkspaceID: whereHelperstring{field: "\"workspace_directory_connections\".\"workspace_id\""},
	TokenHash:   whereHelper__byte{field: "\"workspace_directory_connections\".\"token_hash\""},
	Enabled:     whereHelperbool{field: "\"workspace_directory_connections\".\"enabled\""},
	OnUnknown:   whereHelperstring{field: "\"workspace_directory_connections\".\"on_unknown\""},
	OnAbsent:    whereHelperstring{field: "\"workspace_directory_connections\".\"on_absent\""},
	AdminGroup:  whereHelperstring{field: "\"workspace_directory_connections\".\"admin_group\""},
	LastSyncAt:  whereHelpernull_Time{field: "\"workspace_directory_connections\".\"last_sync_at\""},
	CreatedAt:   whereHelpertime_Time{field: "\"workspace_directory_connections\".\"created_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"workspace_directory_connections\".\"updated_at\""},
}

// WorkspaceDirectoryConnectionRels is where relationship names are stored.
var WorkspaceDirectoryConnectionRels = struct {
	Workspace                string
	WorkspaceDirectoryGroups string
	WorkspaceDirectoryUsers  string
}{
	Workspace:                "Workspace",
	WorkspaceDirectoryGroups: "WorkspaceDirectoryGroups",
	WorkspaceDirectoryUsers:  "WorkspaceDirectoryUsers",
}

// workspaceDirectoryConnectionR is where relationships are stored.
type workspaceDirectoryConnectionR struct {
	Workspace                *Workspace          `boil:"Workspace" json:"Workspace" toml:"Workspace" yaml:"Workspace"`
	WorkspaceDirectoryGroups DirectoryGroupSlice `boil:"WorkspaceDirectoryGroups" json:"WorkspaceDirectoryGroups" toml:"WorkspaceDirectoryGroups" yaml:"WorkspaceDirectoryGroups"`
	WorkspaceDirectoryUsers  DirectoryUserSlice  `boil:"WorkspaceDirectoryUsers" json:"WorkspaceDirectoryUsers" toml:"WorkspaceDirectoryUsers" yaml:"WorkspaceDirectoryUsers"`
}

// NewStruct creates a new relationship struct
func (*workspaceDirectoryConnectionR) NewStruct() *workspaceDirectoryConnectionR {
	return &workspaceDirectoryConnectionR{}
}

func (o *WorkspaceDirectoryConnection) GetWorkspace() *Workspace {
	if o == nil {
		return nil
	}

	return o.R.GetWorkspace()
}

func (r *workspaceDirectoryConnectionR) GetWorkspace() *Workspace {
	if r == nil {
		return nil
	}

	return r.Workspace
}

func (o *WorkspaceDirectoryConnection) GetWorkspaceDirectoryGroups() DirectoryGroupSlice {
	if o == nil {
		return nil
	}

	return o.R.GetWorkspaceDirectoryGroups()
}

func (r *workspaceDirectoryConnectionR) GetWorkspaceDirectoryGroups() DirectoryGroupSlice {
	if r == nil {
		return nil
	}

	return r.WorkspaceDirectoryGroups
}

func (o *WorkspaceDirectoryConnection) GetWorkspaceDirectoryUsers() DirectoryUserSlice {
	if o == nil {
		return nil
	}

	return o.R.GetWorkspaceDirectoryUsers()
}

func (r *workspaceDirectoryConnectionR) GetWorkspaceDirectoryUsers() DirectoryUserSlice {
	if r == nil {
		return nil
	}

	return r.WorkspaceDirectoryUsers
}

// workspaceDirectoryConnectionL is where Load methods for each relationship are stored.
type workspaceDirectoryConnectionL struct{}

var (
	workspaceDirectoryConnectionAllColumns            = []string{"workspace_id", "token_hash", "enabled", "on_unknown", "on_absent", "admin_group", "last_sync_at", "created_at", "updated_at"}
	workspaceDirectoryConnectionColumnsWithoutDefault = []string{"workspace_id", "token_hash"}
	workspaceDirectoryConnectionColumnsWithDefault    = []string{"enabled", "on_unknown", "on_absent", "admin_group", "last_sync_at", "created_at", "updated_at"}
	workspaceDirectoryConnectionPrimaryKeyColumns     = []string{"workspace_id"}
	workspaceDirectoryConnectionGeneratedColumns      = []string{}
)

type (
	// WorkspaceDirectoryConnectionSlice is an alias for a slice of pointers to WorkspaceDirectoryConnection.
	// This should almost always be used instead of []WorkspaceDirectoryConnection.
	WorkspaceDirectoryConnectionSlice []*WorkspaceDirectoryConnection
	// WorkspaceDirectoryConnectionHook is the signature for custom WorkspaceDirectoryConnection hook methods
	WorkspaceDirectoryConnectionHook func(context.Context, boil.ContextExecutor, *WorkspaceDirectoryConnection) error

	workspaceDirectoryConnectionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workspaceDirectoryConnectionType                 = reflect.TypeOf(&WorkspaceDirectoryConnection{})
	workspaceDirectoryConnectionMapping              = queries.MakeStructMapping(workspaceDirectoryConnectionType)
	workspaceDirectoryConnectionPrimaryKeyMapping, _ = queries.BindMapping(workspaceDirectoryConnectionType, workspaceDirectoryConnectionMapping, workspaceDirectoryConnectionPrimaryKeyColumns)
	workspaceDirectoryConnectionInsertCacheMut       sync.RWMutex
	workspaceDirectoryConnectionInsertCache          = make(map[string]insertCache)
	workspaceDirectoryConnectionUpdateCacheMut       sync.RWMutex
	workspaceDirectoryConnectionUpdateCache          = make(map[string]updateCache)
	workspaceDirectoryConnectionUpsertCacheMut       sync.RWMutex
	workspaceDirectoryConnectionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workspaceDirectoryConnectionAfterSelectMu sync.Mutex
var workspaceDirectoryConnectionAfterSelectHooks []WorkspaceDirectoryConnectionHook

var workspaceDirectoryConnectionBeforeInsertMu sync.Mutex
var workspaceDirectoryConnectionBeforeInsertHooks []WorkspaceDirectoryConnectionHook
var workspaceDirectoryConnectionAfterInsertMu sync.Mutex
var workspaceDirectoryConnectionAfterInsertHooks []WorkspaceDirectoryConnectionHook

var workspaceDirectoryConnectionBeforeUpdateMu sync.Mutex
var workspaceDirectoryConnectionBeforeUpdateHooks []WorkspaceDirectoryConnectionHook
var workspaceDirectoryConnectionAfterUpdateMu sync.Mutex
var workspaceDirectoryConnectionAfterUpdateHooks []WorkspaceDirectoryConnectionHook

var workspaceDirectoryConnectionBeforeDeleteMu sync.Mutex
var workspaceDirectoryConnectionBeforeDeleteHooks []WorkspaceDirectoryConnectionHook
var workspaceDirectoryConnectionAfterDeleteMu sync.Mutex
var workspaceDirectoryConnectionAfterDeleteHooks []WorkspaceDirectoryConnectionHook

var workspaceDirectoryConnectionBeforeUpsertMu sync.Mutex
var workspaceDirectoryConnectionBeforeUpsertHooks []WorkspaceDirectoryConnectionHook
var workspaceDirectoryConnectionAfterUpsertMu sync.Mutex
var workspaceDirectoryConnectionAfterUpsertHooks []WorkspaceDirectoryConnectionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *WorkspaceDirectoryConnection) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceDirectoryConnectionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *WorkspaceDirectoryConnection) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceDirectoryConnectionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *WorkspaceDirectoryConnection) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceDirectoryConnectionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *WorkspaceDirectoryConnection) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceDirectoryConnectionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *WorkspaceDirectoryConnection) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceDirectoryConnectionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *WorkspaceDirectoryConnection) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceDirectoryConnectionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *WorkspaceDirectoryConnection) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceDirectoryConnectionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *WorkspaceDirectoryConnection) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceDirectoryConnectionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *WorkspaceDirectoryConnection) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workspaceDirectoryConnectionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkspaceDirectoryConnectionHook registers your hook function for all future operations.
func AddWorkspaceDirectoryConnectionHook(hookPoint boil.HookPoint, workspaceDirectoryConnectionHook WorkspaceDirectoryConnectionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		workspaceDirectoryConnectionAfterSelectMu.Lock()
		workspaceDirectoryConnectionAfterSelectHooks = append(workspaceDirectoryConnectionAfterSelectHooks, workspaceDirectoryConnectionHook)
		workspaceDirectoryConnectionAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		workspaceDirectoryConnectionBeforeInsertMu.Lock()
		workspaceDirectoryConnectionBeforeInsertHooks = append(workspaceDirectoryConnectionBeforeInsertHooks, workspaceDirectoryConnectionHook)
		workspaceDirectoryConnectionBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		workspaceDirectoryConnectionAfterInsertMu.Lock()
		workspaceDirectoryConnectionAfterInsertHooks = append(workspaceDirectoryConnectionAfterInsertHooks, workspaceDirectoryConnectionHook)
		workspaceDirectoryConnectionAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		workspaceDirectoryConnectionBeforeUpdateMu.Lock()
		workspaceDirectoryConnectionBeforeUpdateHooks = append(workspaceDirectoryConnectionBeforeUpdateHooks, workspaceDirectoryConnectionHook)
		workspaceDirectoryConnectionBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		workspaceDirectoryConnectionAfterUpdateMu.Lock()
		workspaceDirectoryConnectionAfterUpdateHooks = append(workspaceDirectoryConnectionAfterUpdateHooks, workspaceDirectoryConnectionHook)
		workspaceDirectoryConnectionAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		workspaceDirectoryConnectionBeforeDeleteMu.Lock()
		workspaceDirectoryConnectionBeforeDeleteHooks = append(workspaceDirectoryConnectionBeforeDeleteHooks, workspaceDirectoryConnectionHook)
		workspaceDirectoryConnectionBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		workspaceDirectoryConnectionAfterDeleteMu.Lock()
		workspaceDirectoryConnectionAfterDeleteHooks = append(workspaceDirectoryConnectionAfterDeleteHooks, workspaceDirectoryConnectionHook)
		workspaceDirectoryConnectionAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		workspaceDirectoryConnectionBeforeUpsertMu.Lock()
		workspaceDirectoryConnectionBeforeUpsertHooks = append(workspaceDirectoryConnectionBeforeUpsertHooks, workspaceDirectoryConnectionHook)
		workspaceDirectoryConnectionBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		workspaceDirectoryConnectionAfterUpsertMu.Lock()
		workspaceDirectoryConnectionAfterUpsertHooks = append(workspaceDirectoryConnectionAfterUpsertHooks, workspaceDirectoryConnectionHook)
		workspaceDirectoryConnectionAfterUpsertMu.Unlock()
	}
}

// One returns a single workspaceDirectoryConnection record from the query.
func (q workspaceDirectoryConnectionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WorkspaceDirectoryConnection, error) {
	o := &WorkspaceDirectoryConnection{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for workspace_directory_connections")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all WorkspaceDirectoryConnection records from the query.
func (q workspaceDirectoryConnectionQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkspaceDirectoryConnectionSlice, error) {
	var o []*WorkspaceDirectoryConnection

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to WorkspaceDirectoryConnection slice")
	}

	if len(workspaceDirectoryConnectionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all WorkspaceDirectoryConnection records in the query.
func (q workspaceDirectoryConnectionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count workspace_directory_connections rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workspaceDirectoryConnectionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if workspace_directory_connections exists")
	}

	return count > 0, nil
}

// Workspace pointed to by the foreign key.
func (o *WorkspaceDirectoryConnection) Workspace(mods ...qm.QueryMod) workspaceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorkspaceID),
	}

	queryMods = append(queryMods, mods...)

	return Workspaces(queryMods...)
}

// WorkspaceDirectoryGroups retrieves all the directory_group's DirectoryGroups with an executor via workspace_id column.
func (o *WorkspaceDirectoryConnection) WorkspaceDirectoryGroups(mods ...qm.QueryMod) directoryGroupQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"directory_groups\".\"workspace_id\"=?", o.WorkspaceID),
	)

	return DirectoryGroups(queryMods...)
}

// WorkspaceDirectoryUsers retrieves all the directory_user's DirectoryUsers with an executor via workspace_id column.
func (o *WorkspaceDirectoryConnection) WorkspaceDirectoryUsers(mods ...qm.QueryMod) directoryUserQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"directory_users\".\"workspace_id\"=?", o.WorkspaceID),
	)

	return DirectoryUsers(queryMods...)
}

// LoadWorkspace allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workspaceDirectoryConnectionL) LoadWorkspace(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceDirectoryConnection any, mods queries.Applicator) error {
	var slice []*WorkspaceDirectoryConnection
	var object *WorkspaceDirectoryConnection

	if singular {
		var ok bool
		object, ok = maybeWorkspaceDirectoryConnection.(*WorkspaceDirectoryConnection)
		if !ok {
			object = new(WorkspaceDirectoryConnection)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceDirectoryConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceDirectoryConnection))
			}
		}
	} else {
		s, ok := maybeWorkspaceDirectoryConnection.(*[]*WorkspaceDirectoryConnection)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceDirectoryConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceDirectoryConnection))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceDirectoryConnectionR{}
		}
		args[object.WorkspaceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceDirectoryConnectionR{}
			}

			args[obj.WorkspaceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspaces`),
		qm.WhereIn(`workspaces.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Workspace")
	}

	var resultSlice []*Workspace
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Workspace")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workspaces")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspaces")
	}

	if len(workspaceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Workspace = foreign
		if foreign.R == nil {
			foreign.R = &workspaceR{}
		}
		foreign.R.WorkspaceDirectoryConnection = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkspaceID == foreign.ID {
				local.R.Workspace = foreign
				if foreign.R == nil {
					foreign.R = &workspaceR{}
				}
				foreign.R.WorkspaceDirectoryConnection = local
				break
			}
		}
	}

	return nil
}

// LoadWorkspaceDirectoryGroups allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (workspaceDirectoryConnectionL) LoadWorkspaceDirectoryGroups(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceDirectoryConnection any, mods queries.Applicator) error {
	var slice []*WorkspaceDirectoryConnection
	var object *WorkspaceDirectoryConnection

	if singular {
		var ok bool
		object, ok = maybeWorkspaceDirectoryConnection.(*WorkspaceDirectoryConnection)
		if !ok {
			object = new(WorkspaceDirectoryConnection)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceDirectoryConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceDirectoryConnection))
			}
		}
	} else {
		s, ok := maybeWorkspaceDirectoryConnection.(*[]*WorkspaceDirectoryConnection)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceDirectoryConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceDirectoryConnection))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceDirectoryConnectionR{}
		}
		args[object.WorkspaceID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceDirectoryConnectionR{}
			}
			args[obj.WorkspaceID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`directory_groups`),
		qm.WhereIn(`directory_groups.workspace_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load directory_groups")
	}

	var resultSlice []*DirectoryGroup
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice directory_groups")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on directory_groups")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for directory_groups")
	}

	if len(directoryGroupAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.WorkspaceDirectoryGroups = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &directoryGroupR{}
			}
			foreign.R.Workspace = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.WorkspaceID == foreign.WorkspaceID {
				local.R.WorkspaceDirectoryGroups = append(local.R.WorkspaceDirectoryGroups, foreign)
				if foreign.R == nil {
					foreign.R = &directoryGroupR{}
				}
				foreign.R.Workspace = local
				break
			}
		}
	}

	return nil
}

// LoadWorkspaceDirectoryUsers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (workspaceDirectoryConnectionL) LoadWorkspaceDirectoryUsers(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWorkspaceDirectoryConnection any, mods queries.Applicator) error {
	var slice []*WorkspaceDirectoryConnection
	var object *WorkspaceDirectoryConnection

	if singular {
		var ok bool
		object, ok = maybeWorkspaceDirectoryConnection.(*WorkspaceDirectoryConnection)
		if !ok {
			object = new(WorkspaceDirectoryConnection)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWorkspaceDirectoryConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWorkspaceDirectoryConnection))
			}
		}
	} else {
		s, ok := maybeWorkspaceDirectoryConnection.(*[]*WorkspaceDirectoryConnection)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWorkspaceDirectoryConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWorkspaceDirectoryConnection))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &workspaceDirectoryConnectionR{}
		}
		args[object.WorkspaceID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workspaceDirectoryConnectionR{}
			}
			args[obj.WorkspaceID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`directory_users`),
		qm.WhereIn(`directory_users.workspace_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load directory_users")
	}

	var resultSlice []*DirectoryUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice directory_users")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on directory_users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for directory_users")
	}

	if len(directoryUserAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.WorkspaceDirectoryUsers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &directoryUserR{}
			}
			foreign.R.Workspace = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.WorkspaceID == foreign.WorkspaceID {
				local.R.WorkspaceDirectoryUsers = append(local.R.WorkspaceDirectoryUsers, foreign)
				if foreign.R == nil {
					foreign.R = &directoryUserR{}
				}
				foreign.R.Workspace = local
				break
			}
		}
	}

	return nil
}

// SetWorkspace of the workspaceDirectoryConnection to the related item.
// Sets o.R.Workspace to related.
// Adds o to related.R.WorkspaceDirectoryConnection.
func (o *WorkspaceDirectoryConnection) SetWorkspace(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Workspace) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"workspace_directory_connections\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"workspace_id"}),
		strmangle.WhereClause("\"", "\"", 2, workspaceDirectoryConnectionPrimaryKeyColumns),
	)
	values := []any{related.ID, o.WorkspaceID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkspaceID = related.ID
	if o.R == nil {
		o.R = &workspaceDirectoryConnectionR{
			Workspace: related,
		}
	} else {
		o.R.Workspace = related
	}

	if related.R == nil {
		related.R = &workspaceR{
			WorkspaceDirectoryConnection: o,
		}
	} else {
		related.R.WorkspaceDirectoryConnection = o
	}

	return nil
}

// AddWorkspaceDirectoryGroups adds the given related objects to the existing relationships
// of the workspace_directory_connection, optionally inserting them as new records.
// Appends related to o.R.WorkspaceDirectoryGroups.
// Sets related.R.Workspace appropriately.
func (o *WorkspaceDirectoryConnection) AddWorkspaceDirectoryGroups(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DirectoryGroup) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WorkspaceID = o.WorkspaceID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"directory_groups\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"workspace_id"}),
				strmangle.WhereClause("\"", "\"", 2, directoryGroupPrimaryKeyColumns),
			)
			values := []any{o.WorkspaceID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WorkspaceID = o.WorkspaceID
		}
	}

	if o.R == nil {
		o.R = &workspaceDirectoryConnectionR{
			WorkspaceDirectoryGroups: related,
		}
	} else {
		o.R.WorkspaceDirectoryGroups = append(o.R.WorkspaceDirectoryGroups, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &directoryGroupR{
				Workspace: o,
			}
		} else {
			rel.R.Workspace = o
		}
	}
	return nil
}

// AddWorkspaceDirectoryUsers adds the given related objects to the existing relationships
// of the workspace_directory_connection, optionally inserting them as new records.
// Appends related to o.R.WorkspaceDirectoryUsers.
// Sets related.R.Workspace appropriately.
func (o *WorkspaceDirectoryConnection) AddWorkspaceDirectoryUsers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DirectoryUser) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WorkspaceID = o.WorkspaceID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"directory_users\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"workspace_id"}),
				strmangle.WhereClause("\"", "\"", 2, directoryUserPrimaryKeyColumns),
			)
			values := []any{o.WorkspaceID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WorkspaceID = o.WorkspaceID
		}
	}

	if o.R == nil {
		o.R = &workspaceDirectoryConnectionR{
			WorkspaceDirectoryUsers: related,
		}
	} else {
		o.R.WorkspaceDirectoryUsers = append(o.R.WorkspaceDirectoryUsers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &directoryUserR{
				Workspace: o,
			}
		} else {
			rel.R.Workspace = o
		}
	}
	return nil
}

// WorkspaceDirectoryConnections retrieves all the records using an executor.
func WorkspaceDirectoryConnections(mods ...qm.QueryMod) workspaceDirectoryConnectionQuery {
	mods = append(mods, qm.From("\"workspace_directory_connections\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"workspace_directory_connections\".*"})
	}

	return workspaceDirectoryConnectionQuery{q}
}

// FindWorkspaceDirectoryConnection retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWorkspaceDirectoryConnection(ctx context.Context, exec boil.ContextExecutor, workspaceID string, selectCols ...string) (*WorkspaceDirectoryConnection, error) {
	workspaceDirectoryConnectionObj := &WorkspaceDirectoryConnection{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"workspace_directory_connections\" where \"workspace_id\"=$1", sel,
	)

	q := queries.Raw(query, workspaceID)

	err := q.Bind(ctx, exec, workspaceDirectoryConnectionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from workspace_directory_connections")
	}

	if err = workspaceDirectoryConnectionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workspaceDirectoryConnectionObj, err
	}

	return workspaceDirectoryConnectionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WorkspaceDirectoryConnection) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_directory_connections provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceDirectoryConnectionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workspaceDirectoryConnectionInsertCacheMut.RLock()
	cache, cached := workspaceDirectoryConnectionInsertCache[key]
	workspaceDirectoryConnectionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workspaceDirectoryConnectionAllColumns,
			workspaceDirectoryConnectionColumnsWithDefault,
			workspaceDirectoryConnectionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workspaceDirectoryConnectionType, workspaceDirectoryConnectionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workspaceDirectoryConnectionType, workspaceDirectoryConnectionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"workspace_directory_connections\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"workspace_directory_connections\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into workspace_directory_connections")
	}

	if !cached {
		workspaceDirectoryConnectionInsertCacheMut.Lock()
		workspaceDirectoryConnectionInsertCache[key] = cache
		workspaceDirectoryConnectionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the WorkspaceDirectoryConnection.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WorkspaceDirectoryConnection) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workspaceDirectoryConnectionUpdateCacheMut.RLock()
	cache, cached := workspaceDirectoryConnectionUpdateCache[key]
	workspaceDirectoryConnectionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workspaceDirectoryConnectionAllColumns,
			workspaceDirectoryConnectionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update workspace_directory_connections, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"workspace_directory_connections\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workspaceDirectoryConnectionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workspaceDirectoryConnectionType, workspaceDirectoryConnectionMapping, append(wl, workspaceDirectoryConnectionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update workspace_directory_connections row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for workspace_directory_connections")
	}

	if !cached {
		workspaceDirectoryConnectionUpdateCacheMut.Lock()
		workspaceDirectoryConnectionUpdateCache[key] = cache
		workspaceDirectoryConnectionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workspaceDirectoryConnectionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for workspace_directory_connections")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for workspace_directory_connections")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkspaceDirectoryConnectionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceDirectoryConnectionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"workspace_directory_connections\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workspaceDirectoryConnectionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in workspaceDirectoryConnection slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all workspaceDirectoryConnection")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WorkspaceDirectoryConnection) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no workspace_directory_connections provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workspaceDirectoryConnectionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workspaceDirectoryConnectionUpsertCacheMut.RLock()
	cache, cached := workspaceDirectoryConnectionUpsertCache[key]
	workspaceDirectoryConnectionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			workspaceDirectoryConnectionAllColumns,
			workspaceDirectoryConnectionColumnsWithDefault,
			workspaceDirectoryConnectionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			workspaceDirectoryConnectionAllColumns,
			workspaceDirectoryConnectionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert workspace_directory_connections, could not build update column list")
		}

		ret := strmangle.SetComplement(workspaceDirectoryConnectionAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(workspaceDirectoryConnectionPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert workspace_directory_connections, could not build conflict column list")
			}

			conflict = make([]string, len(workspaceDirectoryConnectionPrimaryKeyColumns))
			copy(conflict, workspaceDirectoryConnectionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"workspace_directory_connections\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(workspaceDirectoryConnectionType, workspaceDirectoryConnectionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workspaceDirectoryConnectionType, workspaceDirectoryConnectionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert workspace_directory_connections")
	}

	if !cached {
		workspaceDirectoryConnectionUpsertCacheMut.Lock()
		workspaceDirectoryConnectionUpsertCache[key] = cache
		workspaceDirectoryConnectionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single WorkspaceDirectoryConnection record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WorkspaceDirectoryConnection) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no WorkspaceDirectoryConnection provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workspaceDirectoryConnectionPrimaryKeyMapping)
	sql := "DELETE FROM \"workspace_directory_connections\" WHERE \"workspace_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from workspace_directory_connections")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for workspace_directory_connections")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workspaceDirectoryConnectionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no workspaceDirectoryConnectionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspace_directory_connections")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_directory_connections")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkspaceDirectoryConnectionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workspaceDirectoryConnectionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceDirectoryConnectionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"workspace_directory_connections\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceDirectoryConnectionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from workspaceDirectoryConnection slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for workspace_directory_connections")
	}

	if len(workspaceDirectoryConnectionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WorkspaceDirectoryConnection) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWorkspaceDirectoryConnection(ctx, exec, o.WorkspaceID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkspaceDirectoryConnectionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkspaceDirectoryConnectionSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workspaceDirectoryConnectionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"workspace_directory_connections\".* FROM \"workspace_directory_connections\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workspaceDirectoryConnectionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in WorkspaceDirectoryConnectionSlice")
	}

	*o = slice

	return nil
}

// WorkspaceDirectoryConnectionExists checks if the WorkspaceDirectoryConnection row exists.
func WorkspaceDirectoryConnectionExists(ctx context.Context, exec boil.ContextExecutor, workspaceID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"workspace_directory_connections\" where \"workspace_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, workspaceID)
	}
	row := exec.QueryRowContext(ctx, sql, workspaceID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if workspace_directory_connections exists")
	}

	return exists, nil
}

// Exists checks if the WorkspaceDirectoryConnection row exists.
func (o *WorkspaceDirectoryConnection) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WorkspaceDirectoryConnectionExists(ctx, exec, o.WorkspaceID)
}
