// Code generated by MockGen. DO NOT EDIT.
// Source: execution_services.go
//
// Generated by this command:
//
//	mockgen -source=execution_services.go -destination=executionservice/mock_execution_services.go -package=executionservice -mock_names=ExecutionServices=MockExecutionServices
//

// Package executionservice is a generated GoMock package.
package executionservice

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/usenorn/norn/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutionServices is a mock of ExecutionServices interface.
type MockExecutionServices struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionServicesMockRecorder
	isgomock struct{}
}

// MockExecutionServicesMockRecorder is the mock recorder for MockExecutionServices.
type MockExecutionServicesMockRecorder struct {
	mock *MockExecutionServices
}

// NewMockExecutionServices creates a new mock instance.
func NewMockExecutionServices(ctrl *gomock.Controller) *MockExecutionServices {
	mock := &MockExecutionServices{ctrl: ctrl}
	mock.recorder = &MockExecutionServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionServices) EXPECT() *MockExecutionServicesMockRecorder {
	return m.recorder
}

// ForExecution mocks base method.
func (m *MockExecutionServices) ForExecution(ctx context.Context, workspaceID uuid.UUID, executionID string) ([]entity.ExecutionService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForExecution", ctx, workspaceID, executionID)
	ret0, _ := ret[0].([]entity.ExecutionService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForExecution indicates an expected call of ForExecution.
func (mr *MockExecutionServicesMockRecorder) ForExecution(ctx, workspaceID, executionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForExecution", reflect.TypeOf((*MockExecutionServices)(nil).ForExecution), ctx, workspaceID, executionID)
}

// Reported mocks base method.
func (m *MockExecutionServices) Reported(ctx context.Context, runner entity.Runner, message entity.ChannelMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reported", ctx, runner, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reported indicates an expected call of Reported.
func (mr *MockExecutionServicesMockRecorder) Reported(ctx, runner, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reported", reflect.TypeOf((*MockExecutionServices)(nil).Reported), ctx, runner, message)
}
