// Code generated by MockGen. DO NOT EDIT.
// Source: workspaces.go
//
// Generated by this command:
//
//	mockgen -source=workspaces.go -destination=workspace/mock_workspaces.go -package=workspace -mock_names=Workspaces=MockWorkspaces
//

// Package workspace is a generated GoMock package.
package workspace

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/usenorn/norn/internal/entity"
	service "github.com/usenorn/norn/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkspaces is a mock of Workspaces interface.
type MockWorkspaces struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspacesMockRecorder
	isgomock struct{}
}

// MockWorkspacesMockRecorder is the mock recorder for MockWorkspaces.
type MockWorkspacesMockRecorder struct {
	mock *MockWorkspaces
}

// NewMockWorkspaces creates a new mock instance.
func NewMockWorkspaces(ctrl *gomock.Controller) *MockWorkspaces {
	mock := &MockWorkspaces{ctrl: ctrl}
	mock.recorder = &MockWorkspacesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaces) EXPECT() *MockWorkspacesMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockWorkspaces) AddMember(ctx context.Context, workspaceID, accountID uuid.UUID, role entity.MembershipRole) (entity.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, workspaceID, accountID, role)
	ret0, _ := ret[0].(entity.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember.
func (mr *MockWorkspacesMockRecorder) AddMember(ctx, workspaceID, accountID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockWorkspaces)(nil).AddMember), ctx, workspaceID, accountID, role)
}

// AuthPolicy mocks base method.
func (m *MockWorkspaces) AuthPolicy(ctx context.Context, workspaceID uuid.UUID) (entity.WorkspaceAuthPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthPolicy", ctx, workspaceID)
	ret0, _ := ret[0].(entity.WorkspaceAuthPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthPolicy indicates an expected call of AuthPolicy.
func (mr *MockWorkspacesMockRecorder) AuthPolicy(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthPolicy", reflect.TypeOf((*MockWorkspaces)(nil).AuthPolicy), ctx, workspaceID)
}

// ChangeMemberRole mocks base method.
func (m *MockWorkspaces) ChangeMemberRole(ctx context.Context, workspaceID, accountID uuid.UUID, role entity.MembershipRole) (entity.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeMemberRole", ctx, workspaceID, accountID, role)
	ret0, _ := ret[0].(entity.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeMemberRole indicates an expected call of ChangeMemberRole.
func (mr *MockWorkspacesMockRecorder) ChangeMemberRole(ctx, workspaceID, accountID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeMemberRole", reflect.TypeOf((*MockWorkspaces)(nil).ChangeMemberRole), ctx, workspaceID, accountID, role)
}

// Create mocks base method.
func (m *MockWorkspaces) Create(ctx context.Context, input service.CreateWorkspaceInput) (entity.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(entity.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkspacesMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkspaces)(nil).Create), ctx, input)
}

// ListForAccount mocks base method.
func (m *MockWorkspaces) ListForAccount(ctx context.Context, accountID uuid.UUID) ([]entity.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForAccount", ctx, accountID)
	ret0, _ := ret[0].([]entity.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForAccount indicates an expected call of ListForAccount.
func (mr *MockWorkspacesMockRecorder) ListForAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForAccount", reflect.TypeOf((*MockWorkspaces)(nil).ListForAccount), ctx, accountID)
}

// ListMembers mocks base method.
func (m *MockWorkspaces) ListMembers(ctx context.Context, workspaceID uuid.UUID) ([]entity.Membership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, workspaceID)
	ret0, _ := ret[0].([]entity.Membership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockWorkspacesMockRecorder) ListMembers(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockWorkspaces)(nil).ListMembers), ctx, workspaceID)
}

// RemoveMember mocks base method.
func (m *MockWorkspaces) RemoveMember(ctx context.Context, workspaceID, accountID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, workspaceID, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockWorkspacesMockRecorder) RemoveMember(ctx, workspaceID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockWorkspaces)(nil).RemoveMember), ctx, workspaceID, accountID)
}

// SetAuthPolicy mocks base method.
func (m *MockWorkspaces) SetAuthPolicy(ctx context.Context, workspaceID uuid.UUID, enforcement entity.AuthEnforcement) (entity.WorkspaceAuthPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAuthPolicy", ctx, workspaceID, enforcement)
	ret0, _ := ret[0].(entity.WorkspaceAuthPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAuthPolicy indicates an expected call of SetAuthPolicy.
func (mr *MockWorkspacesMockRecorder) SetAuthPolicy(ctx, workspaceID, enforcement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAuthPolicy", reflect.TypeOf((*MockWorkspaces)(nil).SetAuthPolicy), ctx, workspaceID, enforcement)
}
