// Code generated by MockGen. DO NOT EDIT.
// Source: issue_drafts.go
//
// Generated by this command:
//
//	mockgen -source=issue_drafts.go -destination=issuedraft/mock_issue_drafts.go -package=issuedraft -mock_names=IssueDrafts=MockIssueDrafts
//

// Package issuedraft is a generated GoMock package.
package issuedraft

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/usenorn/norn/internal/entity"
	service "github.com/usenorn/norn/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockIssueDrafts is a mock of IssueDrafts interface.
type MockIssueDrafts struct {
	ctrl     *gomock.Controller
	recorder *MockIssueDraftsMockRecorder
	isgomock struct{}
}

// MockIssueDraftsMockRecorder is the mock recorder for MockIssueDrafts.
type MockIssueDraftsMockRecorder struct {
	mock *MockIssueDrafts
}

// NewMockIssueDrafts creates a new mock instance.
func NewMockIssueDrafts(ctrl *gomock.Controller) *MockIssueDrafts {
	mock := &MockIssueDrafts{ctrl: ctrl}
	mock.recorder = &MockIssueDraftsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueDrafts) EXPECT() *MockIssueDraftsMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockIssueDrafts) List(ctx context.Context, workspaceID uuid.UUID) ([]entity.IssueDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, workspaceID)
	ret0, _ := ret[0].([]entity.IssueDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIssueDraftsMockRecorder) List(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIssueDrafts)(nil).List), ctx, workspaceID)
}

// Remove mocks base method.
func (m *MockIssueDrafts) Remove(ctx context.Context, workspaceID, draftID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, workspaceID, draftID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockIssueDraftsMockRecorder) Remove(ctx, workspaceID, draftID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockIssueDrafts)(nil).Remove), ctx, workspaceID, draftID)
}

// Save mocks base method.
func (m *MockIssueDrafts) Save(ctx context.Context, workspaceID uuid.UUID, input service.SaveIssueDraftInput) (entity.IssueDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, workspaceID, input)
	ret0, _ := ret[0].(entity.IssueDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIssueDraftsMockRecorder) Save(ctx, workspaceID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIssueDrafts)(nil).Save), ctx, workspaceID, input)
}
