// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/goforj/wire"
	"github.com/usenorn/norn/internal/config"
	"github.com/usenorn/norn/internal/handler/http/router"
	"github.com/usenorn/norn/internal/handler/http/sso"
	"github.com/usenorn/norn/internal/handler/http/v1/dashboard"
	"github.com/usenorn/norn/internal/handler/job"
	"github.com/usenorn/norn/internal/observability/logging"
	"github.com/usenorn/norn/internal/pkg/authz"
	"github.com/usenorn/norn/internal/pkg/crypter"
	"github.com/usenorn/norn/internal/pkg/geoip"
	"github.com/usenorn/norn/internal/pkg/objectstore"
	"github.com/usenorn/norn/internal/pkg/oidcprovider"
	"github.com/usenorn/norn/internal/pkg/postgres"
	"github.com/usenorn/norn/internal/pkg/pwned"
	"github.com/usenorn/norn/internal/pkg/samlprovider"
	"github.com/usenorn/norn/internal/pkg/smtp"
	"github.com/usenorn/norn/internal/pkg/taskqueue"
	"github.com/usenorn/norn/internal/pkg/valkey"
	"github.com/usenorn/norn/internal/repository"
	"github.com/usenorn/norn/internal/repository/account"
	"github.com/usenorn/norn/internal/repository/apitoken"
	"github.com/usenorn/norn/internal/repository/blob"
	"github.com/usenorn/norn/internal/repository/breachcheck"
	"github.com/usenorn/norn/internal/repository/breakglass"
	"github.com/usenorn/norn/internal/repository/bulkaction"
	"github.com/usenorn/norn/internal/repository/emailchange"
	"github.com/usenorn/norn/internal/repository/geolocation"
	"github.com/usenorn/norn/internal/repository/invitation"
	"github.com/usenorn/norn/internal/repository/issue"
	"github.com/usenorn/norn/internal/repository/issueactivity"
	"github.com/usenorn/norn/internal/repository/issuerelation"
	"github.com/usenorn/norn/internal/repository/jobqueue"
	"github.com/usenorn/norn/internal/repository/label"
	"github.com/usenorn/norn/internal/repository/labelgroup"
	"github.com/usenorn/norn/internal/repository/mailer"
	"github.com/usenorn/norn/internal/repository/membership"
	oidcprovider2 "github.com/usenorn/norn/internal/repository/oidcprovider"
	"github.com/usenorn/norn/internal/repository/oidcstate"
	"github.com/usenorn/norn/internal/repository/passwordhistory"
	"github.com/usenorn/norn/internal/repository/passwordreset"
	"github.com/usenorn/norn/internal/repository/samlreplay"
	"github.com/usenorn/norn/internal/repository/samlrequest"
	"github.com/usenorn/norn/internal/repository/session"
	"github.com/usenorn/norn/internal/repository/signinthrottle"
	"github.com/usenorn/norn/internal/repository/signup"
	"github.com/usenorn/norn/internal/repository/ssoconnection"
	"github.com/usenorn/norn/internal/repository/ssoidentity"
	"github.com/usenorn/norn/internal/repository/team"
	"github.com/usenorn/norn/internal/repository/teammember"
	"github.com/usenorn/norn/internal/repository/workflowstate"
	"github.com/usenorn/norn/internal/repository/workspace"
	"github.com/usenorn/norn/internal/repository/workspaceauthpolicy"
	account2 "github.com/usenorn/norn/internal/service/account"
	apitoken2 "github.com/usenorn/norn/internal/service/apitoken"
	"github.com/usenorn/norn/internal/service/authorizer"
	"github.com/usenorn/norn/internal/service/bulkoperation"
	invitation2 "github.com/usenorn/norn/internal/service/invitation"
	issue2 "github.com/usenorn/norn/internal/service/issue"
	issuerelation2 "github.com/usenorn/norn/internal/service/issuerelation"
	"github.com/usenorn/norn/internal/service/jobs"
	label2 "github.com/usenorn/norn/internal/service/label"
	session2 "github.com/usenorn/norn/internal/service/session"
	ssoconnection2 "github.com/usenorn/norn/internal/service/ssoconnection"
	team2 "github.com/usenorn/norn/internal/service/team"
	workflowstate2 "github.com/usenorn/norn/internal/service/workflowstate"
	workspace2 "github.com/usenorn/norn/internal/service/workspace"
)

// Injectors from wire.go:

func InitApp(cfgFile string) (*App, func(), error) {
	configConfig, err := config.New(cfgFile)
	if err != nil {
		return nil, nil, err
	}
	http := config.NewHTTP(configConfig)
	configSession := config.NewSession(configConfig)
	configValkey := config.NewValkey(configConfig)
	client, cleanup, err := valkey.New(configValkey)
	if err != nil {
		return nil, nil, err
	}
	repositorySession := session.New(client, configSession)
	configPostgres := config.NewPostgres(configConfig)
	postgresClient, cleanup2, err := postgres.New(configPostgres)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repositoryAccount := account.New(postgresClient)
	repositoryMembership := membership.New(postgresClient)
	geoIP := config.NewGeoIP(configConfig)
	geoipClient, cleanup3, err := geoip.New(geoIP)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	geoLocator := geolocation.New(geoipClient)
	signInThrottle := signinthrottle.New(client)
	casbin := config.NewCasbin(configConfig)
	enforcer, cleanup4, err := authz.New(casbin, postgresClient, client)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	workspaceAuthPolicy := workspaceauthpolicy.New(postgresClient)
	repositoryWorkspace := workspace.New(postgresClient)
	repositoryTeam := team.New(postgresClient)
	serviceAuthorizer := authorizer.New(enforcer, repositoryMembership, workspaceAuthPolicy, repositoryWorkspace, repositoryTeam, repositoryAccount)
	sessions := session2.New(repositorySession, repositoryAccount, repositoryMembership, geoLocator, signInThrottle, configSession, serviceAuthorizer)
	apiToken := apitoken.New(postgresClient)
	apiTokens := apitoken2.New(apiToken, repositoryMembership, repositoryAccount, serviceAuthorizer)
	emailChange := emailchange.New(postgresClient)
	passwordReset := passwordreset.New(postgresClient)
	signUp := signup.New(postgresClient)
	passwordHistory := passwordhistory.New(postgresClient)
	password := config.NewPassword(configConfig)
	pwnedClient := pwned.New(password)
	breachCheck := breachcheck.New(pwnedClient)
	storage := config.NewStorage(configConfig)
	objectstoreClient, err := objectstore.New(storage)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	repositoryBlob := blob.New(objectstoreClient)
	configSMTP := config.NewSMTP(configConfig)
	smtpClient, cleanup5, err := smtp.New(configSMTP)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	repositoryMailer := mailer.New(smtpClient)
	asynq := config.NewAsynq(configConfig)
	taskqueueClient, cleanup6, err := taskqueue.NewClient(asynq)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	inspector, cleanup7, err := taskqueue.NewInspector(asynq)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jobqueueClient := jobqueue.NewClient(taskqueueClient, inspector, asynq)
	jobProducer := jobqueue.AsProducer(jobqueueClient)
	app := config.NewApp(configConfig)
	instance := config.NewInstance(configConfig)
	accounts := account2.New(repositoryAccount, emailChange, passwordReset, signUp, passwordHistory, repositoryMembership, repositoryWorkspace, workspaceAuthPolicy, breachCheck, signInThrottle, repositoryBlob, repositoryMailer, jobProducer, postgresClient, sessions, serviceAuthorizer, app, configSMTP, instance)
	teamMember := teammember.New(postgresClient)
	workflowState := workflowstate.New(postgresClient)
	security := config.NewSecurity(configConfig)
	crypterCrypter, err := crypter.New(security)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ssoConnection := ssoconnection.New(postgresClient, crypterCrypter)
	ssoIdentity := ssoidentity.New(postgresClient)
	breakGlass := breakglass.New(postgresClient)
	configWorkspace := config.NewWorkspace(configConfig)
	workspaces := workspace2.New(repositoryWorkspace, repositoryMembership, repositoryAccount, repositoryTeam, teamMember, workflowState, workspaceAuthPolicy, ssoConnection, ssoIdentity, breakGlass, jobProducer, serviceAuthorizer, postgresClient, configWorkspace)
	teams := team2.New(repositoryTeam, teamMember, repositoryWorkspace, repositoryMembership, repositoryAccount, workspaceAuthPolicy, workflowState, serviceAuthorizer, postgresClient)
	repositoryInvitation := invitation.New(postgresClient)
	invitations := invitation2.New(repositoryInvitation, repositoryMembership, repositoryWorkspace, repositoryAccount, repositoryTeam, teamMember, workspaceAuthPolicy, jobProducer, repositoryMailer, postgresClient, serviceAuthorizer, accounts, sessions, app, configSMTP)
	repositoryIssue := issue.New(postgresClient)
	issueActivity := issueactivity.New(postgresClient)
	repositoryLabel := label.New(postgresClient)
	issues := issue2.New(repositoryIssue, workflowState, issueActivity, repositoryLabel, repositoryMembership, jobProducer, serviceAuthorizer, postgresClient)
	issueRelation := issuerelation.New(postgresClient)
	issueRelations := issuerelation2.New(issueRelation, repositoryIssue, workflowState, issueActivity, serviceAuthorizer, postgresClient)
	bulkAction := bulkaction.New(postgresClient)
	bulkOperations := bulkoperation.New(bulkAction, repositoryIssue, workflowState, repositoryLabel, issueActivity, repositoryMembership, jobProducer, serviceAuthorizer, postgresClient)
	workflowStates := workflowstate2.New(workflowState, repositoryIssue, repositoryTeam, serviceAuthorizer, postgresClient)
	labelGroup := labelgroup.New(postgresClient)
	labels := label2.New(repositoryLabel, labelGroup, repositoryTeam, serviceAuthorizer, postgresClient)
	oidc := config.NewOIDC(configConfig)
	oidcState := oidcstate.New(client, oidc)
	saml := config.NewSAML(configConfig)
	samlRequest := samlrequest.New(client, saml)
	samlReplay := samlreplay.New(client, saml)
	oidcproviderClient := oidcprovider.New(oidc)
	oidcProvider := oidcprovider2.New(oidcproviderClient, app)
	samlproviderClient := samlprovider.New(saml)
	ssoConnections := ssoconnection2.New(ssoConnection, ssoIdentity, oidcState, samlRequest, samlReplay, repositoryWorkspace, repositoryAccount, repositoryMembership, oidcProvider, samlproviderClient, repositoryMailer, sessions, app, serviceAuthorizer, postgresClient)
	strictServerInterface := dashboard.New(accounts, workspaces, teams, invitations, issues, issueRelations, bulkOperations, workflowStates, labels, apiTokens, sessions, ssoConnections, repositoryBlob, app, instance, configSession)
	callback := sso.NewCallback(ssoConnections, configSession)
	ssoSAML := sso.NewSAML(ssoConnections, configSession)
	handler := router.New(http, configSession, sessions, apiTokens, strictServerInterface, callback, ssoSAML)
	logger, err := logging.New(app)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	internalApp := NewApp(http, handler, logger)
	return internalApp, func() {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func InitWorker(cfgFile string) (*Worker, func(), error) {
	configConfig, err := config.New(cfgFile)
	if err != nil {
		return nil, nil, err
	}
	saml := config.NewSAML(configConfig)
	asynq := config.NewAsynq(configConfig)
	app := config.NewApp(configConfig)
	logger, err := logging.New(app)
	if err != nil {
		return nil, nil, err
	}
	server := taskqueue.NewServer(asynq, logger)
	scheduler := taskqueue.NewScheduler(asynq, logger)
	configPostgres := config.NewPostgres(configConfig)
	client, cleanup, err := postgres.New(configPostgres)
	if err != nil {
		return nil, nil, err
	}
	repositoryAccount := account.New(client)
	emailChange := emailchange.New(client)
	passwordReset := passwordreset.New(client)
	signUp := signup.New(client)
	passwordHistory := passwordhistory.New(client)
	repositoryMembership := membership.New(client)
	repositoryWorkspace := workspace.New(client)
	workspaceAuthPolicy := workspaceauthpolicy.New(client)
	password := config.NewPassword(configConfig)
	pwnedClient := pwned.New(password)
	breachCheck := breachcheck.New(pwnedClient)
	configValkey := config.NewValkey(configConfig)
	valkeyClient, cleanup2, err := valkey.New(configValkey)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	signInThrottle := signinthrottle.New(valkeyClient)
	storage := config.NewStorage(configConfig)
	objectstoreClient, err := objectstore.New(storage)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	repositoryBlob := blob.New(objectstoreClient)
	configSMTP := config.NewSMTP(configConfig)
	smtpClient, cleanup3, err := smtp.New(configSMTP)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	repositoryMailer := mailer.New(smtpClient)
	taskqueueClient, cleanup4, err := taskqueue.NewClient(asynq)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	inspector, cleanup5, err := taskqueue.NewInspector(asynq)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jobqueueClient := jobqueue.NewClient(taskqueueClient, inspector, asynq)
	jobProducer := jobqueue.AsProducer(jobqueueClient)
	configSession := config.NewSession(configConfig)
	repositorySession := session.New(valkeyClient, configSession)
	geoIP := config.NewGeoIP(configConfig)
	geoipClient, cleanup6, err := geoip.New(geoIP)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	geoLocator := geolocation.New(geoipClient)
	casbin := config.NewCasbin(configConfig)
	enforcer, cleanup7, err := authz.New(casbin, client, valkeyClient)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	repositoryTeam := team.New(client)
	serviceAuthorizer := authorizer.New(enforcer, repositoryMembership, workspaceAuthPolicy, repositoryWorkspace, repositoryTeam, repositoryAccount)
	sessions := session2.New(repositorySession, repositoryAccount, repositoryMembership, geoLocator, signInThrottle, configSession, serviceAuthorizer)
	instance := config.NewInstance(configConfig)
	accounts := account2.New(repositoryAccount, emailChange, passwordReset, signUp, passwordHistory, repositoryMembership, repositoryWorkspace, workspaceAuthPolicy, breachCheck, signInThrottle, repositoryBlob, repositoryMailer, jobProducer, client, sessions, serviceAuthorizer, app, configSMTP, instance)
	signUpVerificationHandler := job.NewSignUpVerificationHandler(accounts)
	emailChangeConfirmationHandler := job.NewEmailChangeConfirmationHandler(accounts)
	passwordResetHandler := job.NewPasswordResetHandler(accounts)
	passwordResetSSONoticeHandler := job.NewPasswordResetSSONoticeHandler(accounts)
	repositoryInvitation := invitation.New(client)
	teamMember := teammember.New(client)
	invitations := invitation2.New(repositoryInvitation, repositoryMembership, repositoryWorkspace, repositoryAccount, repositoryTeam, teamMember, workspaceAuthPolicy, jobProducer, repositoryMailer, client, serviceAuthorizer, accounts, sessions, app, configSMTP)
	invitationHandler := job.NewInvitationHandler(invitations)
	workflowState := workflowstate.New(client)
	security := config.NewSecurity(configConfig)
	crypterCrypter, err := crypter.New(security)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ssoConnection := ssoconnection.New(client, crypterCrypter)
	ssoIdentity := ssoidentity.New(client)
	breakGlass := breakglass.New(client)
	configWorkspace := config.NewWorkspace(configConfig)
	workspaces := workspace2.New(repositoryWorkspace, repositoryMembership, repositoryAccount, repositoryTeam, teamMember, workflowState, workspaceAuthPolicy, ssoConnection, ssoIdentity, breakGlass, jobProducer, serviceAuthorizer, client, configWorkspace)
	workspacePurgeHandler := job.NewWorkspacePurgeHandler(workspaces)
	repositoryIssue := issue.New(client)
	issueActivity := issueactivity.New(client)
	repositoryLabel := label.New(client)
	issues := issue2.New(repositoryIssue, workflowState, issueActivity, repositoryLabel, repositoryMembership, jobProducer, serviceAuthorizer, client)
	issuePurgeHandler := job.NewIssuePurgeHandler(issues)
	bulkAction := bulkaction.New(client)
	bulkOperations := bulkoperation.New(bulkAction, repositoryIssue, workflowState, repositoryLabel, issueActivity, repositoryMembership, jobProducer, serviceAuthorizer, client)
	bulkApplyHandler := job.NewBulkApplyHandler(bulkOperations)
	oidc := config.NewOIDC(configConfig)
	oidcState := oidcstate.New(valkeyClient, oidc)
	samlRequest := samlrequest.New(valkeyClient, saml)
	samlReplay := samlreplay.New(valkeyClient, saml)
	oidcproviderClient := oidcprovider.New(oidc)
	oidcProvider := oidcprovider2.New(oidcproviderClient, app)
	samlproviderClient := samlprovider.New(saml)
	ssoConnections := ssoconnection2.New(ssoConnection, ssoIdentity, oidcState, samlRequest, samlReplay, repositoryWorkspace, repositoryAccount, repositoryMembership, oidcProvider, samlproviderClient, repositoryMailer, sessions, app, serviceAuthorizer, client)
	ssoCertificateSweepHandler := job.NewSSOCertificateSweepHandler(ssoConnections)
	serveMux := NewServeMux(signUpVerificationHandler, emailChangeConfirmationHandler, passwordResetHandler, passwordResetSSONoticeHandler, invitationHandler, workspacePurgeHandler, issuePurgeHandler, bulkApplyHandler, ssoCertificateSweepHandler)
	worker := NewWorker(saml, server, scheduler, serveMux, logger)
	return worker, func() {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func InitMigrator(cfgFile string) (*Migrator, func(), error) {
	configConfig, err := config.New(cfgFile)
	if err != nil {
		return nil, nil, err
	}
	configPostgres := config.NewPostgres(configConfig)
	client, cleanup, err := postgres.New(configPostgres)
	if err != nil {
		return nil, nil, err
	}
	app := config.NewApp(configConfig)
	logger, err := logging.New(app)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	migrator, err := NewMigrator(client, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return migrator, func() {
		cleanup()
	}, nil
}

func InitSeeder(cfgFile string) (*Seeder, func(), error) {
	configConfig, err := config.New(cfgFile)
	if err != nil {
		return nil, nil, err
	}
	casbin := config.NewCasbin(configConfig)
	configPostgres := config.NewPostgres(configConfig)
	client, cleanup, err := postgres.New(configPostgres)
	if err != nil {
		return nil, nil, err
	}
	configValkey := config.NewValkey(configConfig)
	valkeyClient, cleanup2, err := valkey.New(configValkey)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	enforcer, cleanup3, err := authz.New(casbin, client, valkeyClient)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	repositoryMembership := membership.New(client)
	workspaceAuthPolicy := workspaceauthpolicy.New(client)
	repositoryWorkspace := workspace.New(client)
	repositoryTeam := team.New(client)
	repositoryAccount := account.New(client)
	serviceAuthorizer := authorizer.New(enforcer, repositoryMembership, workspaceAuthPolicy, repositoryWorkspace, repositoryTeam, repositoryAccount)
	app := config.NewApp(configConfig)
	logger, err := logging.New(app)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	seeder := NewSeeder(serviceAuthorizer, logger)
	return seeder, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func InitJobsAdmin(cfgFile string) (*JobsAdmin, func(), error) {
	configConfig, err := config.New(cfgFile)
	if err != nil {
		return nil, nil, err
	}
	asynq := config.NewAsynq(configConfig)
	client, cleanup, err := taskqueue.NewClient(asynq)
	if err != nil {
		return nil, nil, err
	}
	inspector, cleanup2, err := taskqueue.NewInspector(asynq)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	jobqueueClient := jobqueue.NewClient(client, inspector, asynq)
	jobInspector := jobqueue.AsInspector(jobqueueClient)
	serviceJobs := jobs.New(jobInspector)
	jobsAdmin := NewJobsAdmin(serviceJobs)
	return jobsAdmin, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var baseSet = wire.NewSet(config.Set, logging.Set, postgres.Set, valkey.Set, taskqueue.Set, smtp.Set, objectstore.Set, authz.Set, geoip.Set, pwned.Set, crypter.Set, oidcprovider.Set, samlprovider.Set, wire.Bind(new(repository.Transactor), new(*postgres.Client)), account.Set, emailchange.Set, workspace.Set, membership.Set, session.Set, blob.Set, mailer.Set, jobqueue.Set, geolocation.Set, workspaceauthpolicy.Set, passwordreset.Set, signup.Set, issue.Set, issueactivity.Set, issuerelation.Set, bulkaction.Set, label.Set, labelgroup.Set, workflowstate.Set, apitoken.Set, passwordhistory.Set, signinthrottle.Set, breachcheck.Set, invitation.Set, team.Set, teammember.Set, ssoconnection.Set, ssoidentity.Set, breakglass.Set, samlrequest.Set, samlreplay.Set, oidcstate.Set, oidcprovider2.Set, account2.Set, workspace2.Set, invitation2.Set, team2.Set, issue2.Set, issuerelation2.Set, bulkoperation.Set, label2.Set, workflowstate2.Set, apitoken2.Set, session2.Set, authorizer.Set, jobs.Set, ssoconnection2.Set, dashboard.Set, sso.Set, router.Set, job.Set, NewApp,
	NewServeMux,
	NewWorker,
	NewMigrator,
	NewSeeder,
	NewJobsAdmin,
)
