// Code generated by MockGen. DO NOT EDIT.
// Source: issue_delegation.go
//
// Generated by this command:
//
//	mockgen -source=issue_delegation.go -destination=issuedelegation/mock_issue_delegation.go -package=issuedelegation -mock_names=IssueDelegation=MockIssueDelegation
//

// Package issuedelegation is a generated GoMock package.
package issuedelegation

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/usenorn/norn/internal/entity"
	repository "github.com/usenorn/norn/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockIssueDelegation is a mock of IssueDelegation interface.
type MockIssueDelegation struct {
	ctrl     *gomock.Controller
	recorder *MockIssueDelegationMockRecorder
	isgomock struct{}
}

// MockIssueDelegationMockRecorder is the mock recorder for MockIssueDelegation.
type MockIssueDelegationMockRecorder struct {
	mock *MockIssueDelegation
}

// NewMockIssueDelegation creates a new mock instance.
func NewMockIssueDelegation(ctrl *gomock.Controller) *MockIssueDelegation {
	mock := &MockIssueDelegation{ctrl: ctrl}
	mock.recorder = &MockIssueDelegationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueDelegation) EXPECT() *MockIssueDelegationMockRecorder {
	return m.recorder
}

// Delegate mocks base method.
func (m *MockIssueDelegation) Delegate(ctx context.Context, delegation entity.IssueDelegation) (entity.IssueDelegation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delegate", ctx, delegation)
	ret0, _ := ret[0].(entity.IssueDelegation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delegate indicates an expected call of Delegate.
func (mr *MockIssueDelegationMockRecorder) Delegate(ctx, delegation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delegate", reflect.TypeOf((*MockIssueDelegation)(nil).Delegate), ctx, delegation)
}

// ListByIssue mocks base method.
func (m *MockIssueDelegation) ListByIssue(ctx context.Context, workspaceID, issueID uuid.UUID) ([]entity.IssueDelegation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIssue", ctx, workspaceID, issueID)
	ret0, _ := ret[0].([]entity.IssueDelegation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIssue indicates an expected call of ListByIssue.
func (mr *MockIssueDelegationMockRecorder) ListByIssue(ctx, workspaceID, issueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIssue", reflect.TypeOf((*MockIssueDelegation)(nil).ListByIssue), ctx, workspaceID, issueID)
}

// Recall mocks base method.
func (m *MockIssueDelegation) Recall(ctx context.Context, workspaceID uuid.UUID, recall repository.RecallDelegation) (entity.IssueDelegation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recall", ctx, workspaceID, recall)
	ret0, _ := ret[0].(entity.IssueDelegation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recall indicates an expected call of Recall.
func (mr *MockIssueDelegationMockRecorder) Recall(ctx, workspaceID, recall any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recall", reflect.TypeOf((*MockIssueDelegation)(nil).Recall), ctx, workspaceID, recall)
}
